// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: twilight/mining/v1/mining.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Enum numeric values are permanent after release. Future upgrades may add
// values but must not reuse, reorder, or change existing numeric values.
//
// The mode is chain-wide, authority-scheduled, historically versioned, effective
// only at epoch boundaries, and non-retroactive. There is deliberately no
// per-Slot opt-out and no boolean shorthand: POC 1 reaches only
// TRUSTED_AS_DISTRIBUTION, but the value that makes protocol Selection reachable
// exists from the first release so a later tranche adds a producer rather than a
// state migration.
type MiningDistributionMode int32

const (
	MiningDistributionMode_MINING_DISTRIBUTION_MODE_UNSPECIFIED             MiningDistributionMode = 0
	MiningDistributionMode_MINING_DISTRIBUTION_MODE_TRUSTED_AS_DISTRIBUTION MiningDistributionMode = 1
	MiningDistributionMode_MINING_DISTRIBUTION_MODE_PROTOCOL_SELECTION      MiningDistributionMode = 2
)

var MiningDistributionMode_name = map[int32]string{
	0: "MINING_DISTRIBUTION_MODE_UNSPECIFIED",
	1: "MINING_DISTRIBUTION_MODE_TRUSTED_AS_DISTRIBUTION",
	2: "MINING_DISTRIBUTION_MODE_PROTOCOL_SELECTION",
}

var MiningDistributionMode_value = map[string]int32{
	"MINING_DISTRIBUTION_MODE_UNSPECIFIED":             0,
	"MINING_DISTRIBUTION_MODE_TRUSTED_AS_DISTRIBUTION": 1,
	"MINING_DISTRIBUTION_MODE_PROTOCOL_SELECTION":      2,
}

func (x MiningDistributionMode) String() string {
	return proto.EnumName(MiningDistributionMode_name, int32(x))
}

func (MiningDistributionMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1e6f922626df5586, []int{0}
}

// Enum numeric values are permanent after release. Future upgrades may add
// values but must not reuse, reorder, or change existing numeric values.
//
// The technical mode a materialized settlement was created under. It is immutable
// once materialized and decides whether participant chunks are admissible at all:
// OPERATOR_ONLY admits none. Only TRUSTED_AS is reachable in POC 1; the other two
// exist as structure for the Selection tranche and must not acquire an
// applicability rule here.
type SettlementMode int32

const (
	SettlementMode_SETTLEMENT_MODE_UNSPECIFIED           SettlementMode = 0
	SettlementMode_SETTLEMENT_MODE_TRUSTED_AS            SettlementMode = 1
	SettlementMode_SETTLEMENT_MODE_SELECTED_PARTICIPANTS SettlementMode = 2
	SettlementMode_SETTLEMENT_MODE_OPERATOR_ONLY         SettlementMode = 3
)

var SettlementMode_name = map[int32]string{
	0: "SETTLEMENT_MODE_UNSPECIFIED",
	1: "SETTLEMENT_MODE_TRUSTED_AS",
	2: "SETTLEMENT_MODE_SELECTED_PARTICIPANTS",
	3: "SETTLEMENT_MODE_OPERATOR_ONLY",
}

var SettlementMode_value = map[string]int32{
	"SETTLEMENT_MODE_UNSPECIFIED":           0,
	"SETTLEMENT_MODE_TRUSTED_AS":            1,
	"SETTLEMENT_MODE_SELECTED_PARTICIPANTS": 2,
	"SETTLEMENT_MODE_OPERATOR_ONLY":         3,
}

func (x SettlementMode) String() string {
	return proto.EnumName(SettlementMode_name, int32(x))
}

func (SettlementMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1e6f922626df5586, []int{1}
}

// Enum numeric values are permanent after release. Future upgrades may add
// values but must not reuse, reorder, or change existing numeric values.
//
// Records the authorization ARM through which a settlement reached FINALIZED,
// never the identity of the caller. UNSPECIFIED is valid only while a settlement
// is OPEN; a FINALIZED settlement carries exactly one other value.
//
// This is immutable audit metadata. Nothing may branch on it to decide who may
// act or where value goes.
type SettlementFinalizationReason int32

const (
	SettlementFinalizationReason_SETTLEMENT_FINALIZATION_REASON_UNSPECIFIED                   SettlementFinalizationReason = 0
	SettlementFinalizationReason_SETTLEMENT_FINALIZATION_REASON_AUTHORIZED_EARLY              SettlementFinalizationReason = 1
	SettlementFinalizationReason_SETTLEMENT_FINALIZATION_REASON_PERMISSIONLESS_AFTER_DEADLINE SettlementFinalizationReason = 2
	SettlementFinalizationReason_SETTLEMENT_FINALIZATION_REASON_PERMISSIONLESS_OPERATOR_ONLY  SettlementFinalizationReason = 3
)

var SettlementFinalizationReason_name = map[int32]string{
	0: "SETTLEMENT_FINALIZATION_REASON_UNSPECIFIED",
	1: "SETTLEMENT_FINALIZATION_REASON_AUTHORIZED_EARLY",
	2: "SETTLEMENT_FINALIZATION_REASON_PERMISSIONLESS_AFTER_DEADLINE",
	3: "SETTLEMENT_FINALIZATION_REASON_PERMISSIONLESS_OPERATOR_ONLY",
}

var SettlementFinalizationReason_value = map[string]int32{
	"SETTLEMENT_FINALIZATION_REASON_UNSPECIFIED":                   0,
	"SETTLEMENT_FINALIZATION_REASON_AUTHORIZED_EARLY":              1,
	"SETTLEMENT_FINALIZATION_REASON_PERMISSIONLESS_AFTER_DEADLINE": 2,
	"SETTLEMENT_FINALIZATION_REASON_PERMISSIONLESS_OPERATOR_ONLY":  3,
}

func (x SettlementFinalizationReason) String() string {
	return proto.EnumName(SettlementFinalizationReason_name, int32(x))
}

func (SettlementFinalizationReason) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1e6f922626df5586, []int{2}
}

// MiningDistributionModeVersion is one immutable entry of the chain-wide
// distribution-mode history.
//
// It carries a validity INTERVAL rather than a single effective epoch, which is
// what distinguishes it from the reward and settlement parameter families. The
// interval shape is canonical and must not be flattened into the effective-epoch
// record used by the other histories.
type MiningDistributionModeVersion struct {
	Version        uint64                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Mode           MiningDistributionMode `protobuf:"varint,2,opt,name=mode,proto3,enum=twilight.mining.v1.MiningDistributionMode" json:"mode,omitempty"`
	ValidFromEpoch uint64                 `protobuf:"varint,3,opt,name=valid_from_epoch,json=validFromEpoch,proto3" json:"valid_from_epoch,omitempty"`
	// valid_until_epoch_exclusive is 0 for an open-ended current version.
	ValidUntilEpochExclusive uint64 `protobuf:"varint,4,opt,name=valid_until_epoch_exclusive,json=validUntilEpochExclusive,proto3" json:"valid_until_epoch_exclusive,omitempty"`
}

func (m *MiningDistributionModeVersion) Reset()         { *m = MiningDistributionModeVersion{} }
func (m *MiningDistributionModeVersion) String() string { return proto.CompactTextString(m) }
func (*MiningDistributionModeVersion) ProtoMessage()    {}
func (*MiningDistributionModeVersion) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e6f922626df5586, []int{0}
}
func (m *MiningDistributionModeVersion) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MiningDistributionModeVersion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MiningDistributionModeVersion.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MiningDistributionModeVersion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MiningDistributionModeVersion.Merge(m, src)
}
func (m *MiningDistributionModeVersion) XXX_Size() int {
	return m.Size()
}
func (m *MiningDistributionModeVersion) XXX_DiscardUnknown() {
	xxx_messageInfo_MiningDistributionModeVersion.DiscardUnknown(m)
}

var xxx_messageInfo_MiningDistributionModeVersion proto.InternalMessageInfo

func (m *MiningDistributionModeVersion) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *MiningDistributionModeVersion) GetMode() MiningDistributionMode {
	if m != nil {
		return m.Mode
	}
	return MiningDistributionMode_MINING_DISTRIBUTION_MODE_UNSPECIFIED
}

func (m *MiningDistributionModeVersion) GetValidFromEpoch() uint64 {
	if m != nil {
		return m.ValidFromEpoch
	}
	return 0
}

func (m *MiningDistributionModeVersion) GetValidUntilEpochExclusive() uint64 {
	if m != nil {
		return m.ValidUntilEpochExclusive
	}
	return 0
}

// ScheduledMiningDistributionMode is the single pending mode change, keyed by the
// epoch it becomes effective at.
//
// POC 1 defines the shape and provides no writer: there is no mode-update
// transaction, so this collection is permanently empty and the promotion path is
// unreachable.
type ScheduledMiningDistributionMode struct {
	EffectiveEpoch uint64                 `protobuf:"varint,1,opt,name=effective_epoch,json=effectiveEpoch,proto3" json:"effective_epoch,omitempty"`
	Mode           MiningDistributionMode `protobuf:"varint,2,opt,name=mode,proto3,enum=twilight.mining.v1.MiningDistributionMode" json:"mode,omitempty"`
}

func (m *ScheduledMiningDistributionMode) Reset()         { *m = ScheduledMiningDistributionMode{} }
func (m *ScheduledMiningDistributionMode) String() string { return proto.CompactTextString(m) }
func (*ScheduledMiningDistributionMode) ProtoMessage()    {}
func (*ScheduledMiningDistributionMode) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e6f922626df5586, []int{1}
}
func (m *ScheduledMiningDistributionMode) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ScheduledMiningDistributionMode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ScheduledMiningDistributionMode.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ScheduledMiningDistributionMode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScheduledMiningDistributionMode.Merge(m, src)
}
func (m *ScheduledMiningDistributionMode) XXX_Size() int {
	return m.Size()
}
func (m *ScheduledMiningDistributionMode) XXX_DiscardUnknown() {
	xxx_messageInfo_ScheduledMiningDistributionMode.DiscardUnknown(m)
}

var xxx_messageInfo_ScheduledMiningDistributionMode proto.InternalMessageInfo

func (m *ScheduledMiningDistributionMode) GetEffectiveEpoch() uint64 {
	if m != nil {
		return m.EffectiveEpoch
	}
	return 0
}

func (m *ScheduledMiningDistributionMode) GetMode() MiningDistributionMode {
	if m != nil {
		return m.Mode
	}
	return MiningDistributionMode_MINING_DISTRIBUTION_MODE_UNSPECIFIED
}

// SelectionParamsVersion is one immutable entry of the global Selection-parameter
// history.
//
// POC 1 creates the genesis version because canonical fresh genesis requires the
// history and requires every ACTIVE CoreSlot policy to satisfy it. Nothing in
// POC 1 runs Selection, and no runtime update path exists.
type SelectionParamsVersion struct {
	Version                             uint64 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	EffectiveEpoch                      uint64 `protobuf:"varint,2,opt,name=effective_epoch,json=effectiveEpoch,proto3" json:"effective_epoch,omitempty"`
	MaxSelectionRateBps                 uint64 `protobuf:"varint,3,opt,name=max_selection_rate_bps,json=maxSelectionRateBps,proto3" json:"max_selection_rate_bps,omitempty"`
	MaxSelectedParticipantsPerSelection uint64 `protobuf:"varint,4,opt,name=max_selected_participants_per_selection,json=maxSelectedParticipantsPerSelection,proto3" json:"max_selected_participants_per_selection,omitempty"`
	MaxCandidatesPerSelection           uint64 `protobuf:"varint,5,opt,name=max_candidates_per_selection,json=maxCandidatesPerSelection,proto3" json:"max_candidates_per_selection,omitempty"`
	BeaconStartOffsetBlocks             uint64 `protobuf:"varint,6,opt,name=beacon_start_offset_blocks,json=beaconStartOffsetBlocks,proto3" json:"beacon_start_offset_blocks,omitempty"`
	BeaconWindowBlocks                  uint64 `protobuf:"varint,7,opt,name=beacon_window_blocks,json=beaconWindowBlocks,proto3" json:"beacon_window_blocks,omitempty"`
	MinExternalBeaconBlocks             uint64 `protobuf:"varint,8,opt,name=min_external_beacon_blocks,json=minExternalBeaconBlocks,proto3" json:"min_external_beacon_blocks,omitempty"`
	MinDistinctExternalProposers        uint64 `protobuf:"varint,9,opt,name=min_distinct_external_proposers,json=minDistinctExternalProposers,proto3" json:"min_distinct_external_proposers,omitempty"`
}

func (m *SelectionParamsVersion) Reset()         { *m = SelectionParamsVersion{} }
func (m *SelectionParamsVersion) String() string { return proto.CompactTextString(m) }
func (*SelectionParamsVersion) ProtoMessage()    {}
func (*SelectionParamsVersion) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e6f922626df5586, []int{2}
}
func (m *SelectionParamsVersion) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SelectionParamsVersion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SelectionParamsVersion.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SelectionParamsVersion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelectionParamsVersion.Merge(m, src)
}
func (m *SelectionParamsVersion) XXX_Size() int {
	return m.Size()
}
func (m *SelectionParamsVersion) XXX_DiscardUnknown() {
	xxx_messageInfo_SelectionParamsVersion.DiscardUnknown(m)
}

var xxx_messageInfo_SelectionParamsVersion proto.InternalMessageInfo

func (m *SelectionParamsVersion) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *SelectionParamsVersion) GetEffectiveEpoch() uint64 {
	if m != nil {
		return m.EffectiveEpoch
	}
	return 0
}

func (m *SelectionParamsVersion) GetMaxSelectionRateBps() uint64 {
	if m != nil {
		return m.MaxSelectionRateBps
	}
	return 0
}

func (m *SelectionParamsVersion) GetMaxSelectedParticipantsPerSelection() uint64 {
	if m != nil {
		return m.MaxSelectedParticipantsPerSelection
	}
	return 0
}

func (m *SelectionParamsVersion) GetMaxCandidatesPerSelection() uint64 {
	if m != nil {
		return m.MaxCandidatesPerSelection
	}
	return 0
}

func (m *SelectionParamsVersion) GetBeaconStartOffsetBlocks() uint64 {
	if m != nil {
		return m.BeaconStartOffsetBlocks
	}
	return 0
}

func (m *SelectionParamsVersion) GetBeaconWindowBlocks() uint64 {
	if m != nil {
		return m.BeaconWindowBlocks
	}
	return 0
}

func (m *SelectionParamsVersion) GetMinExternalBeaconBlocks() uint64 {
	if m != nil {
		return m.MinExternalBeaconBlocks
	}
	return 0
}

func (m *SelectionParamsVersion) GetMinDistinctExternalProposers() uint64 {
	if m != nil {
		return m.MinDistinctExternalProposers
	}
	return 0
}

// ScheduledSelectionParams is the single pending Selection-parameter change.
// POC 1 defines the shape and provides no writer.
type ScheduledSelectionParams struct {
	EffectiveEpoch                      uint64 `protobuf:"varint,1,opt,name=effective_epoch,json=effectiveEpoch,proto3" json:"effective_epoch,omitempty"`
	MaxSelectionRateBps                 uint64 `protobuf:"varint,2,opt,name=max_selection_rate_bps,json=maxSelectionRateBps,proto3" json:"max_selection_rate_bps,omitempty"`
	MaxSelectedParticipantsPerSelection uint64 `protobuf:"varint,3,opt,name=max_selected_participants_per_selection,json=maxSelectedParticipantsPerSelection,proto3" json:"max_selected_participants_per_selection,omitempty"`
	MaxCandidatesPerSelection           uint64 `protobuf:"varint,4,opt,name=max_candidates_per_selection,json=maxCandidatesPerSelection,proto3" json:"max_candidates_per_selection,omitempty"`
	BeaconStartOffsetBlocks             uint64 `protobuf:"varint,5,opt,name=beacon_start_offset_blocks,json=beaconStartOffsetBlocks,proto3" json:"beacon_start_offset_blocks,omitempty"`
	BeaconWindowBlocks                  uint64 `protobuf:"varint,6,opt,name=beacon_window_blocks,json=beaconWindowBlocks,proto3" json:"beacon_window_blocks,omitempty"`
	MinExternalBeaconBlocks             uint64 `protobuf:"varint,7,opt,name=min_external_beacon_blocks,json=minExternalBeaconBlocks,proto3" json:"min_external_beacon_blocks,omitempty"`
	MinDistinctExternalProposers        uint64 `protobuf:"varint,8,opt,name=min_distinct_external_proposers,json=minDistinctExternalProposers,proto3" json:"min_distinct_external_proposers,omitempty"`
}

func (m *ScheduledSelectionParams) Reset()         { *m = ScheduledSelectionParams{} }
func (m *ScheduledSelectionParams) String() string { return proto.CompactTextString(m) }
func (*ScheduledSelectionParams) ProtoMessage()    {}
func (*ScheduledSelectionParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e6f922626df5586, []int{3}
}
func (m *ScheduledSelectionParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ScheduledSelectionParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ScheduledSelectionParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ScheduledSelectionParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScheduledSelectionParams.Merge(m, src)
}
func (m *ScheduledSelectionParams) XXX_Size() int {
	return m.Size()
}
func (m *ScheduledSelectionParams) XXX_DiscardUnknown() {
	xxx_messageInfo_ScheduledSelectionParams.DiscardUnknown(m)
}

var xxx_messageInfo_ScheduledSelectionParams proto.InternalMessageInfo

func (m *ScheduledSelectionParams) GetEffectiveEpoch() uint64 {
	if m != nil {
		return m.EffectiveEpoch
	}
	return 0
}

func (m *ScheduledSelectionParams) GetMaxSelectionRateBps() uint64 {
	if m != nil {
		return m.MaxSelectionRateBps
	}
	return 0
}

func (m *ScheduledSelectionParams) GetMaxSelectedParticipantsPerSelection() uint64 {
	if m != nil {
		return m.MaxSelectedParticipantsPerSelection
	}
	return 0
}

func (m *ScheduledSelectionParams) GetMaxCandidatesPerSelection() uint64 {
	if m != nil {
		return m.MaxCandidatesPerSelection
	}
	return 0
}

func (m *ScheduledSelectionParams) GetBeaconStartOffsetBlocks() uint64 {
	if m != nil {
		return m.BeaconStartOffsetBlocks
	}
	return 0
}

func (m *ScheduledSelectionParams) GetBeaconWindowBlocks() uint64 {
	if m != nil {
		return m.BeaconWindowBlocks
	}
	return 0
}

func (m *ScheduledSelectionParams) GetMinExternalBeaconBlocks() uint64 {
	if m != nil {
		return m.MinExternalBeaconBlocks
	}
	return 0
}

func (m *ScheduledSelectionParams) GetMinDistinctExternalProposers() uint64 {
	if m != nil {
		return m.MinDistinctExternalProposers
	}
	return 0
}

// SettlementParamsVersion is one immutable entry of the settlement-validity
// parameter history, bound to a target at its N-2 boundary before any Selection
// outcome is knowable.
//
// A later update can never reduce or reinterpret the payout capacity or deadline
// of an already-bound target.
type SettlementParamsVersion struct {
	Version                uint64 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	EffectiveEpoch         uint64 `protobuf:"varint,2,opt,name=effective_epoch,json=effectiveEpoch,proto3" json:"effective_epoch,omitempty"`
	SettlementWindowEpochs uint64 `protobuf:"varint,3,opt,name=settlement_window_epochs,json=settlementWindowEpochs,proto3" json:"settlement_window_epochs,omitempty"`
	MaxRecipientsPerChunk  uint64 `protobuf:"varint,4,opt,name=max_recipients_per_chunk,json=maxRecipientsPerChunk,proto3" json:"max_recipients_per_chunk,omitempty"`
	MaxChunksPerSettlement uint64 `protobuf:"varint,5,opt,name=max_chunks_per_settlement,json=maxChunksPerSettlement,proto3" json:"max_chunks_per_settlement,omitempty"`
	// min_recipient_payout_amount is a canonical base-denom integer as text. It is
	// arbitrary precision and is never narrowed to a fixed-width type: a legitimate
	// floor may exceed the range of a uint64.
	MinRecipientPayoutAmount string `protobuf:"bytes,6,opt,name=min_recipient_payout_amount,json=minRecipientPayoutAmount,proto3" json:"min_recipient_payout_amount,omitempty"`
}

func (m *SettlementParamsVersion) Reset()         { *m = SettlementParamsVersion{} }
func (m *SettlementParamsVersion) String() string { return proto.CompactTextString(m) }
func (*SettlementParamsVersion) ProtoMessage()    {}
func (*SettlementParamsVersion) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e6f922626df5586, []int{4}
}
func (m *SettlementParamsVersion) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SettlementParamsVersion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SettlementParamsVersion.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SettlementParamsVersion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SettlementParamsVersion.Merge(m, src)
}
func (m *SettlementParamsVersion) XXX_Size() int {
	return m.Size()
}
func (m *SettlementParamsVersion) XXX_DiscardUnknown() {
	xxx_messageInfo_SettlementParamsVersion.DiscardUnknown(m)
}

var xxx_messageInfo_SettlementParamsVersion proto.InternalMessageInfo

func (m *SettlementParamsVersion) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *SettlementParamsVersion) GetEffectiveEpoch() uint64 {
	if m != nil {
		return m.EffectiveEpoch
	}
	return 0
}

func (m *SettlementParamsVersion) GetSettlementWindowEpochs() uint64 {
	if m != nil {
		return m.SettlementWindowEpochs
	}
	return 0
}

func (m *SettlementParamsVersion) GetMaxRecipientsPerChunk() uint64 {
	if m != nil {
		return m.MaxRecipientsPerChunk
	}
	return 0
}

func (m *SettlementParamsVersion) GetMaxChunksPerSettlement() uint64 {
	if m != nil {
		return m.MaxChunksPerSettlement
	}
	return 0
}

func (m *SettlementParamsVersion) GetMinRecipientPayoutAmount() string {
	if m != nil {
		return m.MinRecipientPayoutAmount
	}
	return ""
}

// ScheduledSettlementParams is the single pending settlement-parameter change.
// POC 1 defines the shape and provides no writer.
type ScheduledSettlementParams struct {
	EffectiveEpoch           uint64 `protobuf:"varint,1,opt,name=effective_epoch,json=effectiveEpoch,proto3" json:"effective_epoch,omitempty"`
	SettlementWindowEpochs   uint64 `protobuf:"varint,2,opt,name=settlement_window_epochs,json=settlementWindowEpochs,proto3" json:"settlement_window_epochs,omitempty"`
	MaxRecipientsPerChunk    uint64 `protobuf:"varint,3,opt,name=max_recipients_per_chunk,json=maxRecipientsPerChunk,proto3" json:"max_recipients_per_chunk,omitempty"`
	MaxChunksPerSettlement   uint64 `protobuf:"varint,4,opt,name=max_chunks_per_settlement,json=maxChunksPerSettlement,proto3" json:"max_chunks_per_settlement,omitempty"`
	MinRecipientPayoutAmount string `protobuf:"bytes,5,opt,name=min_recipient_payout_amount,json=minRecipientPayoutAmount,proto3" json:"min_recipient_payout_amount,omitempty"`
}

func (m *ScheduledSettlementParams) Reset()         { *m = ScheduledSettlementParams{} }
func (m *ScheduledSettlementParams) String() string { return proto.CompactTextString(m) }
func (*ScheduledSettlementParams) ProtoMessage()    {}
func (*ScheduledSettlementParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e6f922626df5586, []int{5}
}
func (m *ScheduledSettlementParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ScheduledSettlementParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ScheduledSettlementParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ScheduledSettlementParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScheduledSettlementParams.Merge(m, src)
}
func (m *ScheduledSettlementParams) XXX_Size() int {
	return m.Size()
}
func (m *ScheduledSettlementParams) XXX_DiscardUnknown() {
	xxx_messageInfo_ScheduledSettlementParams.DiscardUnknown(m)
}

var xxx_messageInfo_ScheduledSettlementParams proto.InternalMessageInfo

func (m *ScheduledSettlementParams) GetEffectiveEpoch() uint64 {
	if m != nil {
		return m.EffectiveEpoch
	}
	return 0
}

func (m *ScheduledSettlementParams) GetSettlementWindowEpochs() uint64 {
	if m != nil {
		return m.SettlementWindowEpochs
	}
	return 0
}

func (m *ScheduledSettlementParams) GetMaxRecipientsPerChunk() uint64 {
	if m != nil {
		return m.MaxRecipientsPerChunk
	}
	return 0
}

func (m *ScheduledSettlementParams) GetMaxChunksPerSettlement() uint64 {
	if m != nil {
		return m.MaxChunksPerSettlement
	}
	return 0
}

func (m *ScheduledSettlementParams) GetMinRecipientPayoutAmount() string {
	if m != nil {
		return m.MinRecipientPayoutAmount
	}
	return ""
}

// SettlementEpochAnchor records, once per epoch, the canonical settlement clock
// that epoch's settlements were created at.
//
// Exactly one exists for an epoch that contains at least one settlement, created
// atomically with that epoch's complete set. An epoch with no settlements has no
// anchor. The creation height is derived as the epoch's end height and is
// deliberately not stored here.
type SettlementEpochAnchor struct {
	Epoch                  uint64 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	CreatedSettlementClock uint64 `protobuf:"varint,2,opt,name=created_settlement_clock,json=createdSettlementClock,proto3" json:"created_settlement_clock,omitempty"`
}

func (m *SettlementEpochAnchor) Reset()         { *m = SettlementEpochAnchor{} }
func (m *SettlementEpochAnchor) String() string { return proto.CompactTextString(m) }
func (*SettlementEpochAnchor) ProtoMessage()    {}
func (*SettlementEpochAnchor) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e6f922626df5586, []int{6}
}
func (m *SettlementEpochAnchor) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SettlementEpochAnchor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SettlementEpochAnchor.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SettlementEpochAnchor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SettlementEpochAnchor.Merge(m, src)
}
func (m *SettlementEpochAnchor) XXX_Size() int {
	return m.Size()
}
func (m *SettlementEpochAnchor) XXX_DiscardUnknown() {
	xxx_messageInfo_SettlementEpochAnchor.DiscardUnknown(m)
}

var xxx_messageInfo_SettlementEpochAnchor proto.InternalMessageInfo

func (m *SettlementEpochAnchor) GetEpoch() uint64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *SettlementEpochAnchor) GetCreatedSettlementClock() uint64 {
	if m != nil {
		return m.CreatedSettlementClock
	}
	return 0
}

// Settlement is the canonical per-Slot settlement workflow record, keyed
// (slot_id, epoch), with stored lifecycle OPEN -> FINALIZED.
//
// # What this record deliberately does NOT contain
//
// released_amount is absent. Its canonical authority is the corresponding
// x/rewards SlotEntitlement: a participant chunk increases the entitlement-side
// value, and finalization derives the remainder from it. A copy here would be a
// second monetary authority free to diverge from the one the release boundary
// actually enforces.
//
// participant_distribution_ceiling, created_height, created_settlement_clock and
// deadline_clock are absent for the same reason in a weaker form: each is derived
// from the epoch anchor plus the target-bound settlement parameters, and a stored
// copy would be a forgeable duplicate of something canonical.
type Settlement struct {
	SlotId                  uint64                       `protobuf:"varint,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	Epoch                   uint64                       `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	DistributionModeVersion uint64                       `protobuf:"varint,3,opt,name=distribution_mode_version,json=distributionModeVersion,proto3" json:"distribution_mode_version,omitempty"`
	SettlementMode          SettlementMode               `protobuf:"varint,4,opt,name=settlement_mode,json=settlementMode,proto3,enum=twilight.mining.v1.SettlementMode" json:"settlement_mode,omitempty"`
	SettlementParamsVersion uint64                       `protobuf:"varint,5,opt,name=settlement_params_version,json=settlementParamsVersion,proto3" json:"settlement_params_version,omitempty"`
	NextChunkIndex          uint64                       `protobuf:"varint,6,opt,name=next_chunk_index,json=nextChunkIndex,proto3" json:"next_chunk_index,omitempty"`
	Finalized               bool                         `protobuf:"varint,7,opt,name=finalized,proto3" json:"finalized,omitempty"`
	FinalizedHeight         uint64                       `protobuf:"varint,8,opt,name=finalized_height,json=finalizedHeight,proto3" json:"finalized_height,omitempty"`
	FinalizationReason      SettlementFinalizationReason `protobuf:"varint,9,opt,name=finalization_reason,json=finalizationReason,proto3,enum=twilight.mining.v1.SettlementFinalizationReason" json:"finalization_reason,omitempty"`
}

func (m *Settlement) Reset()         { *m = Settlement{} }
func (m *Settlement) String() string { return proto.CompactTextString(m) }
func (*Settlement) ProtoMessage()    {}
func (*Settlement) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e6f922626df5586, []int{7}
}
func (m *Settlement) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Settlement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Settlement.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Settlement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Settlement.Merge(m, src)
}
func (m *Settlement) XXX_Size() int {
	return m.Size()
}
func (m *Settlement) XXX_DiscardUnknown() {
	xxx_messageInfo_Settlement.DiscardUnknown(m)
}

var xxx_messageInfo_Settlement proto.InternalMessageInfo

func (m *Settlement) GetSlotId() uint64 {
	if m != nil {
		return m.SlotId
	}
	return 0
}

func (m *Settlement) GetEpoch() uint64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *Settlement) GetDistributionModeVersion() uint64 {
	if m != nil {
		return m.DistributionModeVersion
	}
	return 0
}

func (m *Settlement) GetSettlementMode() SettlementMode {
	if m != nil {
		return m.SettlementMode
	}
	return SettlementMode_SETTLEMENT_MODE_UNSPECIFIED
}

func (m *Settlement) GetSettlementParamsVersion() uint64 {
	if m != nil {
		return m.SettlementParamsVersion
	}
	return 0
}

func (m *Settlement) GetNextChunkIndex() uint64 {
	if m != nil {
		return m.NextChunkIndex
	}
	return 0
}

func (m *Settlement) GetFinalized() bool {
	if m != nil {
		return m.Finalized
	}
	return false
}

func (m *Settlement) GetFinalizedHeight() uint64 {
	if m != nil {
		return m.FinalizedHeight
	}
	return 0
}

func (m *Settlement) GetFinalizationReason() SettlementFinalizationReason {
	if m != nil {
		return m.FinalizationReason
	}
	return SettlementFinalizationReason_SETTLEMENT_FINALIZATION_REASON_UNSPECIFIED
}

func init() {
	proto.RegisterEnum("twilight.mining.v1.MiningDistributionMode", MiningDistributionMode_name, MiningDistributionMode_value)
	proto.RegisterEnum("twilight.mining.v1.SettlementMode", SettlementMode_name, SettlementMode_value)
	proto.RegisterEnum("twilight.mining.v1.SettlementFinalizationReason", SettlementFinalizationReason_name, SettlementFinalizationReason_value)
	proto.RegisterType((*MiningDistributionModeVersion)(nil), "twilight.mining.v1.MiningDistributionModeVersion")
	proto.RegisterType((*ScheduledMiningDistributionMode)(nil), "twilight.mining.v1.ScheduledMiningDistributionMode")
	proto.RegisterType((*SelectionParamsVersion)(nil), "twilight.mining.v1.SelectionParamsVersion")
	proto.RegisterType((*ScheduledSelectionParams)(nil), "twilight.mining.v1.ScheduledSelectionParams")
	proto.RegisterType((*SettlementParamsVersion)(nil), "twilight.mining.v1.SettlementParamsVersion")
	proto.RegisterType((*ScheduledSettlementParams)(nil), "twilight.mining.v1.ScheduledSettlementParams")
	proto.RegisterType((*SettlementEpochAnchor)(nil), "twilight.mining.v1.SettlementEpochAnchor")
	proto.RegisterType((*Settlement)(nil), "twilight.mining.v1.Settlement")
}

func init() { proto.RegisterFile("twilight/mining/v1/mining.proto", fileDescriptor_1e6f922626df5586) }

var fileDescriptor_1e6f922626df5586 = []byte{
	// 1201 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0xcf, 0x73, 0xdb, 0xc4,
	0x17, 0x8f, 0x1c, 0x27, 0x69, 0xf7, 0xe0, 0x7a, 0xb6, 0x6d, 0xa2, 0xb4, 0xa9, 0xd3, 0xaf, 0xbf,
	0x30, 0x4d, 0xc3, 0x60, 0xf7, 0x07, 0x33, 0x14, 0x0a, 0x14, 0xc5, 0x56, 0xa8, 0x06, 0xdb, 0xd2,
	0x48, 0x0a, 0x4c, 0x7b, 0xd9, 0x91, 0xa5, 0x75, 0xbc, 0xd4, 0xda, 0xd5, 0x48, 0x6b, 0xd7, 0xe5,
	0xc8, 0x81, 0x03, 0x27, 0xce, 0x5c, 0x38, 0x73, 0xe4, 0xbf, 0x80, 0x5b, 0x4f, 0x0c, 0x47, 0x26,
	0xfd, 0x47, 0x18, 0xad, 0x7e, 0xd8, 0x71, 0xed, 0x26, 0x24, 0xb9, 0x79, 0xdf, 0x7b, 0x9f, 0xcf,
	0x7b, 0xfb, 0x79, 0x6f, 0x77, 0x2d, 0xb0, 0xcd, 0x5f, 0x92, 0x01, 0x39, 0xec, 0xf3, 0xba, 0x4f,
	0x28, 0xa1, 0x87, 0xf5, 0xd1, 0xfd, 0xf4, 0x57, 0x2d, 0x08, 0x19, 0x67, 0x10, 0x66, 0x01, 0xb5,
	0xd4, 0x3c, 0xba, 0x5f, 0x3d, 0x92, 0xc0, 0xad, 0xb6, 0x58, 0x35, 0x49, 0xc4, 0x43, 0xd2, 0x1d,
	0x72, 0xc2, 0x68, 0x9b, 0x79, 0xf8, 0x1b, 0x1c, 0x46, 0x84, 0x51, 0x28, 0x83, 0xb5, 0x51, 0xf2,
	0x53, 0x96, 0x6e, 0x4b, 0x3b, 0x45, 0x33, 0x5b, 0xc2, 0x2f, 0x40, 0xd1, 0x67, 0x1e, 0x96, 0x0b,
	0xb7, 0xa5, 0x9d, 0xd2, 0x83, 0xdd, 0xda, 0xdb, 0xf4, 0xb5, 0xf9, 0xd4, 0xa6, 0xc0, 0xc1, 0x1d,
	0x50, 0x1e, 0x39, 0x03, 0xe2, 0xa1, 0x5e, 0xc8, 0x7c, 0x84, 0x03, 0xe6, 0xf6, 0xe5, 0x65, 0x91,
	0xa2, 0x24, 0xec, 0xfb, 0x21, 0xf3, 0xd5, 0xd8, 0x0a, 0x3f, 0x07, 0x37, 0x93, 0xc8, 0x21, 0xe5,
	0x64, 0x90, 0x84, 0x22, 0x3c, 0x76, 0x07, 0xc3, 0x88, 0x8c, 0xb0, 0x5c, 0x14, 0x20, 0x59, 0x84,
	0x1c, 0xc4, 0x11, 0x02, 0xa5, 0x66, 0xfe, 0xea, 0x4f, 0x12, 0xd8, 0xb6, 0xdc, 0x3e, 0xf6, 0x86,
	0x03, 0xec, 0xcd, 0x2f, 0x09, 0xde, 0x01, 0x57, 0x70, 0xaf, 0x87, 0x5d, 0x4e, 0x46, 0x38, 0xad,
	0x25, 0xd9, 0x6e, 0x29, 0x37, 0x27, 0xb5, 0x9c, 0x73, 0xd7, 0xd5, 0x5f, 0x8a, 0x60, 0xdd, 0xc2,
	0x83, 0x98, 0x92, 0x51, 0xc3, 0x09, 0x1d, 0x3f, 0x3a, 0x59, 0xea, 0x39, 0xd5, 0x15, 0xe6, 0x56,
	0xf7, 0x10, 0xac, 0xfb, 0xce, 0x18, 0x45, 0x59, 0x02, 0x14, 0x3a, 0x1c, 0xa3, 0x6e, 0x10, 0xa5,
	0xca, 0x5e, 0xf5, 0x9d, 0x71, 0x9e, 0xdd, 0x74, 0x38, 0xde, 0x0b, 0x22, 0x68, 0x83, 0x3b, 0x13,
	0x10, 0xf6, 0x50, 0xe0, 0x84, 0x9c, 0xb8, 0x24, 0x70, 0x28, 0x8f, 0x50, 0x80, 0xc3, 0x09, 0x5d,
	0x2a, 0xf5, 0xff, 0x73, 0x16, 0xec, 0x19, 0x53, 0xc1, 0x06, 0x0e, 0x73, 0x72, 0xf8, 0x04, 0x6c,
	0xc5, 0xac, 0xae, 0x43, 0x3d, 0xe2, 0x39, 0x1c, 0xcf, 0x52, 0xad, 0x08, 0xaa, 0x4d, 0xdf, 0x19,
	0x37, 0xf2, 0x90, 0x63, 0x04, 0x8f, 0xc1, 0x8d, 0x2e, 0x76, 0x5c, 0x46, 0x51, 0xc4, 0x9d, 0x90,
	0x23, 0xd6, 0xeb, 0x45, 0x98, 0xa3, 0xee, 0x80, 0xb9, 0x2f, 0x22, 0x79, 0x55, 0xc0, 0x37, 0x92,
	0x08, 0x2b, 0x0e, 0xd0, 0x85, 0x7f, 0x4f, 0xb8, 0xe1, 0x3d, 0x70, 0x2d, 0x05, 0xbf, 0x24, 0xd4,
	0x63, 0x2f, 0x33, 0xd8, 0x9a, 0x80, 0xc1, 0xc4, 0xf7, 0xad, 0x70, 0xa5, 0x88, 0xc7, 0xe0, 0x86,
	0x4f, 0x28, 0xc2, 0x63, 0x8e, 0x43, 0xea, 0x0c, 0x50, 0x0a, 0x4f, 0x71, 0x97, 0x92, 0x74, 0x3e,
	0xa1, 0x6a, 0x1a, 0xb0, 0x27, 0xfc, 0x29, 0x58, 0x05, 0xdb, 0x31, 0xd8, 0x23, 0x11, 0x27, 0xd4,
	0xe5, 0x13, 0x96, 0x20, 0x64, 0x01, 0x8b, 0x70, 0x18, 0xc9, 0x97, 0x05, 0xc3, 0x96, 0x4f, 0x68,
	0x33, 0x8d, 0xca, 0x98, 0x8c, 0x2c, 0xa6, 0xfa, 0x43, 0x11, 0xc8, 0xf9, 0xa4, 0xce, 0x4c, 0xc9,
	0xe9, 0x47, 0x74, 0xf1, 0x10, 0x14, 0x2e, 0x64, 0x08, 0x96, 0x2f, 0x6e, 0x08, 0x8a, 0xe7, 0x1b,
	0x82, 0x95, 0xb3, 0x0d, 0xc1, 0xea, 0x19, 0x87, 0x60, 0xed, 0xdc, 0x43, 0x70, 0xe9, 0x14, 0x43,
	0xf0, 0x67, 0x01, 0x6c, 0x58, 0x98, 0xf3, 0x01, 0xf6, 0x31, 0xe5, 0x17, 0x7e, 0x45, 0x3c, 0x02,
	0x72, 0x94, 0xb3, 0x67, 0xc2, 0x08, 0x40, 0x76, 0x49, 0xac, 0x4f, 0xfc, 0x89, 0x38, 0x02, 0x18,
	0xc1, 0x8f, 0x81, 0x1c, 0x37, 0x33, 0xc4, 0x2e, 0x09, 0x08, 0xce, 0xe6, 0xc2, 0xed, 0x0f, 0xe9,
	0x8b, 0xb4, 0x91, 0xd7, 0x7d, 0x67, 0x6c, 0xe6, 0x6e, 0x03, 0x87, 0x8d, 0xd8, 0x09, 0x3f, 0x01,
	0x9b, 0x62, 0x0a, 0xe2, 0x45, 0x36, 0x01, 0x59, 0x86, 0xb4, 0x87, 0xf1, 0xc4, 0x8a, 0xe0, 0xa4,
	0xfd, 0x99, 0x37, 0xbe, 0xfa, 0x63, 0x4d, 0xf3, 0x9c, 0x28, 0x70, 0x5e, 0xb1, 0x21, 0x47, 0x8e,
	0xcf, 0x86, 0x94, 0x8b, 0x4e, 0x5e, 0x36, 0x65, 0x9f, 0xd0, 0x3c, 0xad, 0x21, 0x02, 0x14, 0xe1,
	0xaf, 0xfe, 0x5e, 0x00, 0x9b, 0x53, 0x07, 0xea, 0xb8, 0xa8, 0xa7, 0x3f, 0x51, 0xef, 0xd2, 0xac,
	0x70, 0x66, 0xcd, 0x96, 0xcf, 0xac, 0x59, 0xf1, 0x3c, 0x9a, 0xad, 0x9c, 0xa0, 0xd9, 0x21, 0xb8,
	0x3e, 0x21, 0x13, 0xdb, 0x50, 0xa8, 0xdb, 0x67, 0x21, 0xbc, 0x06, 0x56, 0xa6, 0x45, 0x4a, 0x16,
	0xb1, 0x36, 0x6e, 0x88, 0x9d, 0xf8, 0xce, 0x98, 0xd2, 0xc8, 0x8d, 0x8f, 0x44, 0xa6, 0x4d, 0xea,
	0x9f, 0xb0, 0x36, 0x62, 0x6f, 0xf5, 0xaf, 0x65, 0x00, 0xa6, 0xca, 0xde, 0x00, 0x6b, 0xd1, 0x80,
	0x71, 0x44, 0xbc, 0x34, 0xc1, 0x6a, 0xbc, 0xd4, 0xbc, 0x49, 0xde, 0xc2, 0x74, 0xde, 0x4f, 0xc1,
	0xa6, 0x37, 0xf5, 0xc4, 0xa2, 0xf8, 0x75, 0x45, 0xd9, 0xe1, 0x48, 0xa4, 0xdd, 0xf0, 0x16, 0xfc,
	0xa9, 0xf9, 0x1a, 0x5c, 0x99, 0xaa, 0x55, 0xbc, 0xe7, 0x45, 0xf1, 0x9e, 0x57, 0xe7, 0xbd, 0xe7,
	0x93, 0x1a, 0xc5, 0x3b, 0x5e, 0x8a, 0x8e, 0xad, 0xe3, 0x42, 0xa6, 0xc8, 0x02, 0x31, 0x5a, 0x79,
	0x21, 0xe9, 0x0d, 0x15, 0x2d, 0x38, 0xcf, 0x3b, 0xa0, 0x4c, 0xf1, 0x98, 0x27, 0x6d, 0x46, 0x84,
	0x7a, 0x78, 0x9c, 0xde, 0x4e, 0xa5, 0xd8, 0x2e, 0xba, 0xab, 0xc5, 0x56, 0xb8, 0x05, 0x2e, 0xf7,
	0x08, 0x75, 0x06, 0xe4, 0x7b, 0xec, 0x89, 0x8b, 0xe8, 0x92, 0x39, 0x31, 0xc0, 0xbb, 0xa0, 0x9c,
	0x2f, 0x50, 0x1f, 0xc7, 0x1b, 0x48, 0xef, 0x9a, 0x2b, 0xb9, 0xfd, 0xa9, 0x30, 0x43, 0x07, 0x5c,
	0x4d, 0x4d, 0x4e, 0xf2, 0x38, 0x60, 0x27, 0x62, 0x54, 0x3c, 0x4f, 0xa5, 0x07, 0xf7, 0xde, 0xbd,
	0xff, 0xfd, 0x29, 0xa0, 0x29, 0x70, 0x26, 0xec, 0xbd, 0x65, 0xdb, 0xfd, 0x4d, 0x02, 0xeb, 0x0b,
	0xfe, 0x67, 0xed, 0x80, 0xf7, 0xda, 0x5a, 0x47, 0xeb, 0x7c, 0x85, 0x9a, 0x9a, 0x65, 0x9b, 0xda,
	0xde, 0x81, 0xad, 0xe9, 0x1d, 0xd4, 0xd6, 0x9b, 0x2a, 0x3a, 0xe8, 0x58, 0x86, 0xda, 0xd0, 0xf6,
	0x35, 0xb5, 0x59, 0x5e, 0x82, 0x1f, 0x81, 0x7b, 0x0b, 0x23, 0x6d, 0xf3, 0xc0, 0xb2, 0xd5, 0x26,
	0x52, 0xac, 0x63, 0xce, 0xb2, 0x04, 0xeb, 0xe0, 0x83, 0x85, 0x28, 0xc3, 0xd4, 0x6d, 0xbd, 0xa1,
	0xb7, 0x90, 0xa5, 0xb6, 0xd4, 0x86, 0x00, 0x14, 0x76, 0x7f, 0x95, 0x40, 0xe9, 0x78, 0x83, 0xe1,
	0x36, 0xb8, 0x69, 0xa9, 0xb6, 0xdd, 0x52, 0xdb, 0x6a, 0xc7, 0x9e, 0x57, 0x5a, 0x05, 0xdc, 0x98,
	0x0d, 0x98, 0x54, 0x54, 0x96, 0xe0, 0x5d, 0xf0, 0xfe, 0xac, 0x3f, 0x49, 0xa9, 0x36, 0x91, 0xa1,
	0x98, 0xb6, 0xd6, 0xd0, 0x0c, 0xa5, 0x63, 0x5b, 0xe5, 0x02, 0xfc, 0x1f, 0xb8, 0x35, 0x1b, 0xaa,
	0x1b, 0xaa, 0xa9, 0xd8, 0xba, 0x89, 0xf4, 0x4e, 0xeb, 0x59, 0x79, 0x79, 0xf7, 0xc7, 0x02, 0xd8,
	0x7a, 0x57, 0x0b, 0x60, 0x0d, 0xec, 0x4e, 0x71, 0xec, 0x6b, 0x1d, 0xa5, 0xa5, 0x3d, 0x57, 0xc4,
	0xbe, 0x4d, 0x55, 0xb1, 0xf4, 0xce, 0x4c, 0xf9, 0x0f, 0x41, 0xfd, 0x84, 0x78, 0xe5, 0xc0, 0x7e,
	0xaa, 0x9b, 0xda, 0x73, 0xb5, 0x89, 0x54, 0xc5, 0x6c, 0x3d, 0x2b, 0x4b, 0xf0, 0x4b, 0xf0, 0xd9,
	0x09, 0x20, 0x43, 0x35, 0xdb, 0x9a, 0x65, 0x69, 0x7a, 0xa7, 0xa5, 0x5a, 0x16, 0x52, 0xf6, 0x6d,
	0xd5, 0x44, 0x4d, 0x55, 0x69, 0xb6, 0xb4, 0x8e, 0x5a, 0x2e, 0xc0, 0x27, 0xe0, 0xf1, 0x7f, 0x63,
	0x98, 0x11, 0x62, 0xcf, 0xfc, 0xe3, 0xa8, 0x22, 0xbd, 0x3e, 0xaa, 0x48, 0xff, 0x1c, 0x55, 0xa4,
	0x9f, 0xdf, 0x54, 0x96, 0x5e, 0xbf, 0xa9, 0x2c, 0xfd, 0xfd, 0xa6, 0xb2, 0xf4, 0xfc, 0xd1, 0x21,
	0xe1, 0xfd, 0x61, 0xb7, 0xe6, 0x32, 0xbf, 0x9e, 0x0d, 0xf0, 0x87, 0x41, 0xc8, 0xbe, 0xc3, 0x2e,
	0x9f, 0x18, 0x5c, 0x16, 0xe2, 0xfa, 0x38, 0xfb, 0x3c, 0xe2, 0xaf, 0x02, 0x1c, 0x75, 0x57, 0xc5,
	0xb7, 0xd1, 0xc3, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xb7, 0x04, 0xaa, 0x83, 0x3e, 0x0d, 0x00,
	0x00,
}

func (m *MiningDistributionModeVersion) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MiningDistributionModeVersion) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MiningDistributionModeVersion) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ValidUntilEpochExclusive != 0 {
		i = encodeVarintMining(dAtA, i, uint64(m.ValidUntilEpochExclusive))
		i--
		dAtA[i] = 0x20
	}
	if m.ValidFromEpoch != 0 {
		i = encodeVarintMining(dAtA, i, uint64(m.ValidFromEpoch))
		i--
		dAtA[i] = 0x18
	}
	if m.Mode != 0 {
		i = encodeVarintMining(dAtA, i, uint64(m.Mode))
		i--
		dAtA[i] = 0x10
	}
	if m.Version != 0 {
		i = encodeVarintMining(dAtA, i, uint64(m.Version))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ScheduledMiningDistributionMode) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ScheduledMiningDistributionMode) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ScheduledMiningDistributionMode) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Mode != 0 {
		i = encodeVarintMining(dAtA, i, uint64(m.Mode))
		i--
		dAtA[i] = 0x10
	}
	if m.EffectiveEpoch != 0 {
		i = encodeVarintMining(dAtA, i, uint64(m.EffectiveEpoch))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *SelectionParamsVersion) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SelectionParamsVersion) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SelectionParamsVersion) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MinDistinctExternalProposers != 0 {
		i = encodeVarintMining(dAtA, i, uint64(m.MinDistinctExternalProposers))
		i--
		dAtA[i] = 0x48
	}
	if m.MinExternalBeaconBlocks != 0 {
		i = encodeVarintMining(dAtA, i, uint64(m.MinExternalBeaconBlocks))
		i--
		dAtA[i] = 0x40
	}
	if m.BeaconWindowBlocks != 0 {
		i = encodeVarintMining(dAtA, i, uint64(m.BeaconWindowBlocks))
		i--
		dAtA[i] = 0x38
	}
	if m.BeaconStartOffsetBlocks != 0 {
		i = encodeVarintMining(dAtA, i, uint64(m.BeaconStartOffsetBlocks))
		i--
		dAtA[i] = 0x30
	}
	if m.MaxCandidatesPerSelection != 0 {
		i = encodeVarintMining(dAtA, i, uint64(m.MaxCandidatesPerSelection))
		i--
		dAtA[i] = 0x28
	}
	if m.MaxSelectedParticipantsPerSelection != 0 {
		i = encodeVarintMining(dAtA, i, uint64(m.MaxSelectedParticipantsPerSelection))
		i--
		dAtA[i] = 0x20
	}
	if m.MaxSelectionRateBps != 0 {
		i = encodeVarintMining(dAtA, i, uint64(m.MaxSelectionRateBps))
		i--
		dAtA[i] = 0x18
	}
	if m.EffectiveEpoch != 0 {
		i = encodeVarintMining(dAtA, i, uint64(m.EffectiveEpoch))
		i--
		dAtA[i] = 0x10
	}
	if m.Version != 0 {
		i = encodeVarintMining(dAtA, i, uint64(m.Version))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ScheduledSelectionParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ScheduledSelectionParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ScheduledSelectionParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MinDistinctExternalProposers != 0 {
		i = encodeVarintMining(dAtA, i, uint64(m.MinDistinctExternalProposers))
		i--
		dAtA[i] = 0x40
	}
	if m.MinExternalBeaconBlocks != 0 {
		i = encodeVarintMining(dAtA, i, uint64(m.MinExternalBeaconBlocks))
		i--
		dAtA[i] = 0x38
	}
	if m.BeaconWindowBlocks != 0 {
		i = encodeVarintMining(dAtA, i, uint64(m.BeaconWindowBlocks))
		i--
		dAtA[i] = 0x30
	}
	if m.BeaconStartOffsetBlocks != 0 {
		i = encodeVarintMining(dAtA, i, uint64(m.BeaconStartOffsetBlocks))
		i--
		dAtA[i] = 0x28
	}
	if m.MaxCandidatesPerSelection != 0 {
		i = encodeVarintMining(dAtA, i, uint64(m.MaxCandidatesPerSelection))
		i--
		dAtA[i] = 0x20
	}
	if m.MaxSelectedParticipantsPerSelection != 0 {
		i = encodeVarintMining(dAtA, i, uint64(m.MaxSelectedParticipantsPerSelection))
		i--
		dAtA[i] = 0x18
	}
	if m.MaxSelectionRateBps != 0 {
		i = encodeVarintMining(dAtA, i, uint64(m.MaxSelectionRateBps))
		i--
		dAtA[i] = 0x10
	}
	if m.EffectiveEpoch != 0 {
		i = encodeVarintMining(dAtA, i, uint64(m.EffectiveEpoch))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *SettlementParamsVersion) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SettlementParamsVersion) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SettlementParamsVersion) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MinRecipientPayoutAmount) > 0 {
		i -= len(m.MinRecipientPayoutAmount)
		copy(dAtA[i:], m.MinRecipientPayoutAmount)
		i = encodeVarintMining(dAtA, i, uint64(len(m.MinRecipientPayoutAmount)))
		i--
		dAtA[i] = 0x32
	}
	if m.MaxChunksPerSettlement != 0 {
		i = encodeVarintMining(dAtA, i, uint64(m.MaxChunksPerSettlement))
		i--
		dAtA[i] = 0x28
	}
	if m.MaxRecipientsPerChunk != 0 {
		i = encodeVarintMining(dAtA, i, uint64(m.MaxRecipientsPerChunk))
		i--
		dAtA[i] = 0x20
	}
	if m.SettlementWindowEpochs != 0 {
		i = encodeVarintMining(dAtA, i, uint64(m.SettlementWindowEpochs))
		i--
		dAtA[i] = 0x18
	}
	if m.EffectiveEpoch != 0 {
		i = encodeVarintMining(dAtA, i, uint64(m.EffectiveEpoch))
		i--
		dAtA[i] = 0x10
	}
	if m.Version != 0 {
		i = encodeVarintMining(dAtA, i, uint64(m.Version))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ScheduledSettlementParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ScheduledSettlementParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ScheduledSettlementParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MinRecipientPayoutAmount) > 0 {
		i -= len(m.MinRecipientPayoutAmount)
		copy(dAtA[i:], m.MinRecipientPayoutAmount)
		i = encodeVarintMining(dAtA, i, uint64(len(m.MinRecipientPayoutAmount)))
		i--
		dAtA[i] = 0x2a
	}
	if m.MaxChunksPerSettlement != 0 {
		i = encodeVarintMining(dAtA, i, uint64(m.MaxChunksPerSettlement))
		i--
		dAtA[i] = 0x20
	}
	if m.MaxRecipientsPerChunk != 0 {
		i = encodeVarintMining(dAtA, i, uint64(m.MaxRecipientsPerChunk))
		i--
		dAtA[i] = 0x18
	}
	if m.SettlementWindowEpochs != 0 {
		i = encodeVarintMining(dAtA, i, uint64(m.SettlementWindowEpochs))
		i--
		dAtA[i] = 0x10
	}
	if m.EffectiveEpoch != 0 {
		i = encodeVarintMining(dAtA, i, uint64(m.EffectiveEpoch))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *SettlementEpochAnchor) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SettlementEpochAnchor) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SettlementEpochAnchor) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CreatedSettlementClock != 0 {
		i = encodeVarintMining(dAtA, i, uint64(m.CreatedSettlementClock))
		i--
		dAtA[i] = 0x10
	}
	if m.Epoch != 0 {
		i = encodeVarintMining(dAtA, i, uint64(m.Epoch))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Settlement) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Settlement) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Settlement) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.FinalizationReason != 0 {
		i = encodeVarintMining(dAtA, i, uint64(m.FinalizationReason))
		i--
		dAtA[i] = 0x48
	}
	if m.FinalizedHeight != 0 {
		i = encodeVarintMining(dAtA, i, uint64(m.FinalizedHeight))
		i--
		dAtA[i] = 0x40
	}
	if m.Finalized {
		i--
		if m.Finalized {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x38
	}
	if m.NextChunkIndex != 0 {
		i = encodeVarintMining(dAtA, i, uint64(m.NextChunkIndex))
		i--
		dAtA[i] = 0x30
	}
	if m.SettlementParamsVersion != 0 {
		i = encodeVarintMining(dAtA, i, uint64(m.SettlementParamsVersion))
		i--
		dAtA[i] = 0x28
	}
	if m.SettlementMode != 0 {
		i = encodeVarintMining(dAtA, i, uint64(m.SettlementMode))
		i--
		dAtA[i] = 0x20
	}
	if m.DistributionModeVersion != 0 {
		i = encodeVarintMining(dAtA, i, uint64(m.DistributionModeVersion))
		i--
		dAtA[i] = 0x18
	}
	if m.Epoch != 0 {
		i = encodeVarintMining(dAtA, i, uint64(m.Epoch))
		i--
		dAtA[i] = 0x10
	}
	if m.SlotId != 0 {
		i = encodeVarintMining(dAtA, i, uint64(m.SlotId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintMining(dAtA []byte, offset int, v uint64) int {
	offset -= sovMining(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MiningDistributionModeVersion) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Version != 0 {
		n += 1 + sovMining(uint64(m.Version))
	}
	if m.Mode != 0 {
		n += 1 + sovMining(uint64(m.Mode))
	}
	if m.ValidFromEpoch != 0 {
		n += 1 + sovMining(uint64(m.ValidFromEpoch))
	}
	if m.ValidUntilEpochExclusive != 0 {
		n += 1 + sovMining(uint64(m.ValidUntilEpochExclusive))
	}
	return n
}

func (m *ScheduledMiningDistributionMode) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.EffectiveEpoch != 0 {
		n += 1 + sovMining(uint64(m.EffectiveEpoch))
	}
	if m.Mode != 0 {
		n += 1 + sovMining(uint64(m.Mode))
	}
	return n
}

func (m *SelectionParamsVersion) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Version != 0 {
		n += 1 + sovMining(uint64(m.Version))
	}
	if m.EffectiveEpoch != 0 {
		n += 1 + sovMining(uint64(m.EffectiveEpoch))
	}
	if m.MaxSelectionRateBps != 0 {
		n += 1 + sovMining(uint64(m.MaxSelectionRateBps))
	}
	if m.MaxSelectedParticipantsPerSelection != 0 {
		n += 1 + sovMining(uint64(m.MaxSelectedParticipantsPerSelection))
	}
	if m.MaxCandidatesPerSelection != 0 {
		n += 1 + sovMining(uint64(m.MaxCandidatesPerSelection))
	}
	if m.BeaconStartOffsetBlocks != 0 {
		n += 1 + sovMining(uint64(m.BeaconStartOffsetBlocks))
	}
	if m.BeaconWindowBlocks != 0 {
		n += 1 + sovMining(uint64(m.BeaconWindowBlocks))
	}
	if m.MinExternalBeaconBlocks != 0 {
		n += 1 + sovMining(uint64(m.MinExternalBeaconBlocks))
	}
	if m.MinDistinctExternalProposers != 0 {
		n += 1 + sovMining(uint64(m.MinDistinctExternalProposers))
	}
	return n
}

func (m *ScheduledSelectionParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.EffectiveEpoch != 0 {
		n += 1 + sovMining(uint64(m.EffectiveEpoch))
	}
	if m.MaxSelectionRateBps != 0 {
		n += 1 + sovMining(uint64(m.MaxSelectionRateBps))
	}
	if m.MaxSelectedParticipantsPerSelection != 0 {
		n += 1 + sovMining(uint64(m.MaxSelectedParticipantsPerSelection))
	}
	if m.MaxCandidatesPerSelection != 0 {
		n += 1 + sovMining(uint64(m.MaxCandidatesPerSelection))
	}
	if m.BeaconStartOffsetBlocks != 0 {
		n += 1 + sovMining(uint64(m.BeaconStartOffsetBlocks))
	}
	if m.BeaconWindowBlocks != 0 {
		n += 1 + sovMining(uint64(m.BeaconWindowBlocks))
	}
	if m.MinExternalBeaconBlocks != 0 {
		n += 1 + sovMining(uint64(m.MinExternalBeaconBlocks))
	}
	if m.MinDistinctExternalProposers != 0 {
		n += 1 + sovMining(uint64(m.MinDistinctExternalProposers))
	}
	return n
}

func (m *SettlementParamsVersion) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Version != 0 {
		n += 1 + sovMining(uint64(m.Version))
	}
	if m.EffectiveEpoch != 0 {
		n += 1 + sovMining(uint64(m.EffectiveEpoch))
	}
	if m.SettlementWindowEpochs != 0 {
		n += 1 + sovMining(uint64(m.SettlementWindowEpochs))
	}
	if m.MaxRecipientsPerChunk != 0 {
		n += 1 + sovMining(uint64(m.MaxRecipientsPerChunk))
	}
	if m.MaxChunksPerSettlement != 0 {
		n += 1 + sovMining(uint64(m.MaxChunksPerSettlement))
	}
	l = len(m.MinRecipientPayoutAmount)
	if l > 0 {
		n += 1 + l + sovMining(uint64(l))
	}
	return n
}

func (m *ScheduledSettlementParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.EffectiveEpoch != 0 {
		n += 1 + sovMining(uint64(m.EffectiveEpoch))
	}
	if m.SettlementWindowEpochs != 0 {
		n += 1 + sovMining(uint64(m.SettlementWindowEpochs))
	}
	if m.MaxRecipientsPerChunk != 0 {
		n += 1 + sovMining(uint64(m.MaxRecipientsPerChunk))
	}
	if m.MaxChunksPerSettlement != 0 {
		n += 1 + sovMining(uint64(m.MaxChunksPerSettlement))
	}
	l = len(m.MinRecipientPayoutAmount)
	if l > 0 {
		n += 1 + l + sovMining(uint64(l))
	}
	return n
}

func (m *SettlementEpochAnchor) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Epoch != 0 {
		n += 1 + sovMining(uint64(m.Epoch))
	}
	if m.CreatedSettlementClock != 0 {
		n += 1 + sovMining(uint64(m.CreatedSettlementClock))
	}
	return n
}

func (m *Settlement) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SlotId != 0 {
		n += 1 + sovMining(uint64(m.SlotId))
	}
	if m.Epoch != 0 {
		n += 1 + sovMining(uint64(m.Epoch))
	}
	if m.DistributionModeVersion != 0 {
		n += 1 + sovMining(uint64(m.DistributionModeVersion))
	}
	if m.SettlementMode != 0 {
		n += 1 + sovMining(uint64(m.SettlementMode))
	}
	if m.SettlementParamsVersion != 0 {
		n += 1 + sovMining(uint64(m.SettlementParamsVersion))
	}
	if m.NextChunkIndex != 0 {
		n += 1 + sovMining(uint64(m.NextChunkIndex))
	}
	if m.Finalized {
		n += 2
	}
	if m.FinalizedHeight != 0 {
		n += 1 + sovMining(uint64(m.FinalizedHeight))
	}
	if m.FinalizationReason != 0 {
		n += 1 + sovMining(uint64(m.FinalizationReason))
	}
	return n
}

func sovMining(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMining(x uint64) (n int) {
	return sovMining(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MiningDistributionModeVersion) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMining
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MiningDistributionModeVersion: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MiningDistributionModeVersion: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			m.Version = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMining
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Version |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mode", wireType)
			}
			m.Mode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMining
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Mode |= MiningDistributionMode(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidFromEpoch", wireType)
			}
			m.ValidFromEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMining
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ValidFromEpoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidUntilEpochExclusive", wireType)
			}
			m.ValidUntilEpochExclusive = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMining
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ValidUntilEpochExclusive |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMining(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMining
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ScheduledMiningDistributionMode) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMining
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ScheduledMiningDistributionMode: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ScheduledMiningDistributionMode: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EffectiveEpoch", wireType)
			}
			m.EffectiveEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMining
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EffectiveEpoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mode", wireType)
			}
			m.Mode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMining
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Mode |= MiningDistributionMode(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMining(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMining
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SelectionParamsVersion) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMining
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SelectionParamsVersion: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SelectionParamsVersion: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			m.Version = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMining
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Version |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EffectiveEpoch", wireType)
			}
			m.EffectiveEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMining
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EffectiveEpoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxSelectionRateBps", wireType)
			}
			m.MaxSelectionRateBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMining
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxSelectionRateBps |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxSelectedParticipantsPerSelection", wireType)
			}
			m.MaxSelectedParticipantsPerSelection = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMining
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxSelectedParticipantsPerSelection |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxCandidatesPerSelection", wireType)
			}
			m.MaxCandidatesPerSelection = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMining
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxCandidatesPerSelection |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BeaconStartOffsetBlocks", wireType)
			}
			m.BeaconStartOffsetBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMining
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BeaconStartOffsetBlocks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BeaconWindowBlocks", wireType)
			}
			m.BeaconWindowBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMining
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BeaconWindowBlocks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinExternalBeaconBlocks", wireType)
			}
			m.MinExternalBeaconBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMining
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinExternalBeaconBlocks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinDistinctExternalProposers", wireType)
			}
			m.MinDistinctExternalProposers = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMining
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinDistinctExternalProposers |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMining(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMining
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ScheduledSelectionParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMining
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ScheduledSelectionParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ScheduledSelectionParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EffectiveEpoch", wireType)
			}
			m.EffectiveEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMining
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EffectiveEpoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxSelectionRateBps", wireType)
			}
			m.MaxSelectionRateBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMining
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxSelectionRateBps |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxSelectedParticipantsPerSelection", wireType)
			}
			m.MaxSelectedParticipantsPerSelection = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMining
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxSelectedParticipantsPerSelection |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxCandidatesPerSelection", wireType)
			}
			m.MaxCandidatesPerSelection = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMining
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxCandidatesPerSelection |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BeaconStartOffsetBlocks", wireType)
			}
			m.BeaconStartOffsetBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMining
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BeaconStartOffsetBlocks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BeaconWindowBlocks", wireType)
			}
			m.BeaconWindowBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMining
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BeaconWindowBlocks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinExternalBeaconBlocks", wireType)
			}
			m.MinExternalBeaconBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMining
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinExternalBeaconBlocks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinDistinctExternalProposers", wireType)
			}
			m.MinDistinctExternalProposers = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMining
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinDistinctExternalProposers |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMining(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMining
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SettlementParamsVersion) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMining
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SettlementParamsVersion: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SettlementParamsVersion: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			m.Version = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMining
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Version |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EffectiveEpoch", wireType)
			}
			m.EffectiveEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMining
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EffectiveEpoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SettlementWindowEpochs", wireType)
			}
			m.SettlementWindowEpochs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMining
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SettlementWindowEpochs |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxRecipientsPerChunk", wireType)
			}
			m.MaxRecipientsPerChunk = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMining
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxRecipientsPerChunk |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxChunksPerSettlement", wireType)
			}
			m.MaxChunksPerSettlement = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMining
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxChunksPerSettlement |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinRecipientPayoutAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMining
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMining
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMining
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MinRecipientPayoutAmount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMining(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMining
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ScheduledSettlementParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMining
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ScheduledSettlementParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ScheduledSettlementParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EffectiveEpoch", wireType)
			}
			m.EffectiveEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMining
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EffectiveEpoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SettlementWindowEpochs", wireType)
			}
			m.SettlementWindowEpochs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMining
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SettlementWindowEpochs |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxRecipientsPerChunk", wireType)
			}
			m.MaxRecipientsPerChunk = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMining
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxRecipientsPerChunk |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxChunksPerSettlement", wireType)
			}
			m.MaxChunksPerSettlement = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMining
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxChunksPerSettlement |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinRecipientPayoutAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMining
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMining
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMining
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MinRecipientPayoutAmount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMining(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMining
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SettlementEpochAnchor) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMining
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SettlementEpochAnchor: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SettlementEpochAnchor: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Epoch", wireType)
			}
			m.Epoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMining
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Epoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedSettlementClock", wireType)
			}
			m.CreatedSettlementClock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMining
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedSettlementClock |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMining(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMining
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Settlement) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMining
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Settlement: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Settlement: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SlotId", wireType)
			}
			m.SlotId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMining
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SlotId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Epoch", wireType)
			}
			m.Epoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMining
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Epoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DistributionModeVersion", wireType)
			}
			m.DistributionModeVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMining
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DistributionModeVersion |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SettlementMode", wireType)
			}
			m.SettlementMode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMining
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SettlementMode |= SettlementMode(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SettlementParamsVersion", wireType)
			}
			m.SettlementParamsVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMining
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SettlementParamsVersion |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextChunkIndex", wireType)
			}
			m.NextChunkIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMining
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NextChunkIndex |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Finalized", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMining
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Finalized = bool(v != 0)
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FinalizedHeight", wireType)
			}
			m.FinalizedHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMining
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FinalizedHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FinalizationReason", wireType)
			}
			m.FinalizationReason = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMining
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FinalizationReason |= SettlementFinalizationReason(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMining(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMining
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMining(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMining
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMining
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMining
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMining
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMining
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMining
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMining        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMining          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMining = fmt.Errorf("proto: unexpected end of group")
)
