// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: twilight/mining/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// SettlementChunkPayout is one participant line: a destination and the amount it
// receives.
//
// The amount is a string because monetary amounts are arbitrary precision
// throughout. There is no uint64 amount field anywhere in this protocol, and one
// must not be introduced as an optimization — a 64-bit narrowing of a base-denom
// amount is a silently truncating money bug.
type SettlementChunkPayout struct {
	Recipient string `protobuf:"bytes,1,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Amount    string `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (m *SettlementChunkPayout) Reset()         { *m = SettlementChunkPayout{} }
func (m *SettlementChunkPayout) String() string { return proto.CompactTextString(m) }
func (*SettlementChunkPayout) ProtoMessage()    {}
func (*SettlementChunkPayout) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b7ba83d45a77456, []int{0}
}
func (m *SettlementChunkPayout) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SettlementChunkPayout) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SettlementChunkPayout.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SettlementChunkPayout) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SettlementChunkPayout.Merge(m, src)
}
func (m *SettlementChunkPayout) XXX_Size() int {
	return m.Size()
}
func (m *SettlementChunkPayout) XXX_DiscardUnknown() {
	xxx_messageInfo_SettlementChunkPayout.DiscardUnknown(m)
}

var xxx_messageInfo_SettlementChunkPayout proto.InternalMessageInfo

func (m *SettlementChunkPayout) GetRecipient() string {
	if m != nil {
		return m.Recipient
	}
	return ""
}

func (m *SettlementChunkPayout) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

// MsgSubmitSettlementChunk submits the next permitted chunk of an open settlement.
//
// The signer is the Slot's settlement address as recorded in x/coreslot at the
// block the message executes in. Note what the message CANNOT express: it carries
// no payout manifest, no Merkle root, no declared total, no declared chunk count
// and no pre-commitment, because none of those are required or permitted; and it
// carries no destination for the operator remainder, which is derived from the
// entitlement's immutable payout snapshot and can never be named by a caller.
//
// chunk_index is supplied rather than inferred. A caller that has lost the
// response to an earlier submission must be able to state which chunk it believes
// it is sending, so that a replay is REJECTED rather than silently accepted as the
// next chunk.
type MsgSubmitSettlementChunk struct {
	SettlementAddress string                   `protobuf:"bytes,1,opt,name=settlement_address,json=settlementAddress,proto3" json:"settlement_address,omitempty"`
	SlotId            uint64                   `protobuf:"varint,2,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	Epoch             uint64                   `protobuf:"varint,3,opt,name=epoch,proto3" json:"epoch,omitempty"`
	ChunkIndex        uint64                   `protobuf:"varint,4,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	Payouts           []*SettlementChunkPayout `protobuf:"bytes,5,rep,name=payouts,proto3" json:"payouts,omitempty"`
}

func (m *MsgSubmitSettlementChunk) Reset()         { *m = MsgSubmitSettlementChunk{} }
func (m *MsgSubmitSettlementChunk) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitSettlementChunk) ProtoMessage()    {}
func (*MsgSubmitSettlementChunk) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b7ba83d45a77456, []int{1}
}
func (m *MsgSubmitSettlementChunk) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitSettlementChunk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitSettlementChunk.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitSettlementChunk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitSettlementChunk.Merge(m, src)
}
func (m *MsgSubmitSettlementChunk) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitSettlementChunk) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitSettlementChunk.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitSettlementChunk proto.InternalMessageInfo

func (m *MsgSubmitSettlementChunk) GetSettlementAddress() string {
	if m != nil {
		return m.SettlementAddress
	}
	return ""
}

func (m *MsgSubmitSettlementChunk) GetSlotId() uint64 {
	if m != nil {
		return m.SlotId
	}
	return 0
}

func (m *MsgSubmitSettlementChunk) GetEpoch() uint64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *MsgSubmitSettlementChunk) GetChunkIndex() uint64 {
	if m != nil {
		return m.ChunkIndex
	}
	return 0
}

func (m *MsgSubmitSettlementChunk) GetPayouts() []*SettlementChunkPayout {
	if m != nil {
		return m.Payouts
	}
	return nil
}

// MsgSubmitSettlementChunkResponse reports the settlement's chunk cursor after the
// chunk committed.
//
// This is a convenience, never an authority: the same value is readable from the
// settlement itself, and a caller that lost this response resolves its position by
// querying rather than by assuming.
type MsgSubmitSettlementChunkResponse struct {
	NextChunkIndex uint64 `protobuf:"varint,1,opt,name=next_chunk_index,json=nextChunkIndex,proto3" json:"next_chunk_index,omitempty"`
}

func (m *MsgSubmitSettlementChunkResponse) Reset()         { *m = MsgSubmitSettlementChunkResponse{} }
func (m *MsgSubmitSettlementChunkResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitSettlementChunkResponse) ProtoMessage()    {}
func (*MsgSubmitSettlementChunkResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b7ba83d45a77456, []int{2}
}
func (m *MsgSubmitSettlementChunkResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitSettlementChunkResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitSettlementChunkResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitSettlementChunkResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitSettlementChunkResponse.Merge(m, src)
}
func (m *MsgSubmitSettlementChunkResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitSettlementChunkResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitSettlementChunkResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitSettlementChunkResponse proto.InternalMessageInfo

func (m *MsgSubmitSettlementChunkResponse) GetNextChunkIndex() uint64 {
	if m != nil {
		return m.NextChunkIndex
	}
	return 0
}

// MsgFinalizeSettlement terminally closes one settlement.
//
// It carries an identity and a signer, and nothing else. Note what is absent, and
// that the absence is the design rather than an omission: no payout destination,
// no remainder amount, no released amount, no finalization reason, no deadline, no
// participant ceiling, no settlement mode and no configuration version. Every one
// of those is derived from canonical state, so a caller cannot propose a value for
// any of them — redirection and re-pricing are unrepresentable rather than
// rejected, and a rejection path could be relaxed by a later edit where a missing
// field cannot.
//
// Who may send it depends on the settlement, not on the message: an operator-only
// settlement and one past its deadline are finalizable by any valid account, while
// one still inside its participant window is finalizable only by the Slot's
// settlement address. In every case the caller decides only WHETHER the transition
// happens now, never where the money goes.
type MsgFinalizeSettlement struct {
	Signer string `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer,omitempty"`
	SlotId uint64 `protobuf:"varint,2,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	Epoch  uint64 `protobuf:"varint,3,opt,name=epoch,proto3" json:"epoch,omitempty"`
}

func (m *MsgFinalizeSettlement) Reset()         { *m = MsgFinalizeSettlement{} }
func (m *MsgFinalizeSettlement) String() string { return proto.CompactTextString(m) }
func (*MsgFinalizeSettlement) ProtoMessage()    {}
func (*MsgFinalizeSettlement) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b7ba83d45a77456, []int{3}
}
func (m *MsgFinalizeSettlement) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgFinalizeSettlement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgFinalizeSettlement.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgFinalizeSettlement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgFinalizeSettlement.Merge(m, src)
}
func (m *MsgFinalizeSettlement) XXX_Size() int {
	return m.Size()
}
func (m *MsgFinalizeSettlement) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgFinalizeSettlement.DiscardUnknown(m)
}

var xxx_messageInfo_MsgFinalizeSettlement proto.InternalMessageInfo

func (m *MsgFinalizeSettlement) GetSigner() string {
	if m != nil {
		return m.Signer
	}
	return ""
}

func (m *MsgFinalizeSettlement) GetSlotId() uint64 {
	if m != nil {
		return m.SlotId
	}
	return 0
}

func (m *MsgFinalizeSettlement) GetEpoch() uint64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

// MsgFinalizeSettlementResponse reports what the transition resolved to.
//
// Both fields are derived and neither is authority. The reason is readable from
// the settlement afterwards and the released remainder from the entitlement; they
// are returned because a caller that has just triggered a terminal money movement
// should not have to issue a second read to learn which authorization arm applied
// and how much moved.
type MsgFinalizeSettlementResponse struct {
	FinalizationReason SettlementFinalizationReason `protobuf:"varint,1,opt,name=finalization_reason,json=finalizationReason,proto3,enum=twilight.mining.v1.SettlementFinalizationReason" json:"finalization_reason,omitempty"`
	// Base-denom integer, arbitrary precision. Zero when the entitlement had already
	// been fully distributed to participants.
	ReleasedRemainder string `protobuf:"bytes,2,opt,name=released_remainder,json=releasedRemainder,proto3" json:"released_remainder,omitempty"`
}

func (m *MsgFinalizeSettlementResponse) Reset()         { *m = MsgFinalizeSettlementResponse{} }
func (m *MsgFinalizeSettlementResponse) String() string { return proto.CompactTextString(m) }
func (*MsgFinalizeSettlementResponse) ProtoMessage()    {}
func (*MsgFinalizeSettlementResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b7ba83d45a77456, []int{4}
}
func (m *MsgFinalizeSettlementResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgFinalizeSettlementResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgFinalizeSettlementResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgFinalizeSettlementResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgFinalizeSettlementResponse.Merge(m, src)
}
func (m *MsgFinalizeSettlementResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgFinalizeSettlementResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgFinalizeSettlementResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgFinalizeSettlementResponse proto.InternalMessageInfo

func (m *MsgFinalizeSettlementResponse) GetFinalizationReason() SettlementFinalizationReason {
	if m != nil {
		return m.FinalizationReason
	}
	return SettlementFinalizationReason_SETTLEMENT_FINALIZATION_REASON_UNSPECIFIED
}

func (m *MsgFinalizeSettlementResponse) GetReleasedRemainder() string {
	if m != nil {
		return m.ReleasedRemainder
	}
	return ""
}

func init() {
	proto.RegisterType((*SettlementChunkPayout)(nil), "twilight.mining.v1.SettlementChunkPayout")
	proto.RegisterType((*MsgSubmitSettlementChunk)(nil), "twilight.mining.v1.MsgSubmitSettlementChunk")
	proto.RegisterType((*MsgSubmitSettlementChunkResponse)(nil), "twilight.mining.v1.MsgSubmitSettlementChunkResponse")
	proto.RegisterType((*MsgFinalizeSettlement)(nil), "twilight.mining.v1.MsgFinalizeSettlement")
	proto.RegisterType((*MsgFinalizeSettlementResponse)(nil), "twilight.mining.v1.MsgFinalizeSettlementResponse")
}

func init() { proto.RegisterFile("twilight/mining/v1/tx.proto", fileDescriptor_6b7ba83d45a77456) }

var fileDescriptor_6b7ba83d45a77456 = []byte{
	// 560 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xcd, 0x6e, 0xd3, 0x4c,
	0x14, 0x8d, 0x9b, 0x26, 0x55, 0xa7, 0x52, 0xf5, 0x65, 0x3e, 0x42, 0xad, 0x00, 0x6e, 0x14, 0x09,
	0x29, 0x8d, 0xa8, 0x4d, 0x02, 0x48, 0xa8, 0x3b, 0x08, 0xaa, 0x54, 0x89, 0x48, 0xc8, 0xdd, 0xb1,
	0xb1, 0x1c, 0xfb, 0xd6, 0x19, 0x88, 0x67, 0xac, 0x99, 0x49, 0x49, 0x61, 0x83, 0x58, 0xb2, 0x62,
	0xc3, 0x1b, 0xf0, 0x00, 0xe1, 0x2d, 0x58, 0x76, 0xc9, 0x12, 0x25, 0x8b, 0x3c, 0x05, 0x12, 0xf2,
	0xd8, 0x4e, 0xaa, 0xc6, 0x41, 0x74, 0x63, 0xe9, 0x9e, 0x73, 0x7f, 0xe6, 0x9c, 0x7b, 0x65, 0x74,
	0x47, 0xbe, 0x23, 0x43, 0x12, 0x0c, 0xa4, 0x15, 0x12, 0x4a, 0x68, 0x60, 0x9d, 0xb7, 0x2d, 0x39,
	0x36, 0x23, 0xce, 0x24, 0xc3, 0x38, 0x23, 0xcd, 0x84, 0x34, 0xcf, 0xdb, 0xb5, 0x8a, 0x1b, 0x12,
	0xca, 0x2c, 0xf5, 0x4d, 0xd2, 0x6a, 0x7b, 0x1e, 0x13, 0x21, 0x13, 0x56, 0x28, 0x54, 0x79, 0x28,
	0x82, 0x94, 0xd8, 0xcf, 0x69, 0x9e, 0x76, 0x52, 0x09, 0x8d, 0x1e, 0xaa, 0x9e, 0x82, 0x94, 0x43,
	0x08, 0x81, 0xca, 0xee, 0x60, 0x44, 0xdf, 0xbe, 0x72, 0x2f, 0xd8, 0x48, 0xe2, 0xbb, 0x68, 0x9b,
	0x83, 0x47, 0x22, 0x02, 0x54, 0xea, 0x5a, 0x5d, 0x6b, 0x6e, 0xdb, 0x4b, 0x00, 0xdf, 0x46, 0x65,
	0x37, 0x64, 0x23, 0x2a, 0xf5, 0x0d, 0x45, 0xa5, 0x51, 0xe3, 0xdb, 0x06, 0xd2, 0x7b, 0x22, 0x38,
	0x1d, 0xf5, 0x43, 0x22, 0xaf, 0x35, 0xc6, 0x87, 0x08, 0x8b, 0x05, 0xe4, 0xb8, 0xbe, 0xcf, 0x41,
	0x88, 0xb4, 0x77, 0x65, 0xc9, 0x3c, 0x4b, 0x08, 0xbc, 0x87, 0xb6, 0xc4, 0x90, 0x49, 0x87, 0xf8,
	0x6a, 0xc8, 0xa6, 0x5d, 0x8e, 0xc3, 0x13, 0x1f, 0xdf, 0x42, 0x25, 0x88, 0x98, 0x37, 0xd0, 0x8b,
	0x0a, 0x4e, 0x02, 0xbc, 0x8f, 0x76, 0xbc, 0x78, 0x8c, 0x43, 0xa8, 0x0f, 0x63, 0x7d, 0x53, 0x71,
	0x48, 0x41, 0x27, 0x31, 0x82, 0xbb, 0x68, 0x2b, 0x52, 0xda, 0x84, 0x5e, 0xaa, 0x17, 0x9b, 0x3b,
	0x9d, 0x03, 0x73, 0xd5, 0x5d, 0x33, 0xd7, 0x0d, 0x3b, 0xab, 0x3c, 0x7a, 0xf1, 0x69, 0x3e, 0x69,
	0xe5, 0xc8, 0xf8, 0x3c, 0x9f, 0xb4, 0x9a, 0xd7, 0xcd, 0x5e, 0xe7, 0x44, 0xe3, 0x25, 0xaa, 0xaf,
	0xe3, 0x6c, 0x10, 0x11, 0xa3, 0x02, 0x70, 0x13, 0xfd, 0x47, 0x61, 0x2c, 0x9d, 0xab, 0xa2, 0x34,
	0x25, 0x6a, 0x37, 0xc6, 0xbb, 0x0b, 0x61, 0x8d, 0xaf, 0x1a, 0xaa, 0xf6, 0x44, 0x70, 0x4c, 0xa8,
	0x3b, 0x24, 0xef, 0x61, 0xd9, 0x30, 0x5e, 0x93, 0x20, 0x01, 0x05, 0x9e, 0xba, 0x9c, 0x46, 0x37,
	0xb4, 0xf6, 0xe8, 0x49, 0x2c, 0x3a, 0xad, 0x8d, 0x85, 0xde, 0xcf, 0x11, 0xba, 0x3a, 0xbd, 0xf1,
	0x5d, 0x43, 0xf7, 0x72, 0x99, 0x85, 0x46, 0x17, 0xfd, 0x7f, 0x96, 0xb0, 0xae, 0x24, 0x8c, 0x3a,
	0x1c, 0x5c, 0xc1, 0xa8, 0x7a, 0xec, 0x6e, 0xe7, 0xe1, 0xdf, 0xd7, 0x73, 0x7c, 0xa5, 0xd0, 0x56,
	0x75, 0x36, 0x3e, 0x5b, 0xc1, 0xe2, 0xa3, 0xe3, 0x30, 0x04, 0x57, 0x80, 0xef, 0x70, 0x08, 0xdd,
	0xd8, 0x48, 0x9e, 0x5e, 0x6d, 0x25, 0x63, 0xec, 0x8c, 0xe8, 0xfc, 0xd6, 0x50, 0xb1, 0x27, 0x02,
	0xfc, 0x01, 0x55, 0xf3, 0x8f, 0xf8, 0x41, 0xde, 0xab, 0xd6, 0x2d, 0xb3, 0xf6, 0xf8, 0x26, 0xd9,
	0x0b, 0x5b, 0x38, 0xc2, 0x39, 0xcb, 0x3c, 0x58, 0xd3, 0x6b, 0x35, 0xb5, 0xd6, 0xfe, 0xe7, 0xd4,
	0x6c, 0x66, 0xad, 0xf4, 0x71, 0x3e, 0x69, 0x69, 0xcf, 0xed, 0x1f, 0x53, 0x43, 0xbb, 0x9c, 0x1a,
	0xda, 0xaf, 0xa9, 0xa1, 0x7d, 0x99, 0x19, 0x85, 0xcb, 0x99, 0x51, 0xf8, 0x39, 0x33, 0x0a, 0xaf,
	0x9f, 0x06, 0x44, 0x0e, 0x46, 0x7d, 0xd3, 0x63, 0xa1, 0x95, 0x75, 0x3f, 0x8c, 0x38, 0x7b, 0x03,
	0x9e, 0x5c, 0x02, 0x1e, 0xe3, 0x60, 0x8d, 0xb3, 0xbb, 0x90, 0x17, 0x11, 0x88, 0x7e, 0x59, 0xfd,
	0x6a, 0x1e, 0xfd, 0x09, 0x00, 0x00, 0xff, 0xff, 0x87, 0x1b, 0x32, 0x71, 0xea, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// SubmitSettlementChunk releases one bounded batch of participant payouts
	// against an open settlement.
	SubmitSettlementChunk(ctx context.Context, in *MsgSubmitSettlementChunk, opts ...grpc.CallOption) (*MsgSubmitSettlementChunkResponse, error)
	// FinalizeSettlement closes an open settlement, releasing whatever remains of
	// the entitlement to its immutable operator payout snapshot.
	FinalizeSettlement(ctx context.Context, in *MsgFinalizeSettlement, opts ...grpc.CallOption) (*MsgFinalizeSettlementResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) SubmitSettlementChunk(ctx context.Context, in *MsgSubmitSettlementChunk, opts ...grpc.CallOption) (*MsgSubmitSettlementChunkResponse, error) {
	out := new(MsgSubmitSettlementChunkResponse)
	err := c.cc.Invoke(ctx, "/twilight.mining.v1.Msg/SubmitSettlementChunk", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) FinalizeSettlement(ctx context.Context, in *MsgFinalizeSettlement, opts ...grpc.CallOption) (*MsgFinalizeSettlementResponse, error) {
	out := new(MsgFinalizeSettlementResponse)
	err := c.cc.Invoke(ctx, "/twilight.mining.v1.Msg/FinalizeSettlement", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// SubmitSettlementChunk releases one bounded batch of participant payouts
	// against an open settlement.
	SubmitSettlementChunk(context.Context, *MsgSubmitSettlementChunk) (*MsgSubmitSettlementChunkResponse, error)
	// FinalizeSettlement closes an open settlement, releasing whatever remains of
	// the entitlement to its immutable operator payout snapshot.
	FinalizeSettlement(context.Context, *MsgFinalizeSettlement) (*MsgFinalizeSettlementResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) SubmitSettlementChunk(ctx context.Context, req *MsgSubmitSettlementChunk) (*MsgSubmitSettlementChunkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitSettlementChunk not implemented")
}
func (*UnimplementedMsgServer) FinalizeSettlement(ctx context.Context, req *MsgFinalizeSettlement) (*MsgFinalizeSettlementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FinalizeSettlement not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_SubmitSettlementChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubmitSettlementChunk)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubmitSettlementChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/twilight.mining.v1.Msg/SubmitSettlementChunk",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubmitSettlementChunk(ctx, req.(*MsgSubmitSettlementChunk))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_FinalizeSettlement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgFinalizeSettlement)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).FinalizeSettlement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/twilight.mining.v1.Msg/FinalizeSettlement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).FinalizeSettlement(ctx, req.(*MsgFinalizeSettlement))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "twilight.mining.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitSettlementChunk",
			Handler:    _Msg_SubmitSettlementChunk_Handler,
		},
		{
			MethodName: "FinalizeSettlement",
			Handler:    _Msg_FinalizeSettlement_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "twilight/mining/v1/tx.proto",
}

func (m *SettlementChunkPayout) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SettlementChunkPayout) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SettlementChunkPayout) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Amount) > 0 {
		i -= len(m.Amount)
		copy(dAtA[i:], m.Amount)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Amount)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Recipient) > 0 {
		i -= len(m.Recipient)
		copy(dAtA[i:], m.Recipient)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Recipient)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSubmitSettlementChunk) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitSettlementChunk) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitSettlementChunk) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Payouts) > 0 {
		for iNdEx := len(m.Payouts) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Payouts[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if m.ChunkIndex != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.ChunkIndex))
		i--
		dAtA[i] = 0x20
	}
	if m.Epoch != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Epoch))
		i--
		dAtA[i] = 0x18
	}
	if m.SlotId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.SlotId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.SettlementAddress) > 0 {
		i -= len(m.SettlementAddress)
		copy(dAtA[i:], m.SettlementAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SettlementAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSubmitSettlementChunkResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitSettlementChunkResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitSettlementChunkResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.NextChunkIndex != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.NextChunkIndex))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgFinalizeSettlement) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgFinalizeSettlement) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgFinalizeSettlement) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Epoch != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Epoch))
		i--
		dAtA[i] = 0x18
	}
	if m.SlotId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.SlotId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgFinalizeSettlementResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgFinalizeSettlementResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgFinalizeSettlementResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ReleasedRemainder) > 0 {
		i -= len(m.ReleasedRemainder)
		copy(dAtA[i:], m.ReleasedRemainder)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ReleasedRemainder)))
		i--
		dAtA[i] = 0x12
	}
	if m.FinalizationReason != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.FinalizationReason))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *SettlementChunkPayout) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Recipient)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Amount)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSubmitSettlementChunk) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SettlementAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.SlotId != 0 {
		n += 1 + sovTx(uint64(m.SlotId))
	}
	if m.Epoch != 0 {
		n += 1 + sovTx(uint64(m.Epoch))
	}
	if m.ChunkIndex != 0 {
		n += 1 + sovTx(uint64(m.ChunkIndex))
	}
	if len(m.Payouts) > 0 {
		for _, e := range m.Payouts {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgSubmitSettlementChunkResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.NextChunkIndex != 0 {
		n += 1 + sovTx(uint64(m.NextChunkIndex))
	}
	return n
}

func (m *MsgFinalizeSettlement) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.SlotId != 0 {
		n += 1 + sovTx(uint64(m.SlotId))
	}
	if m.Epoch != 0 {
		n += 1 + sovTx(uint64(m.Epoch))
	}
	return n
}

func (m *MsgFinalizeSettlementResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.FinalizationReason != 0 {
		n += 1 + sovTx(uint64(m.FinalizationReason))
	}
	l = len(m.ReleasedRemainder)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *SettlementChunkPayout) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SettlementChunkPayout: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SettlementChunkPayout: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Recipient", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Recipient = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitSettlementChunk) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitSettlementChunk: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitSettlementChunk: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SettlementAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SettlementAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SlotId", wireType)
			}
			m.SlotId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SlotId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Epoch", wireType)
			}
			m.Epoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Epoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChunkIndex", wireType)
			}
			m.ChunkIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ChunkIndex |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Payouts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Payouts = append(m.Payouts, &SettlementChunkPayout{})
			if err := m.Payouts[len(m.Payouts)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitSettlementChunkResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitSettlementChunkResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitSettlementChunkResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextChunkIndex", wireType)
			}
			m.NextChunkIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NextChunkIndex |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgFinalizeSettlement) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgFinalizeSettlement: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgFinalizeSettlement: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SlotId", wireType)
			}
			m.SlotId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SlotId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Epoch", wireType)
			}
			m.Epoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Epoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgFinalizeSettlementResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgFinalizeSettlementResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgFinalizeSettlementResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FinalizationReason", wireType)
			}
			m.FinalizationReason = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FinalizationReason |= SettlementFinalizationReason(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReleasedRemainder", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReleasedRemainder = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
