// Package openapi serves the merged Swagger/OpenAPI documentation for Twilight's
// enabled REST surface (the registered Cosmos SDK modules plus the twilight rewards
// and coreslot modules). The spec twilight.swagger.json is generated by
// scripts/protocgen.sh (protoc-gen-openapiv2) and embedded at build time.
package openapi

import (
	"embed"
	"io/fs"
	"net/http"
	"path"
	"strings"

	"github.com/gorilla/mux"

	sdkdocs "github.com/cosmos/cosmos-sdk/client/docs"
)

// index.html (UI shell) and the merged spec are app-specific and embedded here. The
// heavy swagger-ui JS/CSS are reused from the SDK's embedded bundle, so they are not
// duplicated in this repo.
//
//go:embed index.html twilight.swagger.json
var assets embed.FS

// SwaggerSpec exposes the embedded merged OpenAPI document (e.g. for tests).
func SwaggerSpec() ([]byte, error) { return assets.ReadFile("twilight.swagger.json") }

// RegisterSwaggerAPI mounts the Swagger UI and the merged OpenAPI spec under /swagger/
// on the given router when swaggerEnabled is true; it is a no-op otherwise. The UI is
// served at /swagger/ and the spec at /swagger/twilight.swagger.json. Static swagger-ui
// assets (JS/CSS) are served from the Cosmos SDK's embedded swagger-ui bundle.
func RegisterSwaggerAPI(rtr *mux.Router, swaggerEnabled bool) error {
	if !swaggerEnabled {
		return nil
	}

	sdkUI, err := fs.Sub(sdkdocs.SwaggerUI, "swagger-ui")
	if err != nil {
		return err
	}
	sdkAssets := http.FileServer(http.FS(sdkUI))

	rtr.PathPrefix("/swagger/").Handler(http.StripPrefix("/swagger/", http.HandlerFunc(
		func(w http.ResponseWriter, r *http.Request) {
			name := strings.TrimPrefix(path.Clean("/"+r.URL.Path), "/")
			if name == "" {
				name = "index.html"
			}
			switch name {
			case "index.html", "twilight.swagger.json":
				b, err := assets.ReadFile(name)
				if err != nil {
					http.NotFound(w, r)
					return
				}
				if strings.HasSuffix(name, ".json") {
					w.Header().Set("Content-Type", "application/json")
				} else {
					w.Header().Set("Content-Type", "text/html; charset=utf-8")
				}
				_, _ = w.Write(b)
			default:
				// swagger-ui-bundle.js, swagger-ui.css, etc. from the SDK bundle.
				sdkAssets.ServeHTTP(w, r)
			}
		})))

	return nil
}
