// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: nyks/coreslot/v1/genesis.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type GenesisState struct {
	Params                     *Params                     `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	Slots                      []*CoreSlot                 `protobuf:"bytes,2,rep,name=slots,proto3" json:"slots,omitempty"`
	PendingKeyRotations        []*PendingKeyRotation       `protobuf:"bytes,3,rep,name=pending_key_rotations,json=pendingKeyRotations,proto3" json:"pending_key_rotations,omitempty"`
	ReservedConsensusAddresses []*ReservedConsensusAddress `protobuf:"bytes,4,rep,name=reserved_consensus_addresses,json=reservedConsensusAddresses,proto3" json:"reserved_consensus_addresses,omitempty"`
	RewardWeights              []*OperatorRewardWeight     `protobuf:"bytes,5,rep,name=reward_weights,json=rewardWeights,proto3" json:"reward_weights,omitempty"`
	LastAppliedValidators      []*LastAppliedValidator     `protobuf:"bytes,6,rep,name=last_applied_validators,json=lastAppliedValidators,proto3" json:"last_applied_validators,omitempty"`
	NextSlotId                 uint64                      `protobuf:"varint,7,opt,name=next_slot_id,json=nextSlotId,proto3" json:"next_slot_id,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_108df654a9c5d1d7, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() *Params {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *GenesisState) GetSlots() []*CoreSlot {
	if m != nil {
		return m.Slots
	}
	return nil
}

func (m *GenesisState) GetPendingKeyRotations() []*PendingKeyRotation {
	if m != nil {
		return m.PendingKeyRotations
	}
	return nil
}

func (m *GenesisState) GetReservedConsensusAddresses() []*ReservedConsensusAddress {
	if m != nil {
		return m.ReservedConsensusAddresses
	}
	return nil
}

func (m *GenesisState) GetRewardWeights() []*OperatorRewardWeight {
	if m != nil {
		return m.RewardWeights
	}
	return nil
}

func (m *GenesisState) GetLastAppliedValidators() []*LastAppliedValidator {
	if m != nil {
		return m.LastAppliedValidators
	}
	return nil
}

func (m *GenesisState) GetNextSlotId() uint64 {
	if m != nil {
		return m.NextSlotId
	}
	return 0
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "nyks.coreslot.v1.GenesisState")
}

func init() { proto.RegisterFile("nyks/coreslot/v1/genesis.proto", fileDescriptor_108df654a9c5d1d7) }

var fileDescriptor_108df654a9c5d1d7 = []byte{
	// 403 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xd1, 0x6a, 0x14, 0x31,
	0x14, 0x86, 0x77, 0xec, 0x76, 0x85, 0xb4, 0x8a, 0x44, 0x8a, 0x61, 0x91, 0x71, 0x11, 0x91, 0xa5,
	0xe0, 0x4c, 0x5b, 0x9f, 0xa0, 0x56, 0x10, 0x51, 0x51, 0x52, 0x50, 0xf1, 0xc2, 0x90, 0x6e, 0x0e,
	0xd3, 0xd0, 0x69, 0x12, 0x72, 0xd2, 0x69, 0xe7, 0x19, 0xbc, 0xf1, 0xb1, 0xbc, 0xec, 0xa5, 0x97,
	0xb2, 0xfb, 0x22, 0x92, 0xcc, 0xae, 0x8a, 0xd3, 0xbd, 0x19, 0x98, 0xf3, 0x7f, 0xdf, 0x7f, 0x06,
	0xe6, 0x90, 0xdc, 0xb4, 0x67, 0x58, 0xce, 0xac, 0x07, 0xac, 0x6d, 0x28, 0x9b, 0xfd, 0xb2, 0x02,
	0x03, 0xa8, 0xb1, 0x70, 0xde, 0x06, 0x4b, 0xef, 0xc5, 0xbc, 0x58, 0xe5, 0x45, 0xb3, 0x3f, 0x7e,
	0xd4, 0x33, 0xfe, 0xa4, 0x49, 0x79, 0xfc, 0x6d, 0x48, 0xb6, 0x5f, 0x75, 0x25, 0xc7, 0x41, 0x06,
	0xa0, 0x7b, 0x64, 0xe4, 0xa4, 0x97, 0xe7, 0xc8, 0xb2, 0x49, 0x36, 0xdd, 0x3a, 0x60, 0xc5, 0xff,
	0xa5, 0xc5, 0x87, 0x94, 0xf3, 0x25, 0x47, 0xf7, 0xc8, 0x66, 0x4c, 0x90, 0xdd, 0x9a, 0x6c, 0x4c,
	0xb7, 0x0e, 0xc6, 0x7d, 0xe1, 0xc8, 0x7a, 0x38, 0xae, 0x6d, 0xe0, 0x1d, 0x48, 0x3f, 0x93, 0x1d,
	0x07, 0x46, 0x69, 0x53, 0x89, 0x33, 0x68, 0x85, 0xb7, 0x41, 0x06, 0x6d, 0x0d, 0xb2, 0x8d, 0xd4,
	0xf0, 0xe4, 0x86, 0x95, 0x1d, 0xfe, 0x06, 0x5a, 0xbe, 0x84, 0xf9, 0x7d, 0xd7, 0x9b, 0x21, 0xad,
	0xc9, 0x43, 0x0f, 0x08, 0xbe, 0x01, 0x25, 0x66, 0xd6, 0x20, 0x18, 0xbc, 0x40, 0x21, 0x95, 0xf2,
	0x80, 0x08, 0xc8, 0x86, 0x69, 0xc1, 0x6e, 0x7f, 0x01, 0x5f, 0x5a, 0x47, 0x2b, 0xe9, 0xb0, 0x73,
	0xf8, 0xd8, 0xaf, 0x49, 0x00, 0xe9, 0x3b, 0x72, 0xd7, 0xc3, 0xa5, 0xf4, 0x4a, 0x5c, 0x82, 0xae,
	0x4e, 0x03, 0xb2, 0xcd, 0xd4, 0xff, 0xb4, 0xdf, 0xff, 0xde, 0x81, 0x97, 0xc1, 0x7a, 0x9e, 0xf8,
	0x4f, 0x09, 0xe7, 0x77, 0xfc, 0x3f, 0x6f, 0x48, 0xbf, 0x92, 0x07, 0xb5, 0xc4, 0x20, 0xa4, 0x73,
	0xb5, 0x06, 0x25, 0x1a, 0x59, 0x6b, 0x15, 0x25, 0x64, 0xa3, 0x75, 0xbd, 0x6f, 0x25, 0x86, 0xc3,
	0x8e, 0xff, 0xb8, 0xc2, 0xf9, 0x4e, 0x7d, 0xc3, 0x14, 0xe9, 0x84, 0x6c, 0x1b, 0xb8, 0x0a, 0x22,
	0xba, 0x42, 0x2b, 0x76, 0x7b, 0x92, 0x4d, 0x87, 0x9c, 0xc4, 0x59, 0xfc, 0x3b, 0xaf, 0xd5, 0x8b,
	0x97, 0x3f, 0xe6, 0x79, 0x76, 0x3d, 0xcf, 0xb3, 0x5f, 0xf3, 0x3c, 0xfb, 0xbe, 0xc8, 0x07, 0xd7,
	0x8b, 0x7c, 0xf0, 0x73, 0x91, 0x0f, 0xbe, 0xec, 0x56, 0x3a, 0x9c, 0x5e, 0x9c, 0x14, 0x33, 0x7b,
	0x5e, 0xa6, 0x9b, 0x8a, 0x8f, 0x67, 0xf1, 0x4b, 0xca, 0xab, 0xbf, 0xf7, 0x15, 0x5a, 0x07, 0x78,
	0x32, 0x4a, 0xa7, 0xf5, 0xfc, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6b, 0xd6, 0x40, 0xc6, 0xaf,
	0x02, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.NextSlotId != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.NextSlotId))
		i--
		dAtA[i] = 0x38
	}
	if len(m.LastAppliedValidators) > 0 {
		for iNdEx := len(m.LastAppliedValidators) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.LastAppliedValidators[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.RewardWeights) > 0 {
		for iNdEx := len(m.RewardWeights) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RewardWeights[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.ReservedConsensusAddresses) > 0 {
		for iNdEx := len(m.ReservedConsensusAddresses) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ReservedConsensusAddresses[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.PendingKeyRotations) > 0 {
		for iNdEx := len(m.PendingKeyRotations) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PendingKeyRotations[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Slots) > 0 {
		for iNdEx := len(m.Slots) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Slots[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.Params != nil {
		{
			size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenesis(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Params != nil {
		l = m.Params.Size()
		n += 1 + l + sovGenesis(uint64(l))
	}
	if len(m.Slots) > 0 {
		for _, e := range m.Slots {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.PendingKeyRotations) > 0 {
		for _, e := range m.PendingKeyRotations {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.ReservedConsensusAddresses) > 0 {
		for _, e := range m.ReservedConsensusAddresses {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.RewardWeights) > 0 {
		for _, e := range m.RewardWeights {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.LastAppliedValidators) > 0 {
		for _, e := range m.LastAppliedValidators {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.NextSlotId != 0 {
		n += 1 + sovGenesis(uint64(m.NextSlotId))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Params == nil {
				m.Params = &Params{}
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Slots", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Slots = append(m.Slots, &CoreSlot{})
			if err := m.Slots[len(m.Slots)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PendingKeyRotations", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PendingKeyRotations = append(m.PendingKeyRotations, &PendingKeyRotation{})
			if err := m.PendingKeyRotations[len(m.PendingKeyRotations)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReservedConsensusAddresses", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReservedConsensusAddresses = append(m.ReservedConsensusAddresses, &ReservedConsensusAddress{})
			if err := m.ReservedConsensusAddresses[len(m.ReservedConsensusAddresses)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardWeights", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RewardWeights = append(m.RewardWeights, &OperatorRewardWeight{})
			if err := m.RewardWeights[len(m.RewardWeights)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastAppliedValidators", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LastAppliedValidators = append(m.LastAppliedValidators, &LastAppliedValidator{})
			if err := m.LastAppliedValidators[len(m.LastAppliedValidators)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextSlotId", wireType)
			}
			m.NextSlotId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NextSlotId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
