// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: nyks/coreslot/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ec087fa5be26cf6, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

type QueryParamsResponse struct {
	Params *Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ec087fa5be26cf6, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() *Params {
	if m != nil {
		return m.Params
	}
	return nil
}

type QueryCoreSlotRequest struct {
	SlotId uint64 `protobuf:"varint,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
}

func (m *QueryCoreSlotRequest) Reset()         { *m = QueryCoreSlotRequest{} }
func (m *QueryCoreSlotRequest) String() string { return proto.CompactTextString(m) }
func (*QueryCoreSlotRequest) ProtoMessage()    {}
func (*QueryCoreSlotRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ec087fa5be26cf6, []int{2}
}
func (m *QueryCoreSlotRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCoreSlotRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCoreSlotRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCoreSlotRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCoreSlotRequest.Merge(m, src)
}
func (m *QueryCoreSlotRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryCoreSlotRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCoreSlotRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCoreSlotRequest proto.InternalMessageInfo

func (m *QueryCoreSlotRequest) GetSlotId() uint64 {
	if m != nil {
		return m.SlotId
	}
	return 0
}

type QueryCoreSlotByOperatorRequest struct {
	OperatorAddress string `protobuf:"bytes,1,opt,name=operator_address,json=operatorAddress,proto3" json:"operator_address,omitempty"`
}

func (m *QueryCoreSlotByOperatorRequest) Reset()         { *m = QueryCoreSlotByOperatorRequest{} }
func (m *QueryCoreSlotByOperatorRequest) String() string { return proto.CompactTextString(m) }
func (*QueryCoreSlotByOperatorRequest) ProtoMessage()    {}
func (*QueryCoreSlotByOperatorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ec087fa5be26cf6, []int{3}
}
func (m *QueryCoreSlotByOperatorRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCoreSlotByOperatorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCoreSlotByOperatorRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCoreSlotByOperatorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCoreSlotByOperatorRequest.Merge(m, src)
}
func (m *QueryCoreSlotByOperatorRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryCoreSlotByOperatorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCoreSlotByOperatorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCoreSlotByOperatorRequest proto.InternalMessageInfo

func (m *QueryCoreSlotByOperatorRequest) GetOperatorAddress() string {
	if m != nil {
		return m.OperatorAddress
	}
	return ""
}

type QueryCoreSlotByConsensusAddressRequest struct {
	ConsensusAddress string `protobuf:"bytes,1,opt,name=consensus_address,json=consensusAddress,proto3" json:"consensus_address,omitempty"`
}

func (m *QueryCoreSlotByConsensusAddressRequest) Reset() {
	*m = QueryCoreSlotByConsensusAddressRequest{}
}
func (m *QueryCoreSlotByConsensusAddressRequest) String() string { return proto.CompactTextString(m) }
func (*QueryCoreSlotByConsensusAddressRequest) ProtoMessage()    {}
func (*QueryCoreSlotByConsensusAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ec087fa5be26cf6, []int{4}
}
func (m *QueryCoreSlotByConsensusAddressRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCoreSlotByConsensusAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCoreSlotByConsensusAddressRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCoreSlotByConsensusAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCoreSlotByConsensusAddressRequest.Merge(m, src)
}
func (m *QueryCoreSlotByConsensusAddressRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryCoreSlotByConsensusAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCoreSlotByConsensusAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCoreSlotByConsensusAddressRequest proto.InternalMessageInfo

func (m *QueryCoreSlotByConsensusAddressRequest) GetConsensusAddress() string {
	if m != nil {
		return m.ConsensusAddress
	}
	return ""
}

type QueryCoreSlotResponse struct {
	Slot *CoreSlot `protobuf:"bytes,1,opt,name=slot,proto3" json:"slot,omitempty"`
}

func (m *QueryCoreSlotResponse) Reset()         { *m = QueryCoreSlotResponse{} }
func (m *QueryCoreSlotResponse) String() string { return proto.CompactTextString(m) }
func (*QueryCoreSlotResponse) ProtoMessage()    {}
func (*QueryCoreSlotResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ec087fa5be26cf6, []int{5}
}
func (m *QueryCoreSlotResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCoreSlotResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCoreSlotResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCoreSlotResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCoreSlotResponse.Merge(m, src)
}
func (m *QueryCoreSlotResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryCoreSlotResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCoreSlotResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCoreSlotResponse proto.InternalMessageInfo

func (m *QueryCoreSlotResponse) GetSlot() *CoreSlot {
	if m != nil {
		return m.Slot
	}
	return nil
}

type QueryCoreSlotsRequest struct {
	Status     SlotStatus         `protobuf:"varint,1,opt,name=status,proto3,enum=nyks.coreslot.v1.SlotStatus" json:"status,omitempty"`
	Pagination *query.PageRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryCoreSlotsRequest) Reset()         { *m = QueryCoreSlotsRequest{} }
func (m *QueryCoreSlotsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryCoreSlotsRequest) ProtoMessage()    {}
func (*QueryCoreSlotsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ec087fa5be26cf6, []int{6}
}
func (m *QueryCoreSlotsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCoreSlotsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCoreSlotsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCoreSlotsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCoreSlotsRequest.Merge(m, src)
}
func (m *QueryCoreSlotsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryCoreSlotsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCoreSlotsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCoreSlotsRequest proto.InternalMessageInfo

func (m *QueryCoreSlotsRequest) GetStatus() SlotStatus {
	if m != nil {
		return m.Status
	}
	return SlotStatus_SLOT_STATUS_UNSPECIFIED
}

func (m *QueryCoreSlotsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryCoreSlotsResponse struct {
	Slots      []*CoreSlot         `protobuf:"bytes,1,rep,name=slots,proto3" json:"slots,omitempty"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryCoreSlotsResponse) Reset()         { *m = QueryCoreSlotsResponse{} }
func (m *QueryCoreSlotsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryCoreSlotsResponse) ProtoMessage()    {}
func (*QueryCoreSlotsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ec087fa5be26cf6, []int{7}
}
func (m *QueryCoreSlotsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCoreSlotsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCoreSlotsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCoreSlotsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCoreSlotsResponse.Merge(m, src)
}
func (m *QueryCoreSlotsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryCoreSlotsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCoreSlotsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCoreSlotsResponse proto.InternalMessageInfo

func (m *QueryCoreSlotsResponse) GetSlots() []*CoreSlot {
	if m != nil {
		return m.Slots
	}
	return nil
}

func (m *QueryCoreSlotsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryActiveCoreSlotsRequest struct {
}

func (m *QueryActiveCoreSlotsRequest) Reset()         { *m = QueryActiveCoreSlotsRequest{} }
func (m *QueryActiveCoreSlotsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryActiveCoreSlotsRequest) ProtoMessage()    {}
func (*QueryActiveCoreSlotsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ec087fa5be26cf6, []int{8}
}
func (m *QueryActiveCoreSlotsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryActiveCoreSlotsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryActiveCoreSlotsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryActiveCoreSlotsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryActiveCoreSlotsRequest.Merge(m, src)
}
func (m *QueryActiveCoreSlotsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryActiveCoreSlotsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryActiveCoreSlotsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryActiveCoreSlotsRequest proto.InternalMessageInfo

type QueryPendingKeyRotationsRequest struct {
}

func (m *QueryPendingKeyRotationsRequest) Reset()         { *m = QueryPendingKeyRotationsRequest{} }
func (m *QueryPendingKeyRotationsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryPendingKeyRotationsRequest) ProtoMessage()    {}
func (*QueryPendingKeyRotationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ec087fa5be26cf6, []int{9}
}
func (m *QueryPendingKeyRotationsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPendingKeyRotationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPendingKeyRotationsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPendingKeyRotationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPendingKeyRotationsRequest.Merge(m, src)
}
func (m *QueryPendingKeyRotationsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryPendingKeyRotationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPendingKeyRotationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPendingKeyRotationsRequest proto.InternalMessageInfo

type QueryPendingKeyRotationsResponse struct {
	Rotations []*PendingKeyRotation `protobuf:"bytes,1,rep,name=rotations,proto3" json:"rotations,omitempty"`
}

func (m *QueryPendingKeyRotationsResponse) Reset()         { *m = QueryPendingKeyRotationsResponse{} }
func (m *QueryPendingKeyRotationsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryPendingKeyRotationsResponse) ProtoMessage()    {}
func (*QueryPendingKeyRotationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ec087fa5be26cf6, []int{10}
}
func (m *QueryPendingKeyRotationsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPendingKeyRotationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPendingKeyRotationsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPendingKeyRotationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPendingKeyRotationsResponse.Merge(m, src)
}
func (m *QueryPendingKeyRotationsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryPendingKeyRotationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPendingKeyRotationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPendingKeyRotationsResponse proto.InternalMessageInfo

func (m *QueryPendingKeyRotationsResponse) GetRotations() []*PendingKeyRotation {
	if m != nil {
		return m.Rotations
	}
	return nil
}

type QueryLastAppliedValidatorsRequest struct {
}

func (m *QueryLastAppliedValidatorsRequest) Reset()         { *m = QueryLastAppliedValidatorsRequest{} }
func (m *QueryLastAppliedValidatorsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryLastAppliedValidatorsRequest) ProtoMessage()    {}
func (*QueryLastAppliedValidatorsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ec087fa5be26cf6, []int{11}
}
func (m *QueryLastAppliedValidatorsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryLastAppliedValidatorsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryLastAppliedValidatorsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryLastAppliedValidatorsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLastAppliedValidatorsRequest.Merge(m, src)
}
func (m *QueryLastAppliedValidatorsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryLastAppliedValidatorsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLastAppliedValidatorsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLastAppliedValidatorsRequest proto.InternalMessageInfo

type QueryLastAppliedValidatorsResponse struct {
	Validators []*LastAppliedValidator `protobuf:"bytes,1,rep,name=validators,proto3" json:"validators,omitempty"`
}

func (m *QueryLastAppliedValidatorsResponse) Reset()         { *m = QueryLastAppliedValidatorsResponse{} }
func (m *QueryLastAppliedValidatorsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryLastAppliedValidatorsResponse) ProtoMessage()    {}
func (*QueryLastAppliedValidatorsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ec087fa5be26cf6, []int{12}
}
func (m *QueryLastAppliedValidatorsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryLastAppliedValidatorsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryLastAppliedValidatorsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryLastAppliedValidatorsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLastAppliedValidatorsResponse.Merge(m, src)
}
func (m *QueryLastAppliedValidatorsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryLastAppliedValidatorsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLastAppliedValidatorsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLastAppliedValidatorsResponse proto.InternalMessageInfo

func (m *QueryLastAppliedValidatorsResponse) GetValidators() []*LastAppliedValidator {
	if m != nil {
		return m.Validators
	}
	return nil
}

type QueryReservedConsensusAddressRequest struct {
	ConsensusAddress string `protobuf:"bytes,1,opt,name=consensus_address,json=consensusAddress,proto3" json:"consensus_address,omitempty"`
}

func (m *QueryReservedConsensusAddressRequest) Reset()         { *m = QueryReservedConsensusAddressRequest{} }
func (m *QueryReservedConsensusAddressRequest) String() string { return proto.CompactTextString(m) }
func (*QueryReservedConsensusAddressRequest) ProtoMessage()    {}
func (*QueryReservedConsensusAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ec087fa5be26cf6, []int{13}
}
func (m *QueryReservedConsensusAddressRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryReservedConsensusAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryReservedConsensusAddressRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryReservedConsensusAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryReservedConsensusAddressRequest.Merge(m, src)
}
func (m *QueryReservedConsensusAddressRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryReservedConsensusAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryReservedConsensusAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryReservedConsensusAddressRequest proto.InternalMessageInfo

func (m *QueryReservedConsensusAddressRequest) GetConsensusAddress() string {
	if m != nil {
		return m.ConsensusAddress
	}
	return ""
}

type QueryReservedConsensusAddressResponse struct {
	Reservation *ReservedConsensusAddress `protobuf:"bytes,1,opt,name=reservation,proto3" json:"reservation,omitempty"`
}

func (m *QueryReservedConsensusAddressResponse) Reset()         { *m = QueryReservedConsensusAddressResponse{} }
func (m *QueryReservedConsensusAddressResponse) String() string { return proto.CompactTextString(m) }
func (*QueryReservedConsensusAddressResponse) ProtoMessage()    {}
func (*QueryReservedConsensusAddressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ec087fa5be26cf6, []int{14}
}
func (m *QueryReservedConsensusAddressResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryReservedConsensusAddressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryReservedConsensusAddressResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryReservedConsensusAddressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryReservedConsensusAddressResponse.Merge(m, src)
}
func (m *QueryReservedConsensusAddressResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryReservedConsensusAddressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryReservedConsensusAddressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryReservedConsensusAddressResponse proto.InternalMessageInfo

func (m *QueryReservedConsensusAddressResponse) GetReservation() *ReservedConsensusAddress {
	if m != nil {
		return m.Reservation
	}
	return nil
}

type QueryRewardWeightRequest struct {
	SlotId uint64 `protobuf:"varint,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
}

func (m *QueryRewardWeightRequest) Reset()         { *m = QueryRewardWeightRequest{} }
func (m *QueryRewardWeightRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRewardWeightRequest) ProtoMessage()    {}
func (*QueryRewardWeightRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ec087fa5be26cf6, []int{15}
}
func (m *QueryRewardWeightRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRewardWeightRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRewardWeightRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRewardWeightRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRewardWeightRequest.Merge(m, src)
}
func (m *QueryRewardWeightRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryRewardWeightRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRewardWeightRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRewardWeightRequest proto.InternalMessageInfo

func (m *QueryRewardWeightRequest) GetSlotId() uint64 {
	if m != nil {
		return m.SlotId
	}
	return 0
}

type QueryRewardWeightResponse struct {
	RewardWeight *OperatorRewardWeight `protobuf:"bytes,1,opt,name=reward_weight,json=rewardWeight,proto3" json:"reward_weight,omitempty"`
}

func (m *QueryRewardWeightResponse) Reset()         { *m = QueryRewardWeightResponse{} }
func (m *QueryRewardWeightResponse) String() string { return proto.CompactTextString(m) }
func (*QueryRewardWeightResponse) ProtoMessage()    {}
func (*QueryRewardWeightResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ec087fa5be26cf6, []int{16}
}
func (m *QueryRewardWeightResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRewardWeightResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRewardWeightResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRewardWeightResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRewardWeightResponse.Merge(m, src)
}
func (m *QueryRewardWeightResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryRewardWeightResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRewardWeightResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRewardWeightResponse proto.InternalMessageInfo

func (m *QueryRewardWeightResponse) GetRewardWeight() *OperatorRewardWeight {
	if m != nil {
		return m.RewardWeight
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "nyks.coreslot.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "nyks.coreslot.v1.QueryParamsResponse")
	proto.RegisterType((*QueryCoreSlotRequest)(nil), "nyks.coreslot.v1.QueryCoreSlotRequest")
	proto.RegisterType((*QueryCoreSlotByOperatorRequest)(nil), "nyks.coreslot.v1.QueryCoreSlotByOperatorRequest")
	proto.RegisterType((*QueryCoreSlotByConsensusAddressRequest)(nil), "nyks.coreslot.v1.QueryCoreSlotByConsensusAddressRequest")
	proto.RegisterType((*QueryCoreSlotResponse)(nil), "nyks.coreslot.v1.QueryCoreSlotResponse")
	proto.RegisterType((*QueryCoreSlotsRequest)(nil), "nyks.coreslot.v1.QueryCoreSlotsRequest")
	proto.RegisterType((*QueryCoreSlotsResponse)(nil), "nyks.coreslot.v1.QueryCoreSlotsResponse")
	proto.RegisterType((*QueryActiveCoreSlotsRequest)(nil), "nyks.coreslot.v1.QueryActiveCoreSlotsRequest")
	proto.RegisterType((*QueryPendingKeyRotationsRequest)(nil), "nyks.coreslot.v1.QueryPendingKeyRotationsRequest")
	proto.RegisterType((*QueryPendingKeyRotationsResponse)(nil), "nyks.coreslot.v1.QueryPendingKeyRotationsResponse")
	proto.RegisterType((*QueryLastAppliedValidatorsRequest)(nil), "nyks.coreslot.v1.QueryLastAppliedValidatorsRequest")
	proto.RegisterType((*QueryLastAppliedValidatorsResponse)(nil), "nyks.coreslot.v1.QueryLastAppliedValidatorsResponse")
	proto.RegisterType((*QueryReservedConsensusAddressRequest)(nil), "nyks.coreslot.v1.QueryReservedConsensusAddressRequest")
	proto.RegisterType((*QueryReservedConsensusAddressResponse)(nil), "nyks.coreslot.v1.QueryReservedConsensusAddressResponse")
	proto.RegisterType((*QueryRewardWeightRequest)(nil), "nyks.coreslot.v1.QueryRewardWeightRequest")
	proto.RegisterType((*QueryRewardWeightResponse)(nil), "nyks.coreslot.v1.QueryRewardWeightResponse")
}

func init() { proto.RegisterFile("nyks/coreslot/v1/query.proto", fileDescriptor_2ec087fa5be26cf6) }

var fileDescriptor_2ec087fa5be26cf6 = []byte{
	// 913 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0x4f, 0x6f, 0x1b, 0x45,
	0x1c, 0xcd, 0x96, 0xd6, 0x90, 0x5f, 0x0b, 0x0d, 0xd3, 0x96, 0xba, 0x4b, 0xd8, 0x38, 0xdb, 0xd6,
	0x6d, 0x5d, 0x75, 0x27, 0x76, 0xaa, 0x96, 0x6b, 0x52, 0x94, 0x08, 0x25, 0x12, 0x61, 0x23, 0x40,
	0xe2, 0x12, 0x8d, 0xbd, 0xc3, 0x66, 0x85, 0xb3, 0xb3, 0xd9, 0x59, 0x3b, 0x58, 0x21, 0x42, 0xca,
	0x81, 0x0b, 0x17, 0x44, 0xc4, 0x67, 0xe0, 0x2b, 0xf0, 0x11, 0x38, 0x46, 0xe2, 0xc2, 0x11, 0x25,
	0x7c, 0x0e, 0x84, 0x76, 0x66, 0x76, 0xed, 0xec, 0x9f, 0x6c, 0x2c, 0x71, 0xb1, 0xe4, 0x99, 0xf7,
	0x7b, 0xef, 0xcd, 0xf8, 0x37, 0xef, 0x67, 0x98, 0xf7, 0x47, 0xdf, 0x72, 0xdc, 0x63, 0x21, 0xe5,
	0x7d, 0x16, 0xe1, 0x61, 0x1b, 0xef, 0x0f, 0x68, 0x38, 0xb2, 0x82, 0x90, 0x45, 0x0c, 0xcd, 0xc5,
	0xbb, 0x56, 0xb2, 0x6b, 0x0d, 0xdb, 0x7a, 0xab, 0xc7, 0xf8, 0x1e, 0xe3, 0xb8, 0x4b, 0x38, 0x95,
	0x50, 0x3c, 0x6c, 0x77, 0x69, 0x44, 0xda, 0x38, 0x20, 0xae, 0xe7, 0x93, 0xc8, 0x63, 0xbe, 0xac,
	0xd6, 0xe7, 0x5d, 0xc6, 0xdc, 0x3e, 0xc5, 0x24, 0xf0, 0x30, 0xf1, 0x7d, 0x16, 0x89, 0x4d, 0xae,
	0x76, 0x17, 0x72, 0xca, 0xa9, 0x8e, 0x00, 0x98, 0x77, 0x01, 0x7d, 0x1e, 0x0b, 0x6c, 0x91, 0x90,
	0xec, 0x71, 0x9b, 0xee, 0x0f, 0x28, 0x8f, 0xcc, 0x75, 0xb8, 0x73, 0x61, 0x95, 0x07, 0xcc, 0xe7,
	0x14, 0x2d, 0x41, 0x2d, 0x10, 0x2b, 0x75, 0xad, 0xa1, 0x3d, 0xbd, 0xd9, 0xa9, 0x5b, 0x59, 0xeb,
	0x96, 0xaa, 0x50, 0x38, 0x13, 0xc3, 0x5d, 0x41, 0xf4, 0x86, 0x85, 0x74, 0xbb, 0xcf, 0x22, 0x25,
	0x80, 0xee, 0xc3, 0xdb, 0x71, 0xc5, 0x8e, 0xe7, 0x08, 0xaa, 0xeb, 0x76, 0x2d, 0xfe, 0xfa, 0xa9,
	0x63, 0x6e, 0x80, 0x71, 0xa1, 0x60, 0x75, 0xf4, 0x59, 0x40, 0x43, 0x12, 0xb1, 0x30, 0x29, 0x7d,
	0x06, 0x73, 0x4c, 0x2d, 0xed, 0x10, 0xc7, 0x09, 0x29, 0x97, 0x76, 0x66, 0xed, 0xdb, 0xc9, 0xfa,
	0x8a, 0x5c, 0x36, 0xbf, 0x80, 0x66, 0x86, 0xec, 0x4d, 0x7c, 0x0e, 0x9f, 0x0f, 0xb8, 0x82, 0x24,
	0xa4, 0xcf, 0xe1, 0xfd, 0x5e, 0xb2, 0x95, 0x61, 0x9d, 0xeb, 0x65, 0x6a, 0xcc, 0x75, 0xb8, 0x97,
	0x39, 0x94, 0xba, 0x1f, 0x0b, 0xae, 0xc7, 0xc7, 0x50, 0xb7, 0xa3, 0xe7, 0x6f, 0x27, 0xad, 0x10,
	0x38, 0xf3, 0x57, 0x2d, 0xc3, 0x94, 0xfa, 0x79, 0x09, 0x35, 0x1e, 0x91, 0x68, 0x20, 0x4d, 0xbc,
	0xd7, 0x99, 0xcf, 0x73, 0xc5, 0xf8, 0x6d, 0x81, 0xb1, 0x15, 0x16, 0xad, 0x01, 0x8c, 0xfb, 0xa3,
	0x7e, 0x4d, 0xb8, 0x68, 0x5a, 0xb2, 0x99, 0xac, 0xb8, 0x99, 0x2c, 0xd9, 0x77, 0xaa, 0x99, 0xac,
	0x2d, 0xe2, 0x52, 0xa5, 0x68, 0x4f, 0x54, 0x9a, 0x27, 0x1a, 0x7c, 0x90, 0xf5, 0x95, 0xb6, 0xc0,
	0x8d, 0xd8, 0x40, 0xec, 0xeb, 0xad, 0x8a, 0x33, 0x4a, 0x20, 0x5a, 0x2f, 0x30, 0xf5, 0xa4, 0xd2,
	0x94, 0x94, 0xbb, 0xe0, 0xea, 0x23, 0xf8, 0x50, 0x98, 0x5a, 0xe9, 0x45, 0xde, 0x90, 0x66, 0xaf,
	0xcc, 0x5c, 0x84, 0x05, 0xd9, 0xb3, 0xd4, 0x77, 0x3c, 0xdf, 0xdd, 0xa0, 0x23, 0x3b, 0x79, 0x0c,
	0x09, 0xe4, 0x1b, 0x68, 0x94, 0x43, 0xd4, 0x01, 0x57, 0x61, 0x36, 0x4c, 0x16, 0xd5, 0x21, 0x1f,
	0x15, 0xb4, 0x79, 0x8e, 0xc1, 0x1e, 0x97, 0x99, 0x0f, 0x61, 0x51, 0xe8, 0x6c, 0x12, 0x1e, 0xad,
	0x04, 0x41, 0xdf, 0xa3, 0xce, 0x97, 0xa4, 0xef, 0x39, 0x71, 0x6f, 0xa6, 0x66, 0xfa, 0x60, 0x5e,
	0x06, 0x52, 0x76, 0xd6, 0x00, 0x86, 0xe9, 0xaa, 0xf2, 0xd3, 0xcc, 0xfb, 0x29, 0x22, 0xb1, 0x27,
	0x2a, 0xcd, 0x6d, 0x78, 0x24, 0xd4, 0x6c, 0xca, 0x69, 0x38, 0xa4, 0xce, 0xff, 0xf2, 0x10, 0x06,
	0xf0, 0xb8, 0x82, 0x54, 0x9d, 0x62, 0x13, 0x6e, 0x86, 0x02, 0x23, 0x9b, 0x40, 0xbe, 0x8f, 0x56,
	0xfe, 0x18, 0xa5, 0x44, 0x93, 0xe5, 0xe6, 0x32, 0xd4, 0x95, 0xec, 0x01, 0x09, 0x9d, 0xaf, 0xa8,
	0xe7, 0xee, 0x56, 0x07, 0xcb, 0x2e, 0x3c, 0x28, 0x28, 0x52, 0xfe, 0x36, 0xe0, 0xdd, 0x50, 0xac,
	0xef, 0x1c, 0x88, 0x0d, 0xe5, 0xb0, 0xe0, 0xa2, 0xc7, 0x69, 0x34, 0x41, 0x73, 0x2b, 0x9c, 0xf8,
	0xd6, 0xf9, 0x17, 0xe0, 0x86, 0x90, 0x42, 0x07, 0x50, 0x93, 0x79, 0x88, 0x0a, 0x5a, 0x28, 0x1f,
	0xbb, 0xfa, 0xe3, 0x0a, 0x94, 0x74, 0x6b, 0x36, 0x8e, 0xff, 0xfc, 0xe7, 0xe4, 0x9a, 0x8e, 0xea,
	0x38, 0x97, 0xee, 0x32, 0x76, 0xd1, 0x8f, 0x1a, 0xbc, 0x93, 0x3c, 0x10, 0xd4, 0x2c, 0x61, 0xcd,
	0x64, 0xb2, 0xfe, 0xa4, 0x12, 0xa7, 0xf4, 0x9f, 0x09, 0xfd, 0x87, 0x68, 0x31, 0xaf, 0x2f, 0x9e,
	0x3c, 0x3e, 0x54, 0x3f, 0xc1, 0x11, 0xfa, 0x01, 0x66, 0xd3, 0x87, 0x8a, 0xaa, 0x04, 0xd2, 0x7b,
	0x78, 0x5a, 0x0d, 0x54, 0x56, 0x16, 0x84, 0x95, 0x07, 0xe8, 0x7e, 0x89, 0x15, 0xf4, 0x8b, 0x06,
	0xb7, 0x33, 0x81, 0x81, 0x5e, 0x94, 0xd0, 0x17, 0x07, 0xcb, 0x14, 0x6e, 0x9a, 0xc2, 0x4d, 0x03,
	0x19, 0x65, 0x17, 0x43, 0x84, 0x02, 0xfa, 0x4d, 0x03, 0x94, 0x1f, 0x70, 0x68, 0xa9, 0x42, 0x28,
	0x37, 0x0b, 0xaf, 0xfe, 0x93, 0xbd, 0x12, 0xce, 0x96, 0x90, 0x95, 0x77, 0x96, 0x0c, 0x4d, 0x8e,
	0x0f, 0xb3, 0x73, 0xf5, 0x08, 0xfd, 0xae, 0x81, 0x5e, 0x3e, 0x3d, 0xd1, 0xc7, 0x95, 0x8e, 0x4b,
	0x72, 0xe6, 0xea, 0xce, 0x5f, 0x0b, 0xe7, 0x6d, 0x84, 0x71, 0xc1, 0x5f, 0x19, 0xc5, 0x8d, 0x0f,
	0x73, 0x99, 0x75, 0x84, 0xbe, 0x87, 0x3b, 0x05, 0x39, 0x8f, 0xda, 0x65, 0x6f, 0xac, 0x74, 0x6c,
	0xe8, 0x9d, 0x69, 0x4a, 0x54, 0xa2, 0x1c, 0x6b, 0x70, 0xaf, 0x30, 0xd9, 0xd1, 0x72, 0x09, 0xdb,
	0x65, 0xc3, 0x42, 0x7f, 0x39, 0x5d, 0x91, 0x32, 0xf1, 0x93, 0x06, 0xf5, 0xb2, 0x48, 0x45, 0xaf,
	0x4a, 0x28, 0x2b, 0x26, 0x84, 0xfe, 0x7a, 0xea, 0x3a, 0xe5, 0xc6, 0x85, 0x5b, 0x93, 0xa9, 0x89,
	0x5a, 0xa5, 0x44, 0xb9, 0x58, 0xd7, 0x9f, 0x5f, 0x09, 0x2b, 0x85, 0x56, 0x3f, 0xf9, 0xe3, 0xcc,
	0xd0, 0x4e, 0xcf, 0x0c, 0xed, 0xef, 0x33, 0x43, 0xfb, 0xf9, 0xdc, 0x98, 0x39, 0x3d, 0x37, 0x66,
	0xfe, 0x3a, 0x37, 0x66, 0xbe, 0x6e, 0xb9, 0x5e, 0xb4, 0x3b, 0xe8, 0x5a, 0x3d, 0xb6, 0x27, 0xdb,
	0x29, 0xfe, 0x78, 0x11, 0xb3, 0xe2, 0xef, 0xc6, 0xad, 0x15, 0x8d, 0x02, 0xca, 0xbb, 0x35, 0xf1,
	0x07, 0x79, 0xf9, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x43, 0x33, 0xcd, 0x0c, 0xbd, 0x0b, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	CoreSlot(ctx context.Context, in *QueryCoreSlotRequest, opts ...grpc.CallOption) (*QueryCoreSlotResponse, error)
	CoreSlots(ctx context.Context, in *QueryCoreSlotsRequest, opts ...grpc.CallOption) (*QueryCoreSlotsResponse, error)
	ActiveCoreSlots(ctx context.Context, in *QueryActiveCoreSlotsRequest, opts ...grpc.CallOption) (*QueryCoreSlotsResponse, error)
	CoreSlotByOperator(ctx context.Context, in *QueryCoreSlotByOperatorRequest, opts ...grpc.CallOption) (*QueryCoreSlotResponse, error)
	CoreSlotByConsensusAddress(ctx context.Context, in *QueryCoreSlotByConsensusAddressRequest, opts ...grpc.CallOption) (*QueryCoreSlotResponse, error)
	PendingKeyRotations(ctx context.Context, in *QueryPendingKeyRotationsRequest, opts ...grpc.CallOption) (*QueryPendingKeyRotationsResponse, error)
	LastAppliedValidators(ctx context.Context, in *QueryLastAppliedValidatorsRequest, opts ...grpc.CallOption) (*QueryLastAppliedValidatorsResponse, error)
	ReservedConsensusAddress(ctx context.Context, in *QueryReservedConsensusAddressRequest, opts ...grpc.CallOption) (*QueryReservedConsensusAddressResponse, error)
	RewardWeight(ctx context.Context, in *QueryRewardWeightRequest, opts ...grpc.CallOption) (*QueryRewardWeightResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/nyks.coreslot.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) CoreSlot(ctx context.Context, in *QueryCoreSlotRequest, opts ...grpc.CallOption) (*QueryCoreSlotResponse, error) {
	out := new(QueryCoreSlotResponse)
	err := c.cc.Invoke(ctx, "/nyks.coreslot.v1.Query/CoreSlot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) CoreSlots(ctx context.Context, in *QueryCoreSlotsRequest, opts ...grpc.CallOption) (*QueryCoreSlotsResponse, error) {
	out := new(QueryCoreSlotsResponse)
	err := c.cc.Invoke(ctx, "/nyks.coreslot.v1.Query/CoreSlots", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ActiveCoreSlots(ctx context.Context, in *QueryActiveCoreSlotsRequest, opts ...grpc.CallOption) (*QueryCoreSlotsResponse, error) {
	out := new(QueryCoreSlotsResponse)
	err := c.cc.Invoke(ctx, "/nyks.coreslot.v1.Query/ActiveCoreSlots", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) CoreSlotByOperator(ctx context.Context, in *QueryCoreSlotByOperatorRequest, opts ...grpc.CallOption) (*QueryCoreSlotResponse, error) {
	out := new(QueryCoreSlotResponse)
	err := c.cc.Invoke(ctx, "/nyks.coreslot.v1.Query/CoreSlotByOperator", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) CoreSlotByConsensusAddress(ctx context.Context, in *QueryCoreSlotByConsensusAddressRequest, opts ...grpc.CallOption) (*QueryCoreSlotResponse, error) {
	out := new(QueryCoreSlotResponse)
	err := c.cc.Invoke(ctx, "/nyks.coreslot.v1.Query/CoreSlotByConsensusAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) PendingKeyRotations(ctx context.Context, in *QueryPendingKeyRotationsRequest, opts ...grpc.CallOption) (*QueryPendingKeyRotationsResponse, error) {
	out := new(QueryPendingKeyRotationsResponse)
	err := c.cc.Invoke(ctx, "/nyks.coreslot.v1.Query/PendingKeyRotations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) LastAppliedValidators(ctx context.Context, in *QueryLastAppliedValidatorsRequest, opts ...grpc.CallOption) (*QueryLastAppliedValidatorsResponse, error) {
	out := new(QueryLastAppliedValidatorsResponse)
	err := c.cc.Invoke(ctx, "/nyks.coreslot.v1.Query/LastAppliedValidators", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ReservedConsensusAddress(ctx context.Context, in *QueryReservedConsensusAddressRequest, opts ...grpc.CallOption) (*QueryReservedConsensusAddressResponse, error) {
	out := new(QueryReservedConsensusAddressResponse)
	err := c.cc.Invoke(ctx, "/nyks.coreslot.v1.Query/ReservedConsensusAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) RewardWeight(ctx context.Context, in *QueryRewardWeightRequest, opts ...grpc.CallOption) (*QueryRewardWeightResponse, error) {
	out := new(QueryRewardWeightResponse)
	err := c.cc.Invoke(ctx, "/nyks.coreslot.v1.Query/RewardWeight", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	CoreSlot(context.Context, *QueryCoreSlotRequest) (*QueryCoreSlotResponse, error)
	CoreSlots(context.Context, *QueryCoreSlotsRequest) (*QueryCoreSlotsResponse, error)
	ActiveCoreSlots(context.Context, *QueryActiveCoreSlotsRequest) (*QueryCoreSlotsResponse, error)
	CoreSlotByOperator(context.Context, *QueryCoreSlotByOperatorRequest) (*QueryCoreSlotResponse, error)
	CoreSlotByConsensusAddress(context.Context, *QueryCoreSlotByConsensusAddressRequest) (*QueryCoreSlotResponse, error)
	PendingKeyRotations(context.Context, *QueryPendingKeyRotationsRequest) (*QueryPendingKeyRotationsResponse, error)
	LastAppliedValidators(context.Context, *QueryLastAppliedValidatorsRequest) (*QueryLastAppliedValidatorsResponse, error)
	ReservedConsensusAddress(context.Context, *QueryReservedConsensusAddressRequest) (*QueryReservedConsensusAddressResponse, error)
	RewardWeight(context.Context, *QueryRewardWeightRequest) (*QueryRewardWeightResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) CoreSlot(ctx context.Context, req *QueryCoreSlotRequest) (*QueryCoreSlotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CoreSlot not implemented")
}
func (*UnimplementedQueryServer) CoreSlots(ctx context.Context, req *QueryCoreSlotsRequest) (*QueryCoreSlotsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CoreSlots not implemented")
}
func (*UnimplementedQueryServer) ActiveCoreSlots(ctx context.Context, req *QueryActiveCoreSlotsRequest) (*QueryCoreSlotsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActiveCoreSlots not implemented")
}
func (*UnimplementedQueryServer) CoreSlotByOperator(ctx context.Context, req *QueryCoreSlotByOperatorRequest) (*QueryCoreSlotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CoreSlotByOperator not implemented")
}
func (*UnimplementedQueryServer) CoreSlotByConsensusAddress(ctx context.Context, req *QueryCoreSlotByConsensusAddressRequest) (*QueryCoreSlotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CoreSlotByConsensusAddress not implemented")
}
func (*UnimplementedQueryServer) PendingKeyRotations(ctx context.Context, req *QueryPendingKeyRotationsRequest) (*QueryPendingKeyRotationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PendingKeyRotations not implemented")
}
func (*UnimplementedQueryServer) LastAppliedValidators(ctx context.Context, req *QueryLastAppliedValidatorsRequest) (*QueryLastAppliedValidatorsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LastAppliedValidators not implemented")
}
func (*UnimplementedQueryServer) ReservedConsensusAddress(ctx context.Context, req *QueryReservedConsensusAddressRequest) (*QueryReservedConsensusAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReservedConsensusAddress not implemented")
}
func (*UnimplementedQueryServer) RewardWeight(ctx context.Context, req *QueryRewardWeightRequest) (*QueryRewardWeightResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RewardWeight not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nyks.coreslot.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_CoreSlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryCoreSlotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).CoreSlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nyks.coreslot.v1.Query/CoreSlot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).CoreSlot(ctx, req.(*QueryCoreSlotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_CoreSlots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryCoreSlotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).CoreSlots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nyks.coreslot.v1.Query/CoreSlots",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).CoreSlots(ctx, req.(*QueryCoreSlotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ActiveCoreSlots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryActiveCoreSlotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ActiveCoreSlots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nyks.coreslot.v1.Query/ActiveCoreSlots",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ActiveCoreSlots(ctx, req.(*QueryActiveCoreSlotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_CoreSlotByOperator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryCoreSlotByOperatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).CoreSlotByOperator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nyks.coreslot.v1.Query/CoreSlotByOperator",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).CoreSlotByOperator(ctx, req.(*QueryCoreSlotByOperatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_CoreSlotByConsensusAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryCoreSlotByConsensusAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).CoreSlotByConsensusAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nyks.coreslot.v1.Query/CoreSlotByConsensusAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).CoreSlotByConsensusAddress(ctx, req.(*QueryCoreSlotByConsensusAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_PendingKeyRotations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPendingKeyRotationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PendingKeyRotations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nyks.coreslot.v1.Query/PendingKeyRotations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PendingKeyRotations(ctx, req.(*QueryPendingKeyRotationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_LastAppliedValidators_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLastAppliedValidatorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).LastAppliedValidators(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nyks.coreslot.v1.Query/LastAppliedValidators",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).LastAppliedValidators(ctx, req.(*QueryLastAppliedValidatorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ReservedConsensusAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryReservedConsensusAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ReservedConsensusAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nyks.coreslot.v1.Query/ReservedConsensusAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ReservedConsensusAddress(ctx, req.(*QueryReservedConsensusAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_RewardWeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRewardWeightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).RewardWeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nyks.coreslot.v1.Query/RewardWeight",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).RewardWeight(ctx, req.(*QueryRewardWeightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "nyks.coreslot.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "CoreSlot",
			Handler:    _Query_CoreSlot_Handler,
		},
		{
			MethodName: "CoreSlots",
			Handler:    _Query_CoreSlots_Handler,
		},
		{
			MethodName: "ActiveCoreSlots",
			Handler:    _Query_ActiveCoreSlots_Handler,
		},
		{
			MethodName: "CoreSlotByOperator",
			Handler:    _Query_CoreSlotByOperator_Handler,
		},
		{
			MethodName: "CoreSlotByConsensusAddress",
			Handler:    _Query_CoreSlotByConsensusAddress_Handler,
		},
		{
			MethodName: "PendingKeyRotations",
			Handler:    _Query_PendingKeyRotations_Handler,
		},
		{
			MethodName: "LastAppliedValidators",
			Handler:    _Query_LastAppliedValidators_Handler,
		},
		{
			MethodName: "ReservedConsensusAddress",
			Handler:    _Query_ReservedConsensusAddress_Handler,
		},
		{
			MethodName: "RewardWeight",
			Handler:    _Query_RewardWeight_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nyks/coreslot/v1/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Params != nil {
		{
			size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryCoreSlotRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCoreSlotRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCoreSlotRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.SlotId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.SlotId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryCoreSlotByOperatorRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCoreSlotByOperatorRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCoreSlotByOperatorRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.OperatorAddress) > 0 {
		i -= len(m.OperatorAddress)
		copy(dAtA[i:], m.OperatorAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.OperatorAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryCoreSlotByConsensusAddressRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCoreSlotByConsensusAddressRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCoreSlotByConsensusAddressRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ConsensusAddress) > 0 {
		i -= len(m.ConsensusAddress)
		copy(dAtA[i:], m.ConsensusAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ConsensusAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryCoreSlotResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCoreSlotResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCoreSlotResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Slot != nil {
		{
			size, err := m.Slot.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryCoreSlotsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCoreSlotsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCoreSlotsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.Status != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryCoreSlotsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCoreSlotsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCoreSlotsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Slots) > 0 {
		for iNdEx := len(m.Slots) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Slots[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryActiveCoreSlotsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryActiveCoreSlotsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryActiveCoreSlotsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryPendingKeyRotationsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPendingKeyRotationsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPendingKeyRotationsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryPendingKeyRotationsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPendingKeyRotationsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPendingKeyRotationsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Rotations) > 0 {
		for iNdEx := len(m.Rotations) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Rotations[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryLastAppliedValidatorsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryLastAppliedValidatorsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryLastAppliedValidatorsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryLastAppliedValidatorsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryLastAppliedValidatorsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryLastAppliedValidatorsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Validators) > 0 {
		for iNdEx := len(m.Validators) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Validators[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryReservedConsensusAddressRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryReservedConsensusAddressRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryReservedConsensusAddressRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ConsensusAddress) > 0 {
		i -= len(m.ConsensusAddress)
		copy(dAtA[i:], m.ConsensusAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ConsensusAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryReservedConsensusAddressResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryReservedConsensusAddressResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryReservedConsensusAddressResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Reservation != nil {
		{
			size, err := m.Reservation.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryRewardWeightRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRewardWeightRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRewardWeightRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.SlotId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.SlotId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryRewardWeightResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRewardWeightResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRewardWeightResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RewardWeight != nil {
		{
			size, err := m.RewardWeight.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Params != nil {
		l = m.Params.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryCoreSlotRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SlotId != 0 {
		n += 1 + sovQuery(uint64(m.SlotId))
	}
	return n
}

func (m *QueryCoreSlotByOperatorRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.OperatorAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryCoreSlotByConsensusAddressRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ConsensusAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryCoreSlotResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Slot != nil {
		l = m.Slot.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryCoreSlotsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Status != 0 {
		n += 1 + sovQuery(uint64(m.Status))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryCoreSlotsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Slots) > 0 {
		for _, e := range m.Slots {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryActiveCoreSlotsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryPendingKeyRotationsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryPendingKeyRotationsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Rotations) > 0 {
		for _, e := range m.Rotations {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryLastAppliedValidatorsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryLastAppliedValidatorsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Validators) > 0 {
		for _, e := range m.Validators {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryReservedConsensusAddressRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ConsensusAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryReservedConsensusAddressResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Reservation != nil {
		l = m.Reservation.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryRewardWeightRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SlotId != 0 {
		n += 1 + sovQuery(uint64(m.SlotId))
	}
	return n
}

func (m *QueryRewardWeightResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RewardWeight != nil {
		l = m.RewardWeight.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Params == nil {
				m.Params = &Params{}
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryCoreSlotRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCoreSlotRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCoreSlotRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SlotId", wireType)
			}
			m.SlotId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SlotId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryCoreSlotByOperatorRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCoreSlotByOperatorRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCoreSlotByOperatorRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OperatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OperatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryCoreSlotByConsensusAddressRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCoreSlotByConsensusAddressRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCoreSlotByConsensusAddressRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsensusAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ConsensusAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryCoreSlotResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCoreSlotResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCoreSlotResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Slot", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Slot == nil {
				m.Slot = &CoreSlot{}
			}
			if err := m.Slot.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryCoreSlotsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCoreSlotsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCoreSlotsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= SlotStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryCoreSlotsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCoreSlotsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCoreSlotsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Slots", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Slots = append(m.Slots, &CoreSlot{})
			if err := m.Slots[len(m.Slots)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryActiveCoreSlotsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryActiveCoreSlotsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryActiveCoreSlotsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryPendingKeyRotationsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPendingKeyRotationsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPendingKeyRotationsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryPendingKeyRotationsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPendingKeyRotationsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPendingKeyRotationsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rotations", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Rotations = append(m.Rotations, &PendingKeyRotation{})
			if err := m.Rotations[len(m.Rotations)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryLastAppliedValidatorsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryLastAppliedValidatorsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryLastAppliedValidatorsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryLastAppliedValidatorsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryLastAppliedValidatorsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryLastAppliedValidatorsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Validators", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Validators = append(m.Validators, &LastAppliedValidator{})
			if err := m.Validators[len(m.Validators)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryReservedConsensusAddressRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryReservedConsensusAddressRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryReservedConsensusAddressRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsensusAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ConsensusAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryReservedConsensusAddressResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryReservedConsensusAddressResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryReservedConsensusAddressResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reservation", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Reservation == nil {
				m.Reservation = &ReservedConsensusAddress{}
			}
			if err := m.Reservation.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRewardWeightRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRewardWeightRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRewardWeightRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SlotId", wireType)
			}
			m.SlotId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SlotId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRewardWeightResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRewardWeightResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRewardWeightResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardWeight", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.RewardWeight == nil {
				m.RewardWeight = &OperatorRewardWeight{}
			}
			if err := m.RewardWeight.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
