// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: twilight/rewards/v1/params.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Enum numeric values are permanent after release. Future upgrades may add
// values but must not reuse, reorder, or change existing numeric values.
type HalvingMode int32

const (
	HalvingMode_HALVING_MODE_UNSPECIFIED      HalvingMode = 0
	HalvingMode_HALVING_MODE_SUPPLY_THRESHOLD HalvingMode = 1
)

var HalvingMode_name = map[int32]string{
	0: "HALVING_MODE_UNSPECIFIED",
	1: "HALVING_MODE_SUPPLY_THRESHOLD",
}

var HalvingMode_value = map[string]int32{
	"HALVING_MODE_UNSPECIFIED":      0,
	"HALVING_MODE_SUPPLY_THRESHOLD": 1,
}

func (x HalvingMode) String() string {
	return proto.EnumName(HalvingMode_name, int32(x))
}

func (HalvingMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4f0db2239de880b8, []int{0}
}

// Enum numeric values are permanent after release. Future upgrades may add
// values but must not reuse, reorder, or change existing numeric values.
type DistributionMethod int32

const (
	DistributionMethod_DISTRIBUTION_METHOD_UNSPECIFIED            DistributionMethod = 0
	DistributionMethod_DISTRIBUTION_METHOD_UNIFORM_ACTIVE_BLOCKS  DistributionMethod = 1
	DistributionMethod_DISTRIBUTION_METHOD_WEIGHTED_ACTIVE_BLOCKS DistributionMethod = 2
	DistributionMethod_DISTRIBUTION_METHOD_SNAPSHOT_UNIFORM       DistributionMethod = 3
)

var DistributionMethod_name = map[int32]string{
	0: "DISTRIBUTION_METHOD_UNSPECIFIED",
	1: "DISTRIBUTION_METHOD_UNIFORM_ACTIVE_BLOCKS",
	2: "DISTRIBUTION_METHOD_WEIGHTED_ACTIVE_BLOCKS",
	3: "DISTRIBUTION_METHOD_SNAPSHOT_UNIFORM",
}

var DistributionMethod_value = map[string]int32{
	"DISTRIBUTION_METHOD_UNSPECIFIED":            0,
	"DISTRIBUTION_METHOD_UNIFORM_ACTIVE_BLOCKS":  1,
	"DISTRIBUTION_METHOD_WEIGHTED_ACTIVE_BLOCKS": 2,
	"DISTRIBUTION_METHOD_SNAPSHOT_UNIFORM":       3,
}

func (x DistributionMethod) String() string {
	return proto.EnumName(DistributionMethod_name, int32(x))
}

func (DistributionMethod) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4f0db2239de880b8, []int{1}
}

// Enum numeric values are permanent after release. Future upgrades may add
// values but must not reuse, reorder, or change existing numeric values.
type RemainderPolicy int32

const (
	RemainderPolicy_REMAINDER_POLICY_UNSPECIFIED   RemainderPolicy = 0
	RemainderPolicy_REMAINDER_POLICY_CARRY_FORWARD RemainderPolicy = 1
	RemainderPolicy_REMAINDER_POLICY_BURN          RemainderPolicy = 2
)

var RemainderPolicy_name = map[int32]string{
	0: "REMAINDER_POLICY_UNSPECIFIED",
	1: "REMAINDER_POLICY_CARRY_FORWARD",
	2: "REMAINDER_POLICY_BURN",
}

var RemainderPolicy_value = map[string]int32{
	"REMAINDER_POLICY_UNSPECIFIED":   0,
	"REMAINDER_POLICY_CARRY_FORWARD": 1,
	"REMAINDER_POLICY_BURN":          2,
}

func (x RemainderPolicy) String() string {
	return proto.EnumName(RemainderPolicy_name, int32(x))
}

func (RemainderPolicy) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4f0db2239de880b8, []int{2}
}

// Enum numeric values are permanent after release. Future upgrades may add
// values but must not reuse, reorder, or change existing numeric values.
type FeeDistributionMode int32

const (
	FeeDistributionMode_FEE_DISTRIBUTION_MODE_UNSPECIFIED     FeeDistributionMode = 0
	FeeDistributionMode_FEE_DISTRIBUTION_MODE_NONE            FeeDistributionMode = 1
	FeeDistributionMode_FEE_DISTRIBUTION_MODE_ACTIVE_SET_POOL FeeDistributionMode = 2
	FeeDistributionMode_FEE_DISTRIBUTION_MODE_TREASURY_ONLY   FeeDistributionMode = 3
	FeeDistributionMode_FEE_DISTRIBUTION_MODE_BURN            FeeDistributionMode = 4
)

var FeeDistributionMode_name = map[int32]string{
	0: "FEE_DISTRIBUTION_MODE_UNSPECIFIED",
	1: "FEE_DISTRIBUTION_MODE_NONE",
	2: "FEE_DISTRIBUTION_MODE_ACTIVE_SET_POOL",
	3: "FEE_DISTRIBUTION_MODE_TREASURY_ONLY",
	4: "FEE_DISTRIBUTION_MODE_BURN",
}

var FeeDistributionMode_value = map[string]int32{
	"FEE_DISTRIBUTION_MODE_UNSPECIFIED":     0,
	"FEE_DISTRIBUTION_MODE_NONE":            1,
	"FEE_DISTRIBUTION_MODE_ACTIVE_SET_POOL": 2,
	"FEE_DISTRIBUTION_MODE_TREASURY_ONLY":   3,
	"FEE_DISTRIBUTION_MODE_BURN":            4,
}

func (x FeeDistributionMode) String() string {
	return proto.EnumName(FeeDistributionMode_name, int32(x))
}

func (FeeDistributionMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4f0db2239de880b8, []int{3}
}

type Params struct {
	// Fields 2, 3 and 4 were the three independent pause authorities. They are
	// superseded by the single canonical RewardsPauseState and carry no authority:
	// emission follows reward_enabled_blocks (a paused epoch counts zero and so
	// emits zero), epoch finalization is unconditional at the canonical boundary,
	// and monetary release is governed by the canonical release state. They remain
	// on the wire for compatibility and their numbers are never recycled.
	EmissionsEnabled       bool   `protobuf:"varint,2,opt,name=emissions_enabled,json=emissionsEnabled,proto3" json:"emissions_enabled,omitempty"`                     // Deprecated: Do not use.
	EpochSettlementEnabled bool   `protobuf:"varint,3,opt,name=epoch_settlement_enabled,json=epochSettlementEnabled,proto3" json:"epoch_settlement_enabled,omitempty"` // Deprecated: Do not use.
	ClaimsEnabled          bool   `protobuf:"varint,4,opt,name=claims_enabled,json=claimsEnabled,proto3" json:"claims_enabled,omitempty"`                              // Deprecated: Do not use.
	NativeDenom            string `protobuf:"bytes,5,opt,name=native_denom,json=nativeDenom,proto3" json:"native_denom,omitempty"`
	MaxSupply              string `protobuf:"bytes,6,opt,name=max_supply,json=maxSupply,proto3" json:"max_supply,omitempty"`
	InitialBlockSubsidy    string `protobuf:"bytes,7,opt,name=initial_block_subsidy,json=initialBlockSubsidy,proto3" json:"initial_block_subsidy,omitempty"`
	TargetBlockTimeSeconds uint64 `protobuf:"varint,8,opt,name=target_block_time_seconds,json=targetBlockTimeSeconds,proto3" json:"target_block_time_seconds,omitempty"`
	// Superseded by EpochConfigVersion, which is the sole epoch-geometry
	// authority. Retained as genesis/compatibility data only: fresh genesis
	// requires it to agree with the version-1 history entry, and the generic
	// runtime params-update path cannot change it.
	EpochLengthBlocks  uint64             `protobuf:"varint,9,opt,name=epoch_length_blocks,json=epochLengthBlocks,proto3" json:"epoch_length_blocks,omitempty"` // Deprecated: Do not use.
	HalvingMode        HalvingMode        `protobuf:"varint,10,opt,name=halving_mode,json=halvingMode,proto3,enum=twilight.rewards.v1.HalvingMode" json:"halving_mode,omitempty"`
	DistributionMethod DistributionMethod `protobuf:"varint,11,opt,name=distribution_method,json=distributionMethod,proto3,enum=twilight.rewards.v1.DistributionMethod" json:"distribution_method,omitempty"`
	RemainderPolicy    RemainderPolicy    `protobuf:"varint,12,opt,name=remainder_policy,json=remainderPolicy,proto3,enum=twilight.rewards.v1.RemainderPolicy" json:"remainder_policy,omitempty"`
	// Bounded the epoch span of a single claim transaction. The claim path is
	// retired, so this gates nothing; validation still requires it to be nonzero
	// so existing genesis files keep round-tripping. Retained on the wire, and its
	// number is never recycled.
	MaxClaimEpochsPerTx      uint64              `protobuf:"varint,13,opt,name=max_claim_epochs_per_tx,json=maxClaimEpochsPerTx,proto3" json:"max_claim_epochs_per_tx,omitempty"` // Deprecated: Do not use.
	FeeCollectionEnabled     bool                `protobuf:"varint,14,opt,name=fee_collection_enabled,json=feeCollectionEnabled,proto3" json:"fee_collection_enabled,omitempty"`
	FeeDistributionEnabled   bool                `protobuf:"varint,15,opt,name=fee_distribution_enabled,json=feeDistributionEnabled,proto3" json:"fee_distribution_enabled,omitempty"`
	FeeDenom                 string              `protobuf:"bytes,16,opt,name=fee_denom,json=feeDenom,proto3" json:"fee_denom,omitempty"`
	FeeDistributionMode      FeeDistributionMode `protobuf:"varint,17,opt,name=fee_distribution_mode,json=feeDistributionMode,proto3,enum=twilight.rewards.v1.FeeDistributionMode" json:"fee_distribution_mode,omitempty"`
	TreasuryAddress          string              `protobuf:"bytes,18,opt,name=treasury_address,json=treasuryAddress,proto3" json:"treasury_address,omitempty"`
	EmissionTreasuryShareBps uint64              `protobuf:"varint,19,opt,name=emission_treasury_share_bps,json=emissionTreasuryShareBps,proto3" json:"emission_treasury_share_bps,omitempty"`
	FeeTreasuryShareBps      uint64              `protobuf:"varint,20,opt,name=fee_treasury_share_bps,json=feeTreasuryShareBps,proto3" json:"fee_treasury_share_bps,omitempty"`
	WeightedRewardsEnabled   bool                `protobuf:"varint,21,opt,name=weighted_rewards_enabled,json=weightedRewardsEnabled,proto3" json:"weighted_rewards_enabled,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f0db2239de880b8, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

// Deprecated: Do not use.
func (m *Params) GetEmissionsEnabled() bool {
	if m != nil {
		return m.EmissionsEnabled
	}
	return false
}

// Deprecated: Do not use.
func (m *Params) GetEpochSettlementEnabled() bool {
	if m != nil {
		return m.EpochSettlementEnabled
	}
	return false
}

// Deprecated: Do not use.
func (m *Params) GetClaimsEnabled() bool {
	if m != nil {
		return m.ClaimsEnabled
	}
	return false
}

func (m *Params) GetNativeDenom() string {
	if m != nil {
		return m.NativeDenom
	}
	return ""
}

func (m *Params) GetMaxSupply() string {
	if m != nil {
		return m.MaxSupply
	}
	return ""
}

func (m *Params) GetInitialBlockSubsidy() string {
	if m != nil {
		return m.InitialBlockSubsidy
	}
	return ""
}

func (m *Params) GetTargetBlockTimeSeconds() uint64 {
	if m != nil {
		return m.TargetBlockTimeSeconds
	}
	return 0
}

// Deprecated: Do not use.
func (m *Params) GetEpochLengthBlocks() uint64 {
	if m != nil {
		return m.EpochLengthBlocks
	}
	return 0
}

func (m *Params) GetHalvingMode() HalvingMode {
	if m != nil {
		return m.HalvingMode
	}
	return HalvingMode_HALVING_MODE_UNSPECIFIED
}

func (m *Params) GetDistributionMethod() DistributionMethod {
	if m != nil {
		return m.DistributionMethod
	}
	return DistributionMethod_DISTRIBUTION_METHOD_UNSPECIFIED
}

func (m *Params) GetRemainderPolicy() RemainderPolicy {
	if m != nil {
		return m.RemainderPolicy
	}
	return RemainderPolicy_REMAINDER_POLICY_UNSPECIFIED
}

// Deprecated: Do not use.
func (m *Params) GetMaxClaimEpochsPerTx() uint64 {
	if m != nil {
		return m.MaxClaimEpochsPerTx
	}
	return 0
}

func (m *Params) GetFeeCollectionEnabled() bool {
	if m != nil {
		return m.FeeCollectionEnabled
	}
	return false
}

func (m *Params) GetFeeDistributionEnabled() bool {
	if m != nil {
		return m.FeeDistributionEnabled
	}
	return false
}

func (m *Params) GetFeeDenom() string {
	if m != nil {
		return m.FeeDenom
	}
	return ""
}

func (m *Params) GetFeeDistributionMode() FeeDistributionMode {
	if m != nil {
		return m.FeeDistributionMode
	}
	return FeeDistributionMode_FEE_DISTRIBUTION_MODE_UNSPECIFIED
}

func (m *Params) GetTreasuryAddress() string {
	if m != nil {
		return m.TreasuryAddress
	}
	return ""
}

func (m *Params) GetEmissionTreasuryShareBps() uint64 {
	if m != nil {
		return m.EmissionTreasuryShareBps
	}
	return 0
}

func (m *Params) GetFeeTreasuryShareBps() uint64 {
	if m != nil {
		return m.FeeTreasuryShareBps
	}
	return 0
}

func (m *Params) GetWeightedRewardsEnabled() bool {
	if m != nil {
		return m.WeightedRewardsEnabled
	}
	return false
}

type EpochConfigSnapshot struct {
	SnapshotVersion uint64 `protobuf:"varint,1,opt,name=snapshot_version,json=snapshotVersion,proto3" json:"snapshot_version,omitempty"`
	// Deprecated mirror of the canonical epoch length. EpochConfigVersion is the
	// sole epoch-geometry authority; nothing derives a boundary from this value
	// after genesis. It is repopulated from canonical history whenever the
	// snapshot is rebuilt, so the mirror cannot drift from the authority.
	EpochLengthBlocks        uint64              `protobuf:"varint,2,opt,name=epoch_length_blocks,json=epochLengthBlocks,proto3" json:"epoch_length_blocks,omitempty"` // Deprecated: Do not use.
	DistributionMethod       DistributionMethod  `protobuf:"varint,3,opt,name=distribution_method,json=distributionMethod,proto3,enum=twilight.rewards.v1.DistributionMethod" json:"distribution_method,omitempty"`
	RemainderPolicy          RemainderPolicy     `protobuf:"varint,4,opt,name=remainder_policy,json=remainderPolicy,proto3,enum=twilight.rewards.v1.RemainderPolicy" json:"remainder_policy,omitempty"`
	InitialBlockSubsidy      string              `protobuf:"bytes,5,opt,name=initial_block_subsidy,json=initialBlockSubsidy,proto3" json:"initial_block_subsidy,omitempty"`
	HalvingMode              HalvingMode         `protobuf:"varint,6,opt,name=halving_mode,json=halvingMode,proto3,enum=twilight.rewards.v1.HalvingMode" json:"halving_mode,omitempty"`
	WeightedRewardsEnabled   bool                `protobuf:"varint,7,opt,name=weighted_rewards_enabled,json=weightedRewardsEnabled,proto3" json:"weighted_rewards_enabled,omitempty"`
	FeeCollectionEnabled     bool                `protobuf:"varint,8,opt,name=fee_collection_enabled,json=feeCollectionEnabled,proto3" json:"fee_collection_enabled,omitempty"`
	FeeDistributionEnabled   bool                `protobuf:"varint,9,opt,name=fee_distribution_enabled,json=feeDistributionEnabled,proto3" json:"fee_distribution_enabled,omitempty"`
	FeeDenom                 string              `protobuf:"bytes,10,opt,name=fee_denom,json=feeDenom,proto3" json:"fee_denom,omitempty"`
	FeeDistributionMode      FeeDistributionMode `protobuf:"varint,11,opt,name=fee_distribution_mode,json=feeDistributionMode,proto3,enum=twilight.rewards.v1.FeeDistributionMode" json:"fee_distribution_mode,omitempty"`
	TreasuryAddress          string              `protobuf:"bytes,12,opt,name=treasury_address,json=treasuryAddress,proto3" json:"treasury_address,omitempty"`
	EmissionTreasuryShareBps uint64              `protobuf:"varint,13,opt,name=emission_treasury_share_bps,json=emissionTreasuryShareBps,proto3" json:"emission_treasury_share_bps,omitempty"`
	FeeTreasuryShareBps      uint64              `protobuf:"varint,14,opt,name=fee_treasury_share_bps,json=feeTreasuryShareBps,proto3" json:"fee_treasury_share_bps,omitempty"`
}

func (m *EpochConfigSnapshot) Reset()         { *m = EpochConfigSnapshot{} }
func (m *EpochConfigSnapshot) String() string { return proto.CompactTextString(m) }
func (*EpochConfigSnapshot) ProtoMessage()    {}
func (*EpochConfigSnapshot) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f0db2239de880b8, []int{1}
}
func (m *EpochConfigSnapshot) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EpochConfigSnapshot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EpochConfigSnapshot.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EpochConfigSnapshot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EpochConfigSnapshot.Merge(m, src)
}
func (m *EpochConfigSnapshot) XXX_Size() int {
	return m.Size()
}
func (m *EpochConfigSnapshot) XXX_DiscardUnknown() {
	xxx_messageInfo_EpochConfigSnapshot.DiscardUnknown(m)
}

var xxx_messageInfo_EpochConfigSnapshot proto.InternalMessageInfo

func (m *EpochConfigSnapshot) GetSnapshotVersion() uint64 {
	if m != nil {
		return m.SnapshotVersion
	}
	return 0
}

// Deprecated: Do not use.
func (m *EpochConfigSnapshot) GetEpochLengthBlocks() uint64 {
	if m != nil {
		return m.EpochLengthBlocks
	}
	return 0
}

func (m *EpochConfigSnapshot) GetDistributionMethod() DistributionMethod {
	if m != nil {
		return m.DistributionMethod
	}
	return DistributionMethod_DISTRIBUTION_METHOD_UNSPECIFIED
}

func (m *EpochConfigSnapshot) GetRemainderPolicy() RemainderPolicy {
	if m != nil {
		return m.RemainderPolicy
	}
	return RemainderPolicy_REMAINDER_POLICY_UNSPECIFIED
}

func (m *EpochConfigSnapshot) GetInitialBlockSubsidy() string {
	if m != nil {
		return m.InitialBlockSubsidy
	}
	return ""
}

func (m *EpochConfigSnapshot) GetHalvingMode() HalvingMode {
	if m != nil {
		return m.HalvingMode
	}
	return HalvingMode_HALVING_MODE_UNSPECIFIED
}

func (m *EpochConfigSnapshot) GetWeightedRewardsEnabled() bool {
	if m != nil {
		return m.WeightedRewardsEnabled
	}
	return false
}

func (m *EpochConfigSnapshot) GetFeeCollectionEnabled() bool {
	if m != nil {
		return m.FeeCollectionEnabled
	}
	return false
}

func (m *EpochConfigSnapshot) GetFeeDistributionEnabled() bool {
	if m != nil {
		return m.FeeDistributionEnabled
	}
	return false
}

func (m *EpochConfigSnapshot) GetFeeDenom() string {
	if m != nil {
		return m.FeeDenom
	}
	return ""
}

func (m *EpochConfigSnapshot) GetFeeDistributionMode() FeeDistributionMode {
	if m != nil {
		return m.FeeDistributionMode
	}
	return FeeDistributionMode_FEE_DISTRIBUTION_MODE_UNSPECIFIED
}

func (m *EpochConfigSnapshot) GetTreasuryAddress() string {
	if m != nil {
		return m.TreasuryAddress
	}
	return ""
}

func (m *EpochConfigSnapshot) GetEmissionTreasuryShareBps() uint64 {
	if m != nil {
		return m.EmissionTreasuryShareBps
	}
	return 0
}

func (m *EpochConfigSnapshot) GetFeeTreasuryShareBps() uint64 {
	if m != nil {
		return m.FeeTreasuryShareBps
	}
	return 0
}

func init() {
	proto.RegisterEnum("twilight.rewards.v1.HalvingMode", HalvingMode_name, HalvingMode_value)
	proto.RegisterEnum("twilight.rewards.v1.DistributionMethod", DistributionMethod_name, DistributionMethod_value)
	proto.RegisterEnum("twilight.rewards.v1.RemainderPolicy", RemainderPolicy_name, RemainderPolicy_value)
	proto.RegisterEnum("twilight.rewards.v1.FeeDistributionMode", FeeDistributionMode_name, FeeDistributionMode_value)
	proto.RegisterType((*Params)(nil), "twilight.rewards.v1.Params")
	proto.RegisterType((*EpochConfigSnapshot)(nil), "twilight.rewards.v1.EpochConfigSnapshot")
}

func init() { proto.RegisterFile("twilight/rewards/v1/params.proto", fileDescriptor_4f0db2239de880b8) }

var fileDescriptor_4f0db2239de880b8 = []byte{
	// 1060 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x96, 0x4b, 0x6f, 0xdb, 0x46,
	0x10, 0xc7, 0x4d, 0xd9, 0x71, 0xe4, 0xf1, 0x8b, 0x5e, 0xc5, 0x2e, 0xd3, 0x24, 0xaa, 0xec, 0x24,
	0x88, 0x6c, 0x20, 0x12, 0xe2, 0xf4, 0xe0, 0x00, 0xed, 0x41, 0x0f, 0x3a, 0x62, 0x2b, 0x89, 0x02,
	0x49, 0x3b, 0x75, 0x51, 0x60, 0x41, 0x89, 0x6b, 0x89, 0x2d, 0x5f, 0xe0, 0xae, 0x6d, 0xf9, 0x5b,
	0xf4, 0x33, 0xf5, 0xd4, 0xa3, 0x8f, 0x3d, 0xf4, 0x50, 0xd8, 0x1f, 0xa3, 0x97, 0x82, 0x4b, 0x51,
	0x7e, 0x88, 0x32, 0x02, 0x17, 0xb9, 0xd9, 0x33, 0xbf, 0xff, 0x70, 0x77, 0x66, 0xfe, 0x0b, 0x41,
	0x81, 0x9d, 0xd9, 0x8e, 0xdd, 0x1f, 0xb0, 0x72, 0x48, 0xce, 0xcc, 0xd0, 0xa2, 0xe5, 0xd3, 0x77,
	0xe5, 0xc0, 0x0c, 0x4d, 0x97, 0x96, 0x82, 0xd0, 0x67, 0x3e, 0xca, 0x25, 0x44, 0x69, 0x44, 0x94,
	0x4e, 0xdf, 0x6d, 0xfd, 0x9b, 0x85, 0xf9, 0x0e, 0xa7, 0x50, 0x19, 0xd6, 0x88, 0x6b, 0x53, 0x6a,
	0xfb, 0x1e, 0xc5, 0xc4, 0x33, 0xbb, 0x0e, 0xb1, 0xa4, 0x4c, 0x41, 0x28, 0x66, 0xab, 0x19, 0x49,
	0xd0, 0xc4, 0x71, 0x52, 0x8e, 0x73, 0xe8, 0x3b, 0x90, 0x48, 0xe0, 0xf7, 0x06, 0x98, 0x12, 0xc6,
	0x1c, 0xe2, 0x12, 0x8f, 0x8d, 0x75, 0xb3, 0x63, 0xdd, 0x06, 0x67, 0xf4, 0x31, 0x92, 0xa8, 0xb7,
	0x61, 0xa5, 0xe7, 0x98, 0xb6, 0x7b, 0xfd, 0xad, 0xb9, 0xb1, 0x66, 0x39, 0xce, 0x24, 0xe8, 0x26,
	0x2c, 0x79, 0x26, 0xb3, 0x4f, 0x09, 0xb6, 0x88, 0xe7, 0xbb, 0xd2, 0xa3, 0x82, 0x50, 0x5c, 0xd0,
	0x16, 0xe3, 0x58, 0x3d, 0x0a, 0xa1, 0x17, 0x00, 0xae, 0x39, 0xc4, 0xf4, 0x24, 0x08, 0x9c, 0x73,
	0x69, 0x9e, 0x03, 0x0b, 0xae, 0x39, 0xd4, 0x79, 0x00, 0xed, 0xc2, 0xba, 0xed, 0xd9, 0xcc, 0x36,
	0x1d, 0xdc, 0x75, 0xfc, 0xde, 0x6f, 0x98, 0x9e, 0x74, 0xa9, 0x6d, 0x9d, 0x4b, 0x8f, 0x39, 0x99,
	0x1b, 0x25, 0xab, 0x51, 0x4e, 0x8f, 0x53, 0xe8, 0x03, 0x3c, 0x65, 0x66, 0xd8, 0x27, 0x6c, 0x24,
	0x61, 0xb6, 0x4b, 0x30, 0x25, 0x3d, 0xdf, 0xb3, 0xa8, 0x94, 0x2d, 0x08, 0xc5, 0x39, 0x6d, 0x23,
	0x06, 0xb8, 0xcc, 0xb0, 0x5d, 0xa2, 0xc7, 0x59, 0xb4, 0x0b, 0xb9, 0xb8, 0x33, 0x0e, 0xf1, 0xfa,
	0x6c, 0x10, 0x17, 0xa0, 0xd2, 0x42, 0x24, 0xe2, 0x17, 0x5c, 0xe3, 0xe9, 0x26, 0xcf, 0x72, 0x35,
	0x45, 0x35, 0x58, 0x1a, 0x98, 0xce, 0xa9, 0xed, 0xf5, 0xb1, 0xeb, 0x5b, 0x44, 0x82, 0x82, 0x50,
	0x5c, 0xd9, 0x2d, 0x94, 0x52, 0xa6, 0x56, 0x6a, 0xc4, 0x60, 0xcb, 0xb7, 0x88, 0xb6, 0x38, 0xb8,
	0xfe, 0x07, 0xfd, 0x04, 0x39, 0xcb, 0xa6, 0x2c, 0xb4, 0xbb, 0x27, 0xcc, 0xf6, 0x3d, 0xec, 0x12,
	0x36, 0xf0, 0x2d, 0x69, 0x91, 0xd7, 0x7a, 0x93, 0x5a, 0xab, 0x7e, 0x83, 0x6f, 0x71, 0x5c, 0x43,
	0xd6, 0x44, 0x0c, 0xa9, 0x20, 0x86, 0xc4, 0x35, 0x6d, 0xcf, 0x22, 0x21, 0x0e, 0x7c, 0xc7, 0xee,
	0x9d, 0x4b, 0x4b, 0xbc, 0xec, 0xab, 0xd4, 0xb2, 0x5a, 0x02, 0x77, 0x38, 0xab, 0xad, 0x86, 0xb7,
	0x03, 0x68, 0x0f, 0xbe, 0x8a, 0x26, 0xc6, 0x27, 0x8d, 0x79, 0x3b, 0x28, 0x0e, 0x48, 0x88, 0xd9,
	0x50, 0x5a, 0x1e, 0xf7, 0x29, 0xe7, 0x9a, 0xc3, 0x5a, 0x44, 0xc8, 0x1c, 0xe8, 0x90, 0xd0, 0x18,
	0xa2, 0x6f, 0x61, 0xe3, 0x98, 0x10, 0xdc, 0xf3, 0x1d, 0x87, 0xf4, 0xf8, 0x35, 0x93, 0x0d, 0x5a,
	0x89, 0x36, 0x48, 0x7b, 0x72, 0x4c, 0x48, 0x6d, 0x9c, 0x4c, 0x96, 0x68, 0x0f, 0xa4, 0x48, 0x75,
	0xab, 0x3d, 0x89, 0x6e, 0x95, 0xeb, 0xa2, 0xaa, 0x37, 0xbb, 0x91, 0x28, 0x9f, 0xc1, 0x02, 0x57,
	0xf2, 0xdd, 0x13, 0xf9, 0xc2, 0x64, 0x23, 0x94, 0x2f, 0xde, 0x2f, 0xb0, 0x3e, 0x51, 0x96, 0xcf,
	0x6f, 0x8d, 0x37, 0xa7, 0x98, 0xda, 0x9c, 0xfd, 0xdb, 0x1f, 0xe2, 0x73, 0xcc, 0x1d, 0x4f, 0x06,
	0xd1, 0x36, 0x88, 0x2c, 0x24, 0x26, 0x3d, 0x09, 0xcf, 0xb1, 0x69, 0x59, 0x21, 0xa1, 0x54, 0x42,
	0xfc, 0x04, 0xab, 0x49, 0xbc, 0x12, 0x87, 0xd1, 0xf7, 0xf0, 0x2c, 0x71, 0x28, 0x1e, 0x6b, 0xe8,
	0xc0, 0x0c, 0x09, 0xee, 0x06, 0x54, 0xca, 0xf1, 0x85, 0x95, 0x12, 0xc4, 0x18, 0x11, 0x7a, 0x04,
	0x54, 0x03, 0x8a, 0xde, 0xc7, 0x4d, 0x4d, 0x51, 0x3e, 0xe1, 0xca, 0xe8, 0x78, 0x13, 0xa2, 0x3d,
	0x90, 0xce, 0x48, 0x74, 0x39, 0x62, 0xe1, 0xd1, 0xf5, 0xc6, 0x3d, 0x5d, 0x8f, 0x7b, 0x9a, 0xe4,
	0xb5, 0x38, 0x3d, 0xea, 0xe9, 0x0f, 0x73, 0x59, 0x41, 0xcc, 0x6c, 0xfd, 0x3d, 0x0f, 0x39, 0x3e,
	0xd9, 0x9a, 0xef, 0x1d, 0xdb, 0x7d, 0xdd, 0x33, 0x03, 0x3a, 0xf0, 0x59, 0x74, 0x6d, 0x3a, 0xfa,
	0x1b, 0x9f, 0x92, 0x30, 0x3a, 0xb0, 0x24, 0xf0, 0x63, 0xac, 0x26, 0xf1, 0xc3, 0x38, 0x3c, 0xcd,
	0x6a, 0x99, 0xfb, 0xac, 0x36, 0xc5, 0x25, 0xb3, 0x5f, 0xc6, 0x25, 0x73, 0xff, 0xc7, 0x25, 0x53,
	0x1f, 0xae, 0x47, 0xd3, 0x1f, 0xae, 0xbb, 0x2f, 0xc9, 0xfc, 0x43, 0x5e, 0x92, 0xfb, 0x46, 0xfb,
	0xf8, 0xbe, 0xd1, 0xde, 0x63, 0xcf, 0xec, 0x03, 0xed, 0xb9, 0xf0, 0xf9, 0xf6, 0x84, 0xcf, 0xb5,
	0xe7, 0xe2, 0x97, 0xb2, 0xe7, 0xd2, 0x83, 0xec, 0xb9, 0xfc, 0x60, 0x7b, 0xae, 0x4c, 0xb5, 0xe7,
	0x4e, 0x1b, 0x16, 0x6f, 0xcc, 0x17, 0x3d, 0x07, 0xa9, 0x51, 0x69, 0x1e, 0x2a, 0xed, 0x8f, 0xb8,
	0xa5, 0xd6, 0x65, 0x7c, 0xd0, 0xd6, 0x3b, 0x72, 0x4d, 0xd9, 0x57, 0xe4, 0xba, 0x38, 0x83, 0x36,
	0xe1, 0xc5, 0xad, 0xac, 0x7e, 0xd0, 0xe9, 0x34, 0x8f, 0xb0, 0xd1, 0xd0, 0x64, 0xbd, 0xa1, 0x36,
	0xeb, 0xa2, 0xb0, 0xf3, 0x87, 0x00, 0x68, 0xd2, 0x08, 0xe8, 0x25, 0x7c, 0x53, 0x57, 0x74, 0x43,
	0x53, 0xaa, 0x07, 0x86, 0xa2, 0xb6, 0x71, 0x4b, 0x36, 0x1a, 0x6a, 0xfd, 0x4e, 0xf9, 0xb7, 0xb0,
	0x9d, 0x0e, 0x29, 0xfb, 0xaa, 0xd6, 0xc2, 0x95, 0x9a, 0xa1, 0x1c, 0xca, 0xb8, 0xda, 0x54, 0x6b,
	0x3f, 0xea, 0xa2, 0x80, 0x4a, 0xb0, 0x93, 0x86, 0x7f, 0x92, 0x95, 0x8f, 0x0d, 0x43, 0xae, 0xdf,
	0xe1, 0x33, 0xa8, 0x08, 0xaf, 0xd2, 0x78, 0xbd, 0x5d, 0xe9, 0xe8, 0x0d, 0xd5, 0x48, 0xbe, 0x23,
	0xce, 0xee, 0x84, 0xb0, 0x7a, 0xc7, 0x75, 0xa8, 0x00, 0xcf, 0x35, 0xb9, 0x55, 0x51, 0xda, 0x75,
	0x59, 0xc3, 0x1d, 0xb5, 0xa9, 0xd4, 0x8e, 0xee, 0x9c, 0x7e, 0x0b, 0xf2, 0x13, 0x44, 0xad, 0xa2,
	0x69, 0x47, 0x78, 0x5f, 0xd5, 0x3e, 0x55, 0xb4, 0xba, 0x28, 0xa0, 0xa7, 0xb0, 0x3e, 0xc1, 0x54,
	0x0f, 0xb4, 0xb6, 0x98, 0xd9, 0xb9, 0x10, 0x20, 0x97, 0xb2, 0x54, 0xe8, 0x35, 0x6c, 0xee, 0xcb,
	0x32, 0xbe, 0x7d, 0xf2, 0xc9, 0xd1, 0xe4, 0xe1, 0xeb, 0x74, 0xac, 0xad, 0xb6, 0x65, 0x51, 0x40,
	0xdb, 0xf0, 0x3a, 0x3d, 0x3f, 0xea, 0x92, 0x2e, 0x1b, 0xb8, 0xa3, 0xaa, 0x4d, 0x31, 0x83, 0xde,
	0xc0, 0xcb, 0x74, 0xd4, 0xd0, 0xe4, 0x8a, 0x7e, 0xa0, 0x1d, 0x61, 0xb5, 0xdd, 0x3c, 0x12, 0x67,
	0xa7, 0x7f, 0x93, 0x5f, 0x69, 0xae, 0xaa, 0xff, 0x79, 0x99, 0x17, 0x2e, 0x2e, 0xf3, 0xc2, 0x3f,
	0x97, 0x79, 0xe1, 0xf7, 0xab, 0xfc, 0xcc, 0xc5, 0x55, 0x7e, 0xe6, 0xaf, 0xab, 0xfc, 0xcc, 0xcf,
	0x1f, 0xfa, 0x36, 0x1b, 0x9c, 0x74, 0x4b, 0x3d, 0xdf, 0x2d, 0x27, 0xee, 0x7a, 0x1b, 0x84, 0xfe,
	0xaf, 0xa4, 0xc7, 0xae, 0x03, 0x3d, 0x3f, 0x24, 0xe5, 0xe1, 0xf8, 0xc7, 0x2a, 0x3b, 0x0f, 0x08,
	0xed, 0xce, 0xf3, 0x5f, 0xaa, 0xef, 0xff, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xc5, 0x51, 0x79, 0xce,
	0xcd, 0x0a, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.WeightedRewardsEnabled {
		i--
		if m.WeightedRewardsEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xa8
	}
	if m.FeeTreasuryShareBps != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.FeeTreasuryShareBps))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xa0
	}
	if m.EmissionTreasuryShareBps != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.EmissionTreasuryShareBps))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x98
	}
	if len(m.TreasuryAddress) > 0 {
		i -= len(m.TreasuryAddress)
		copy(dAtA[i:], m.TreasuryAddress)
		i = encodeVarintParams(dAtA, i, uint64(len(m.TreasuryAddress)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x92
	}
	if m.FeeDistributionMode != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.FeeDistributionMode))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x88
	}
	if len(m.FeeDenom) > 0 {
		i -= len(m.FeeDenom)
		copy(dAtA[i:], m.FeeDenom)
		i = encodeVarintParams(dAtA, i, uint64(len(m.FeeDenom)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x82
	}
	if m.FeeDistributionEnabled {
		i--
		if m.FeeDistributionEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x78
	}
	if m.FeeCollectionEnabled {
		i--
		if m.FeeCollectionEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x70
	}
	if m.MaxClaimEpochsPerTx != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxClaimEpochsPerTx))
		i--
		dAtA[i] = 0x68
	}
	if m.RemainderPolicy != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.RemainderPolicy))
		i--
		dAtA[i] = 0x60
	}
	if m.DistributionMethod != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.DistributionMethod))
		i--
		dAtA[i] = 0x58
	}
	if m.HalvingMode != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.HalvingMode))
		i--
		dAtA[i] = 0x50
	}
	if m.EpochLengthBlocks != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.EpochLengthBlocks))
		i--
		dAtA[i] = 0x48
	}
	if m.TargetBlockTimeSeconds != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.TargetBlockTimeSeconds))
		i--
		dAtA[i] = 0x40
	}
	if len(m.InitialBlockSubsidy) > 0 {
		i -= len(m.InitialBlockSubsidy)
		copy(dAtA[i:], m.InitialBlockSubsidy)
		i = encodeVarintParams(dAtA, i, uint64(len(m.InitialBlockSubsidy)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.MaxSupply) > 0 {
		i -= len(m.MaxSupply)
		copy(dAtA[i:], m.MaxSupply)
		i = encodeVarintParams(dAtA, i, uint64(len(m.MaxSupply)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.NativeDenom) > 0 {
		i -= len(m.NativeDenom)
		copy(dAtA[i:], m.NativeDenom)
		i = encodeVarintParams(dAtA, i, uint64(len(m.NativeDenom)))
		i--
		dAtA[i] = 0x2a
	}
	if m.ClaimsEnabled {
		i--
		if m.ClaimsEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if m.EpochSettlementEnabled {
		i--
		if m.EpochSettlementEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if m.EmissionsEnabled {
		i--
		if m.EmissionsEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	return len(dAtA) - i, nil
}

func (m *EpochConfigSnapshot) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EpochConfigSnapshot) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EpochConfigSnapshot) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.FeeTreasuryShareBps != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.FeeTreasuryShareBps))
		i--
		dAtA[i] = 0x70
	}
	if m.EmissionTreasuryShareBps != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.EmissionTreasuryShareBps))
		i--
		dAtA[i] = 0x68
	}
	if len(m.TreasuryAddress) > 0 {
		i -= len(m.TreasuryAddress)
		copy(dAtA[i:], m.TreasuryAddress)
		i = encodeVarintParams(dAtA, i, uint64(len(m.TreasuryAddress)))
		i--
		dAtA[i] = 0x62
	}
	if m.FeeDistributionMode != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.FeeDistributionMode))
		i--
		dAtA[i] = 0x58
	}
	if len(m.FeeDenom) > 0 {
		i -= len(m.FeeDenom)
		copy(dAtA[i:], m.FeeDenom)
		i = encodeVarintParams(dAtA, i, uint64(len(m.FeeDenom)))
		i--
		dAtA[i] = 0x52
	}
	if m.FeeDistributionEnabled {
		i--
		if m.FeeDistributionEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x48
	}
	if m.FeeCollectionEnabled {
		i--
		if m.FeeCollectionEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x40
	}
	if m.WeightedRewardsEnabled {
		i--
		if m.WeightedRewardsEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x38
	}
	if m.HalvingMode != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.HalvingMode))
		i--
		dAtA[i] = 0x30
	}
	if len(m.InitialBlockSubsidy) > 0 {
		i -= len(m.InitialBlockSubsidy)
		copy(dAtA[i:], m.InitialBlockSubsidy)
		i = encodeVarintParams(dAtA, i, uint64(len(m.InitialBlockSubsidy)))
		i--
		dAtA[i] = 0x2a
	}
	if m.RemainderPolicy != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.RemainderPolicy))
		i--
		dAtA[i] = 0x20
	}
	if m.DistributionMethod != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.DistributionMethod))
		i--
		dAtA[i] = 0x18
	}
	if m.EpochLengthBlocks != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.EpochLengthBlocks))
		i--
		dAtA[i] = 0x10
	}
	if m.SnapshotVersion != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.SnapshotVersion))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.EmissionsEnabled {
		n += 2
	}
	if m.EpochSettlementEnabled {
		n += 2
	}
	if m.ClaimsEnabled {
		n += 2
	}
	l = len(m.NativeDenom)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.MaxSupply)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.InitialBlockSubsidy)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if m.TargetBlockTimeSeconds != 0 {
		n += 1 + sovParams(uint64(m.TargetBlockTimeSeconds))
	}
	if m.EpochLengthBlocks != 0 {
		n += 1 + sovParams(uint64(m.EpochLengthBlocks))
	}
	if m.HalvingMode != 0 {
		n += 1 + sovParams(uint64(m.HalvingMode))
	}
	if m.DistributionMethod != 0 {
		n += 1 + sovParams(uint64(m.DistributionMethod))
	}
	if m.RemainderPolicy != 0 {
		n += 1 + sovParams(uint64(m.RemainderPolicy))
	}
	if m.MaxClaimEpochsPerTx != 0 {
		n += 1 + sovParams(uint64(m.MaxClaimEpochsPerTx))
	}
	if m.FeeCollectionEnabled {
		n += 2
	}
	if m.FeeDistributionEnabled {
		n += 2
	}
	l = len(m.FeeDenom)
	if l > 0 {
		n += 2 + l + sovParams(uint64(l))
	}
	if m.FeeDistributionMode != 0 {
		n += 2 + sovParams(uint64(m.FeeDistributionMode))
	}
	l = len(m.TreasuryAddress)
	if l > 0 {
		n += 2 + l + sovParams(uint64(l))
	}
	if m.EmissionTreasuryShareBps != 0 {
		n += 2 + sovParams(uint64(m.EmissionTreasuryShareBps))
	}
	if m.FeeTreasuryShareBps != 0 {
		n += 2 + sovParams(uint64(m.FeeTreasuryShareBps))
	}
	if m.WeightedRewardsEnabled {
		n += 3
	}
	return n
}

func (m *EpochConfigSnapshot) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SnapshotVersion != 0 {
		n += 1 + sovParams(uint64(m.SnapshotVersion))
	}
	if m.EpochLengthBlocks != 0 {
		n += 1 + sovParams(uint64(m.EpochLengthBlocks))
	}
	if m.DistributionMethod != 0 {
		n += 1 + sovParams(uint64(m.DistributionMethod))
	}
	if m.RemainderPolicy != 0 {
		n += 1 + sovParams(uint64(m.RemainderPolicy))
	}
	l = len(m.InitialBlockSubsidy)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if m.HalvingMode != 0 {
		n += 1 + sovParams(uint64(m.HalvingMode))
	}
	if m.WeightedRewardsEnabled {
		n += 2
	}
	if m.FeeCollectionEnabled {
		n += 2
	}
	if m.FeeDistributionEnabled {
		n += 2
	}
	l = len(m.FeeDenom)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if m.FeeDistributionMode != 0 {
		n += 1 + sovParams(uint64(m.FeeDistributionMode))
	}
	l = len(m.TreasuryAddress)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if m.EmissionTreasuryShareBps != 0 {
		n += 1 + sovParams(uint64(m.EmissionTreasuryShareBps))
	}
	if m.FeeTreasuryShareBps != 0 {
		n += 1 + sovParams(uint64(m.FeeTreasuryShareBps))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EmissionsEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.EmissionsEnabled = bool(v != 0)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochSettlementEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.EpochSettlementEnabled = bool(v != 0)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClaimsEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.ClaimsEnabled = bool(v != 0)
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NativeDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NativeDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxSupply", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MaxSupply = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InitialBlockSubsidy", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InitialBlockSubsidy = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TargetBlockTimeSeconds", wireType)
			}
			m.TargetBlockTimeSeconds = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TargetBlockTimeSeconds |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochLengthBlocks", wireType)
			}
			m.EpochLengthBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EpochLengthBlocks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HalvingMode", wireType)
			}
			m.HalvingMode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.HalvingMode |= HalvingMode(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DistributionMethod", wireType)
			}
			m.DistributionMethod = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DistributionMethod |= DistributionMethod(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RemainderPolicy", wireType)
			}
			m.RemainderPolicy = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RemainderPolicy |= RemainderPolicy(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxClaimEpochsPerTx", wireType)
			}
			m.MaxClaimEpochsPerTx = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxClaimEpochsPerTx |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeeCollectionEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.FeeCollectionEnabled = bool(v != 0)
		case 15:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeeDistributionEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.FeeDistributionEnabled = bool(v != 0)
		case 16:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeeDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FeeDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 17:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeeDistributionMode", wireType)
			}
			m.FeeDistributionMode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FeeDistributionMode |= FeeDistributionMode(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 18:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TreasuryAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TreasuryAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 19:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EmissionTreasuryShareBps", wireType)
			}
			m.EmissionTreasuryShareBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EmissionTreasuryShareBps |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 20:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeeTreasuryShareBps", wireType)
			}
			m.FeeTreasuryShareBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FeeTreasuryShareBps |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 21:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WeightedRewardsEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.WeightedRewardsEnabled = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EpochConfigSnapshot) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EpochConfigSnapshot: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EpochConfigSnapshot: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SnapshotVersion", wireType)
			}
			m.SnapshotVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SnapshotVersion |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochLengthBlocks", wireType)
			}
			m.EpochLengthBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EpochLengthBlocks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DistributionMethod", wireType)
			}
			m.DistributionMethod = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DistributionMethod |= DistributionMethod(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RemainderPolicy", wireType)
			}
			m.RemainderPolicy = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RemainderPolicy |= RemainderPolicy(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InitialBlockSubsidy", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InitialBlockSubsidy = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HalvingMode", wireType)
			}
			m.HalvingMode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.HalvingMode |= HalvingMode(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WeightedRewardsEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.WeightedRewardsEnabled = bool(v != 0)
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeeCollectionEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.FeeCollectionEnabled = bool(v != 0)
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeeDistributionEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.FeeDistributionEnabled = bool(v != 0)
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeeDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FeeDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeeDistributionMode", wireType)
			}
			m.FeeDistributionMode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FeeDistributionMode |= FeeDistributionMode(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TreasuryAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TreasuryAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EmissionTreasuryShareBps", wireType)
			}
			m.EmissionTreasuryShareBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EmissionTreasuryShareBps |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeeTreasuryShareBps", wireType)
			}
			m.FeeTreasuryShareBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FeeTreasuryShareBps |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
