// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: twilight/rewards/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgClaimRewards struct {
	Signer     string `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer,omitempty"`
	SlotId     uint64 `protobuf:"varint,2,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	StartEpoch uint64 `protobuf:"varint,3,opt,name=start_epoch,json=startEpoch,proto3" json:"start_epoch,omitempty"`
	EndEpoch   uint64 `protobuf:"varint,4,opt,name=end_epoch,json=endEpoch,proto3" json:"end_epoch,omitempty"`
}

func (m *MsgClaimRewards) Reset()         { *m = MsgClaimRewards{} }
func (m *MsgClaimRewards) String() string { return proto.CompactTextString(m) }
func (*MsgClaimRewards) ProtoMessage()    {}
func (*MsgClaimRewards) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb52d868bd0464b8, []int{0}
}
func (m *MsgClaimRewards) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgClaimRewards) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgClaimRewards.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgClaimRewards) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClaimRewards.Merge(m, src)
}
func (m *MsgClaimRewards) XXX_Size() int {
	return m.Size()
}
func (m *MsgClaimRewards) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClaimRewards.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClaimRewards proto.InternalMessageInfo

func (m *MsgClaimRewards) GetSigner() string {
	if m != nil {
		return m.Signer
	}
	return ""
}

func (m *MsgClaimRewards) GetSlotId() uint64 {
	if m != nil {
		return m.SlotId
	}
	return 0
}

func (m *MsgClaimRewards) GetStartEpoch() uint64 {
	if m != nil {
		return m.StartEpoch
	}
	return 0
}

func (m *MsgClaimRewards) GetEndEpoch() uint64 {
	if m != nil {
		return m.EndEpoch
	}
	return 0
}

type MsgClaimRewardsResponse struct {
}

func (m *MsgClaimRewardsResponse) Reset()         { *m = MsgClaimRewardsResponse{} }
func (m *MsgClaimRewardsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgClaimRewardsResponse) ProtoMessage()    {}
func (*MsgClaimRewardsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb52d868bd0464b8, []int{1}
}
func (m *MsgClaimRewardsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgClaimRewardsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgClaimRewardsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgClaimRewardsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClaimRewardsResponse.Merge(m, src)
}
func (m *MsgClaimRewardsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgClaimRewardsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClaimRewardsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClaimRewardsResponse proto.InternalMessageInfo

type MsgUpdateRewardsParams struct {
	Authority string  `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	Params    *Params `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
}

func (m *MsgUpdateRewardsParams) Reset()         { *m = MsgUpdateRewardsParams{} }
func (m *MsgUpdateRewardsParams) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateRewardsParams) ProtoMessage()    {}
func (*MsgUpdateRewardsParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb52d868bd0464b8, []int{2}
}
func (m *MsgUpdateRewardsParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateRewardsParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateRewardsParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateRewardsParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateRewardsParams.Merge(m, src)
}
func (m *MsgUpdateRewardsParams) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateRewardsParams) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateRewardsParams.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateRewardsParams proto.InternalMessageInfo

func (m *MsgUpdateRewardsParams) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdateRewardsParams) GetParams() *Params {
	if m != nil {
		return m.Params
	}
	return nil
}

type MsgUpdateRewardsParamsResponse struct {
}

func (m *MsgUpdateRewardsParamsResponse) Reset()         { *m = MsgUpdateRewardsParamsResponse{} }
func (m *MsgUpdateRewardsParamsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateRewardsParamsResponse) ProtoMessage()    {}
func (*MsgUpdateRewardsParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb52d868bd0464b8, []int{3}
}
func (m *MsgUpdateRewardsParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateRewardsParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateRewardsParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateRewardsParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateRewardsParamsResponse.Merge(m, src)
}
func (m *MsgUpdateRewardsParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateRewardsParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateRewardsParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateRewardsParamsResponse proto.InternalMessageInfo

type MsgPauseRewards struct {
	EmergencyAuthority string `protobuf:"bytes,1,opt,name=emergency_authority,json=emergencyAuthority,proto3" json:"emergency_authority,omitempty"`
	// The three selectors are superseded by the single canonical pause state.
	// A pause is global: it is scheduled for H+1 and governs reward accrual and
	// monetary release together. The fields remain on the wire for compatibility,
	// carry no partial-pause semantics, and their numbers are never recycled.
	PauseEmissions       bool `protobuf:"varint,2,opt,name=pause_emissions,json=pauseEmissions,proto3" json:"pause_emissions,omitempty"`                     // Deprecated: Do not use.
	PauseEpochSettlement bool `protobuf:"varint,3,opt,name=pause_epoch_settlement,json=pauseEpochSettlement,proto3" json:"pause_epoch_settlement,omitempty"` // Deprecated: Do not use.
	PauseClaims          bool `protobuf:"varint,4,opt,name=pause_claims,json=pauseClaims,proto3" json:"pause_claims,omitempty"`                              // Deprecated: Do not use.
}

func (m *MsgPauseRewards) Reset()         { *m = MsgPauseRewards{} }
func (m *MsgPauseRewards) String() string { return proto.CompactTextString(m) }
func (*MsgPauseRewards) ProtoMessage()    {}
func (*MsgPauseRewards) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb52d868bd0464b8, []int{4}
}
func (m *MsgPauseRewards) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgPauseRewards) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgPauseRewards.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgPauseRewards) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgPauseRewards.Merge(m, src)
}
func (m *MsgPauseRewards) XXX_Size() int {
	return m.Size()
}
func (m *MsgPauseRewards) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgPauseRewards.DiscardUnknown(m)
}

var xxx_messageInfo_MsgPauseRewards proto.InternalMessageInfo

func (m *MsgPauseRewards) GetEmergencyAuthority() string {
	if m != nil {
		return m.EmergencyAuthority
	}
	return ""
}

// Deprecated: Do not use.
func (m *MsgPauseRewards) GetPauseEmissions() bool {
	if m != nil {
		return m.PauseEmissions
	}
	return false
}

// Deprecated: Do not use.
func (m *MsgPauseRewards) GetPauseEpochSettlement() bool {
	if m != nil {
		return m.PauseEpochSettlement
	}
	return false
}

// Deprecated: Do not use.
func (m *MsgPauseRewards) GetPauseClaims() bool {
	if m != nil {
		return m.PauseClaims
	}
	return false
}

type MsgPauseRewardsResponse struct {
}

func (m *MsgPauseRewardsResponse) Reset()         { *m = MsgPauseRewardsResponse{} }
func (m *MsgPauseRewardsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgPauseRewardsResponse) ProtoMessage()    {}
func (*MsgPauseRewardsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb52d868bd0464b8, []int{5}
}
func (m *MsgPauseRewardsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgPauseRewardsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgPauseRewardsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgPauseRewardsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgPauseRewardsResponse.Merge(m, src)
}
func (m *MsgPauseRewardsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgPauseRewardsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgPauseRewardsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgPauseRewardsResponse proto.InternalMessageInfo

type MsgResumeRewards struct {
	EmergencyAuthority string `protobuf:"bytes,1,opt,name=emergency_authority,json=emergencyAuthority,proto3" json:"emergency_authority,omitempty"`
	// Superseded exactly as for MsgPauseRewards above.
	ResumeEmissions       bool `protobuf:"varint,2,opt,name=resume_emissions,json=resumeEmissions,proto3" json:"resume_emissions,omitempty"`                     // Deprecated: Do not use.
	ResumeEpochSettlement bool `protobuf:"varint,3,opt,name=resume_epoch_settlement,json=resumeEpochSettlement,proto3" json:"resume_epoch_settlement,omitempty"` // Deprecated: Do not use.
	ResumeClaims          bool `protobuf:"varint,4,opt,name=resume_claims,json=resumeClaims,proto3" json:"resume_claims,omitempty"`                              // Deprecated: Do not use.
}

func (m *MsgResumeRewards) Reset()         { *m = MsgResumeRewards{} }
func (m *MsgResumeRewards) String() string { return proto.CompactTextString(m) }
func (*MsgResumeRewards) ProtoMessage()    {}
func (*MsgResumeRewards) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb52d868bd0464b8, []int{6}
}
func (m *MsgResumeRewards) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgResumeRewards) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgResumeRewards.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgResumeRewards) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgResumeRewards.Merge(m, src)
}
func (m *MsgResumeRewards) XXX_Size() int {
	return m.Size()
}
func (m *MsgResumeRewards) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgResumeRewards.DiscardUnknown(m)
}

var xxx_messageInfo_MsgResumeRewards proto.InternalMessageInfo

func (m *MsgResumeRewards) GetEmergencyAuthority() string {
	if m != nil {
		return m.EmergencyAuthority
	}
	return ""
}

// Deprecated: Do not use.
func (m *MsgResumeRewards) GetResumeEmissions() bool {
	if m != nil {
		return m.ResumeEmissions
	}
	return false
}

// Deprecated: Do not use.
func (m *MsgResumeRewards) GetResumeEpochSettlement() bool {
	if m != nil {
		return m.ResumeEpochSettlement
	}
	return false
}

// Deprecated: Do not use.
func (m *MsgResumeRewards) GetResumeClaims() bool {
	if m != nil {
		return m.ResumeClaims
	}
	return false
}

type MsgResumeRewardsResponse struct {
}

func (m *MsgResumeRewardsResponse) Reset()         { *m = MsgResumeRewardsResponse{} }
func (m *MsgResumeRewardsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgResumeRewardsResponse) ProtoMessage()    {}
func (*MsgResumeRewardsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb52d868bd0464b8, []int{7}
}
func (m *MsgResumeRewardsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgResumeRewardsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgResumeRewardsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgResumeRewardsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgResumeRewardsResponse.Merge(m, src)
}
func (m *MsgResumeRewardsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgResumeRewardsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgResumeRewardsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgResumeRewardsResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgClaimRewards)(nil), "twilight.rewards.v1.MsgClaimRewards")
	proto.RegisterType((*MsgClaimRewardsResponse)(nil), "twilight.rewards.v1.MsgClaimRewardsResponse")
	proto.RegisterType((*MsgUpdateRewardsParams)(nil), "twilight.rewards.v1.MsgUpdateRewardsParams")
	proto.RegisterType((*MsgUpdateRewardsParamsResponse)(nil), "twilight.rewards.v1.MsgUpdateRewardsParamsResponse")
	proto.RegisterType((*MsgPauseRewards)(nil), "twilight.rewards.v1.MsgPauseRewards")
	proto.RegisterType((*MsgPauseRewardsResponse)(nil), "twilight.rewards.v1.MsgPauseRewardsResponse")
	proto.RegisterType((*MsgResumeRewards)(nil), "twilight.rewards.v1.MsgResumeRewards")
	proto.RegisterType((*MsgResumeRewardsResponse)(nil), "twilight.rewards.v1.MsgResumeRewardsResponse")
}

func init() { proto.RegisterFile("twilight/rewards/v1/tx.proto", fileDescriptor_fb52d868bd0464b8) }

var fileDescriptor_fb52d868bd0464b8 = []byte{
	// 652 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0xbf, 0x6f, 0xd3, 0x40,
	0x14, 0xae, 0xd3, 0x12, 0xda, 0xd7, 0x94, 0x96, 0x2b, 0x34, 0xc1, 0xad, 0x4c, 0x88, 0xa8, 0x5a,
	0xb5, 0x34, 0xa6, 0xed, 0x02, 0x91, 0x40, 0xa2, 0xa8, 0x03, 0x43, 0xa4, 0xca, 0x15, 0x0b, 0x4b,
	0xe4, 0xd8, 0x27, 0xc7, 0x28, 0xf6, 0x59, 0xbe, 0x4b, 0x7f, 0x6c, 0x88, 0x91, 0x05, 0x36, 0xfe,
	0x04, 0xd6, 0x0a, 0xf1, 0x47, 0x30, 0x76, 0x64, 0x44, 0xed, 0xd0, 0x7f, 0x03, 0xf9, 0xee, 0xec,
	0x24, 0xee, 0x19, 0x15, 0x96, 0x48, 0xf7, 0xbe, 0xef, 0xbd, 0x7b, 0xdf, 0xf7, 0xde, 0xc5, 0xb0,
	0xc2, 0x8e, 0xfd, 0xbe, 0xef, 0xf5, 0x98, 0x19, 0xe3, 0x63, 0x3b, 0x76, 0xa9, 0x79, 0xb4, 0x6d,
	0xb2, 0x93, 0x66, 0x14, 0x13, 0x46, 0xd0, 0x62, 0x8a, 0x36, 0x25, 0xda, 0x3c, 0xda, 0xd6, 0xef,
	0xda, 0x81, 0x1f, 0x12, 0x93, 0xff, 0x0a, 0x9e, 0x5e, 0x75, 0x08, 0x0d, 0x08, 0x35, 0x03, 0xea,
	0x25, 0xf9, 0x01, 0xf5, 0x24, 0x50, 0x57, 0x95, 0x8f, 0xec, 0xd8, 0x0e, 0xa8, 0x60, 0x34, 0xbe,
	0x6b, 0x30, 0xdf, 0xa6, 0xde, 0xeb, 0xbe, 0xed, 0x07, 0x96, 0xe0, 0xa0, 0x25, 0x28, 0x53, 0xdf,
	0x0b, 0x71, 0x5c, 0xd3, 0xea, 0xda, 0xfa, 0x8c, 0x25, 0x4f, 0xa8, 0x0a, 0xb7, 0x69, 0x9f, 0xb0,
	0x8e, 0xef, 0xd6, 0x4a, 0x75, 0x6d, 0x7d, 0xca, 0x2a, 0x27, 0xc7, 0x37, 0x2e, 0x7a, 0x08, 0xb3,
	0x94, 0xd9, 0x31, 0xeb, 0xe0, 0x88, 0x38, 0xbd, 0xda, 0x24, 0x07, 0x81, 0x87, 0xf6, 0x93, 0x08,
	0x5a, 0x86, 0x19, 0x1c, 0xba, 0x12, 0x9e, 0xe2, 0xf0, 0x34, 0x0e, 0x5d, 0x0e, 0xb6, 0x9e, 0x7e,
	0xbc, 0x3a, 0xdb, 0x90, 0x77, 0x7c, 0xba, 0x3a, 0xdb, 0xb8, 0xde, 0x74, 0xae, 0xc1, 0xc6, 0x03,
	0xa8, 0xe6, 0x42, 0x16, 0xa6, 0x11, 0x09, 0x29, 0x6e, 0x7c, 0xd3, 0x60, 0xa9, 0x4d, 0xbd, 0xb7,
	0x91, 0x6b, 0x33, 0x2c, 0xc1, 0x03, 0x2e, 0x18, 0xad, 0xc0, 0x8c, 0x3d, 0x60, 0x3d, 0x12, 0xfb,
	0xec, 0x54, 0x2a, 0x1b, 0x06, 0xd0, 0x2e, 0x94, 0x85, 0x31, 0x5c, 0xdb, 0xec, 0xce, 0x72, 0x53,
	0x61, 0x7e, 0x53, 0x94, 0xb2, 0x24, 0xb5, 0xd5, 0x4a, 0x5a, 0x1f, 0x16, 0x49, 0xba, 0x5f, 0x53,
	0x75, 0xaf, 0x68, 0xa7, 0x51, 0x07, 0x43, 0x8d, 0x64, 0x5a, 0x3e, 0x97, 0xf8, 0x6c, 0x0e, 0xec,
	0x01, 0x4d, 0x19, 0xc8, 0x84, 0x45, 0x1c, 0xe0, 0xd8, 0xc3, 0xa1, 0x73, 0xda, 0xc9, 0xcb, 0x41,
	0x19, 0xf4, 0x2a, 0xd3, 0xb5, 0x09, 0xf3, 0x51, 0x52, 0xa0, 0x83, 0x03, 0x9f, 0x52, 0x9f, 0x84,
	0x42, 0xe0, 0xf4, 0x5e, 0xa9, 0xa6, 0x59, 0x77, 0x38, 0xb4, 0x9f, 0x22, 0xe8, 0x19, 0x2c, 0x49,
	0x72, 0x32, 0x99, 0x0e, 0xc5, 0x8c, 0xf5, 0x71, 0x80, 0x43, 0xc6, 0x67, 0x2a, 0x72, 0xee, 0x89,
	0x9c, 0x84, 0x70, 0x98, 0xe1, 0x68, 0x15, 0x2a, 0x22, 0xd3, 0x49, 0xa6, 0x42, 0xf9, 0x90, 0x05,
	0x7f, 0x96, 0xc7, 0xf9, 0xb0, 0x68, 0xeb, 0x45, 0x62, 0x98, 0x4a, 0x41, 0xe1, 0xe0, 0x47, 0xd5,
	0xcb, 0xc1, 0x8f, 0x86, 0x32, 0xb3, 0xbe, 0x96, 0x60, 0xa1, 0x4d, 0x3d, 0x0b, 0xd3, 0x41, 0xf0,
	0xff, 0x6e, 0x6d, 0xc1, 0x42, 0xcc, 0x2b, 0x28, 0xed, 0x9a, 0x17, 0xd8, 0xd0, 0xaf, 0x16, 0x54,
	0x53, 0x7a, 0xb1, 0x61, 0xf7, 0x65, 0x56, 0xce, 0xb1, 0x35, 0x98, 0x93, 0xb9, 0xd7, 0x2c, 0xab,
	0x08, 0x40, 0x7a, 0xf6, 0xf2, 0x6f, 0x9e, 0x3d, 0x52, 0x79, 0x36, 0x66, 0x42, 0x43, 0x87, 0x5a,
	0x3e, 0x96, 0xba, 0xb6, 0xf3, 0x63, 0x12, 0x26, 0xdb, 0xd4, 0x43, 0x5d, 0xa8, 0x8c, 0xfd, 0x05,
	0x3c, 0x56, 0x6e, 0x7f, 0xee, 0xd1, 0xe9, 0x4f, 0x6e, 0xc2, 0x4a, 0xef, 0x42, 0xc7, 0xb0, 0xa8,
	0x7a, 0x96, 0x9b, 0x45, 0x45, 0x14, 0x64, 0x7d, 0xf7, 0x1f, 0xc8, 0xd9, 0xc5, 0x5d, 0xa8, 0x8c,
	0xbd, 0xa1, 0x42, 0x71, 0xa3, 0xac, 0x62, 0x71, 0xaa, 0xf5, 0x43, 0x18, 0xe6, 0xc6, 0x57, 0x6f,
	0xb5, 0x28, 0x7d, 0x8c, 0xa6, 0x6f, 0xdd, 0x88, 0x96, 0x5e, 0xa3, 0xdf, 0xfa, 0x70, 0x75, 0xb6,
	0xa1, 0xed, 0x1d, 0xfe, 0xbc, 0x30, 0xb4, 0xf3, 0x0b, 0x43, 0xfb, 0x7d, 0x61, 0x68, 0x5f, 0x2e,
	0x8d, 0x89, 0xf3, 0x4b, 0x63, 0xe2, 0xd7, 0xa5, 0x31, 0xf1, 0xee, 0xb9, 0xe7, 0xb3, 0xde, 0xa0,
	0xdb, 0x74, 0x48, 0x60, 0xa6, 0x95, 0xb7, 0xa2, 0x98, 0xbc, 0xc7, 0x0e, 0x1b, 0x06, 0x1c, 0x12,
	0x63, 0xf3, 0x24, 0x5b, 0x19, 0x76, 0x1a, 0x61, 0xda, 0x2d, 0xf3, 0x2f, 0xc2, 0xee, 0x9f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xa2, 0xe5, 0x6b, 0xab, 0x94, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	ClaimRewards(ctx context.Context, in *MsgClaimRewards, opts ...grpc.CallOption) (*MsgClaimRewardsResponse, error)
	UpdateRewardsParams(ctx context.Context, in *MsgUpdateRewardsParams, opts ...grpc.CallOption) (*MsgUpdateRewardsParamsResponse, error)
	PauseRewards(ctx context.Context, in *MsgPauseRewards, opts ...grpc.CallOption) (*MsgPauseRewardsResponse, error)
	ResumeRewards(ctx context.Context, in *MsgResumeRewards, opts ...grpc.CallOption) (*MsgResumeRewardsResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) ClaimRewards(ctx context.Context, in *MsgClaimRewards, opts ...grpc.CallOption) (*MsgClaimRewardsResponse, error) {
	out := new(MsgClaimRewardsResponse)
	err := c.cc.Invoke(ctx, "/twilight.rewards.v1.Msg/ClaimRewards", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateRewardsParams(ctx context.Context, in *MsgUpdateRewardsParams, opts ...grpc.CallOption) (*MsgUpdateRewardsParamsResponse, error) {
	out := new(MsgUpdateRewardsParamsResponse)
	err := c.cc.Invoke(ctx, "/twilight.rewards.v1.Msg/UpdateRewardsParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) PauseRewards(ctx context.Context, in *MsgPauseRewards, opts ...grpc.CallOption) (*MsgPauseRewardsResponse, error) {
	out := new(MsgPauseRewardsResponse)
	err := c.cc.Invoke(ctx, "/twilight.rewards.v1.Msg/PauseRewards", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ResumeRewards(ctx context.Context, in *MsgResumeRewards, opts ...grpc.CallOption) (*MsgResumeRewardsResponse, error) {
	out := new(MsgResumeRewardsResponse)
	err := c.cc.Invoke(ctx, "/twilight.rewards.v1.Msg/ResumeRewards", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	ClaimRewards(context.Context, *MsgClaimRewards) (*MsgClaimRewardsResponse, error)
	UpdateRewardsParams(context.Context, *MsgUpdateRewardsParams) (*MsgUpdateRewardsParamsResponse, error)
	PauseRewards(context.Context, *MsgPauseRewards) (*MsgPauseRewardsResponse, error)
	ResumeRewards(context.Context, *MsgResumeRewards) (*MsgResumeRewardsResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) ClaimRewards(ctx context.Context, req *MsgClaimRewards) (*MsgClaimRewardsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClaimRewards not implemented")
}
func (*UnimplementedMsgServer) UpdateRewardsParams(ctx context.Context, req *MsgUpdateRewardsParams) (*MsgUpdateRewardsParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRewardsParams not implemented")
}
func (*UnimplementedMsgServer) PauseRewards(ctx context.Context, req *MsgPauseRewards) (*MsgPauseRewardsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PauseRewards not implemented")
}
func (*UnimplementedMsgServer) ResumeRewards(ctx context.Context, req *MsgResumeRewards) (*MsgResumeRewardsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResumeRewards not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_ClaimRewards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgClaimRewards)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ClaimRewards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/twilight.rewards.v1.Msg/ClaimRewards",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ClaimRewards(ctx, req.(*MsgClaimRewards))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateRewardsParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateRewardsParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateRewardsParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/twilight.rewards.v1.Msg/UpdateRewardsParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateRewardsParams(ctx, req.(*MsgUpdateRewardsParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_PauseRewards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgPauseRewards)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).PauseRewards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/twilight.rewards.v1.Msg/PauseRewards",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).PauseRewards(ctx, req.(*MsgPauseRewards))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ResumeRewards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgResumeRewards)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ResumeRewards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/twilight.rewards.v1.Msg/ResumeRewards",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ResumeRewards(ctx, req.(*MsgResumeRewards))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "twilight.rewards.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ClaimRewards",
			Handler:    _Msg_ClaimRewards_Handler,
		},
		{
			MethodName: "UpdateRewardsParams",
			Handler:    _Msg_UpdateRewardsParams_Handler,
		},
		{
			MethodName: "PauseRewards",
			Handler:    _Msg_PauseRewards_Handler,
		},
		{
			MethodName: "ResumeRewards",
			Handler:    _Msg_ResumeRewards_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "twilight/rewards/v1/tx.proto",
}

func (m *MsgClaimRewards) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgClaimRewards) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgClaimRewards) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.EndEpoch != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.EndEpoch))
		i--
		dAtA[i] = 0x20
	}
	if m.StartEpoch != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.StartEpoch))
		i--
		dAtA[i] = 0x18
	}
	if m.SlotId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.SlotId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgClaimRewardsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgClaimRewardsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgClaimRewardsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUpdateRewardsParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateRewardsParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateRewardsParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Params != nil {
		{
			size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateRewardsParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateRewardsParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateRewardsParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgPauseRewards) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgPauseRewards) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgPauseRewards) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PauseClaims {
		i--
		if m.PauseClaims {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if m.PauseEpochSettlement {
		i--
		if m.PauseEpochSettlement {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if m.PauseEmissions {
		i--
		if m.PauseEmissions {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if len(m.EmergencyAuthority) > 0 {
		i -= len(m.EmergencyAuthority)
		copy(dAtA[i:], m.EmergencyAuthority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.EmergencyAuthority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgPauseRewardsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgPauseRewardsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgPauseRewardsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgResumeRewards) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgResumeRewards) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgResumeRewards) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ResumeClaims {
		i--
		if m.ResumeClaims {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if m.ResumeEpochSettlement {
		i--
		if m.ResumeEpochSettlement {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if m.ResumeEmissions {
		i--
		if m.ResumeEmissions {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if len(m.EmergencyAuthority) > 0 {
		i -= len(m.EmergencyAuthority)
		copy(dAtA[i:], m.EmergencyAuthority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.EmergencyAuthority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgResumeRewardsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgResumeRewardsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgResumeRewardsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgClaimRewards) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.SlotId != 0 {
		n += 1 + sovTx(uint64(m.SlotId))
	}
	if m.StartEpoch != 0 {
		n += 1 + sovTx(uint64(m.StartEpoch))
	}
	if m.EndEpoch != 0 {
		n += 1 + sovTx(uint64(m.EndEpoch))
	}
	return n
}

func (m *MsgClaimRewardsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUpdateRewardsParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Params != nil {
		l = m.Params.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgUpdateRewardsParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgPauseRewards) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.EmergencyAuthority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.PauseEmissions {
		n += 2
	}
	if m.PauseEpochSettlement {
		n += 2
	}
	if m.PauseClaims {
		n += 2
	}
	return n
}

func (m *MsgPauseRewardsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgResumeRewards) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.EmergencyAuthority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.ResumeEmissions {
		n += 2
	}
	if m.ResumeEpochSettlement {
		n += 2
	}
	if m.ResumeClaims {
		n += 2
	}
	return n
}

func (m *MsgResumeRewardsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgClaimRewards) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgClaimRewards: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgClaimRewards: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SlotId", wireType)
			}
			m.SlotId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SlotId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartEpoch", wireType)
			}
			m.StartEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartEpoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndEpoch", wireType)
			}
			m.EndEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EndEpoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgClaimRewardsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgClaimRewardsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgClaimRewardsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateRewardsParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateRewardsParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateRewardsParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Params == nil {
				m.Params = &Params{}
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateRewardsParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateRewardsParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateRewardsParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgPauseRewards) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgPauseRewards: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgPauseRewards: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EmergencyAuthority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EmergencyAuthority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PauseEmissions", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.PauseEmissions = bool(v != 0)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PauseEpochSettlement", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.PauseEpochSettlement = bool(v != 0)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PauseClaims", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.PauseClaims = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgPauseRewardsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgPauseRewardsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgPauseRewardsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgResumeRewards) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgResumeRewards: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgResumeRewards: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EmergencyAuthority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EmergencyAuthority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResumeEmissions", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.ResumeEmissions = bool(v != 0)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResumeEpochSettlement", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.ResumeEpochSettlement = bool(v != 0)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResumeClaims", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.ResumeClaims = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgResumeRewardsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgResumeRewardsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgResumeRewardsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
