#!/usr/bin/env bash
# Shared helpers for the CoreSlot operational drills (lifecycle-e2e,
# restart-rotation, quorum-drill). Sourced, not executed.
#
# Design notes:
#  - Drills drive the chain with REAL `twilightd coreslot ...` transactions signed by
#    the localnet authority (operator0) / emergency authority (operator1) keys
#    generated by scripts/localnet/init.sh. No in-app scenario hook is used.
#  - Authority-gated msgs are signed by operator0 (the configured normal
#    authority); MsgSuspendCoreSlot is signed by operator1 (emergency authority).
#  - Fees are zero (min-gas 0utwlt); both authority accounts are funded in
#    genesis so they have an on-chain account/sequence to sign with.
#  - tx results are read from the DeliverTx/FinalizeBlock result via the RPC
#    /tx?hash endpoint (kv indexer is on by default), not just CheckTx.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
BIN="${BIN:-$ROOT/build/twilightd}"
NET="${TWILIGHT_LOCALNET_HOME:-/tmp/twilight-localnet}"
CHAIN_ID="${CHAIN_ID:-twilight-localnet-1}"
export CHAIN_ID
NODE_COUNT="${NODE_COUNT:-4}"
KEYRING="--keyring-backend test"
DRILL="${DRILL:-drill}"
RUN_ID="${RUN_ID:-$(date -u +%Y%m%d-%H%M%S)-$$}"
export RUN_ID
EVID_ROOT="$ROOT/build/localnet/evidence/$RUN_ID"
EVID_DIR="$EVID_ROOT/$DRILL"

need() { command -v "$1" >/dev/null 2>&1 || { echo "missing required command: $1" >&2; exit 2; }; }
need curl
need jq

rpc_port() { echo $((26657 + $1 * 100)); }
rpc_url() { echo "tcp://127.0.0.1:$(rpc_port "$1")"; }
http_url() { echo "http://127.0.0.1:$(rpc_port "$1")"; }
node_home() { echo "$NET/node$1"; }

rpc_get() { curl -fsS "$(http_url "$1")$2"; }

authority_addr() { sed -n 's/.*"address":"\([^"]*\)".*/\1/p' "$NET/operator0.json" | head -1; }
emergency_addr() { sed -n 's/.*"address":"\([^"]*\)".*/\1/p' "$NET/operator1.json" | head -1; }

# ---- node lifecycle (per-node start/stop) ----------------------------------

stop_node() {
  local i="$1"
  if [[ -f "$NET/node$i.pid" ]]; then
    kill "$(cat "$NET/node$i.pid")" 2>/dev/null || true
    rm -f "$NET/node$i.pid"
  fi
}

# node_bin <index> — the binary this node runs.
#
# Defaults to $BIN, so ordinary localnet behaviour is unchanged when nothing is
# set. Exporting NODE_BIN_<index> overrides one node, which is what makes a
# partial binary rollout expressible: the upgrade drill runs nodes 0-2 on the new
# build while node 3 stays on the old one, and that asymmetry is the whole point
# of the exercise.
node_bin() {
  local var="NODE_BIN_$1"
  echo "${!var:-$BIN}"
}

start_node() {
  local i="$1" bin
  bin="$(node_bin "$i")"
  "$bin" start --home "$(node_home "$i")" --minimum-gas-prices 0utwlt --log_no_color >>"$NET/logs/node$i.log" 2>&1 &
  echo "$!" >"$NET/node$i.pid"
}

# node_alive <index> — true while the node's recorded process is still running.
#
# Liveness is NOT the same as progress, and at an upgrade boundary the two come
# apart: x/upgrade returns an error from PreBlock, CometBFT panics its consensus
# routine, and the process stays UP — often still serving RPC — with consensus
# stopped. So a halted node commonly reads as alive here. Use this to tell an
# expected halt from a process that actually died; use the committed application
# height to tell whether the chain is making progress.
node_alive() {
  local i="$1" pidfile="$NET/node$1.pid"
  [[ -f "$pidfile" ]] || return 1
  kill -0 "$(cat "$pidfile")" 2>/dev/null
}

setup_localnet() {
  mkdir -p "$EVID_DIR"
  "$ROOT/scripts/localnet/init.sh"
  "$ROOT/scripts/localnet/start.sh"
}

teardown_localnet() { "$ROOT/scripts/localnet/stop.sh" || true; }

# join_node <index> — prepare a node home that is NOT in genesis: same document,
# its own keys and ports, peered at every node already running. This is what an
# operator does before asking to be admitted; admission itself is a separate
# authority transaction.
#
# Additive: no existing drill calls this, and the genesis-time path in init.sh is
# untouched.
join_node() {
  local i="$1" home; home="$(node_home "$i")"
  "$BIN" init "node$i" --chain-id "$CHAIN_ID" --home "$home" >/dev/null 2>&1
  "$BIN" keys add "operator$i" --keyring-backend test --home "$home" --output json \
    >"$NET/operator$i.json" 2>/dev/null
  cp "$(node_home 0)/config/genesis.json" "$home/config/genesis.json"
  # Peer to every node already running, not just node 0. With pex disabled a
  # joiner that knows only node 0 relies on it to relay every consensus message
  # for every other member, which is one node away from a stall.
  local rpc p2p grpc peers="" j jid
  for ((j = 0; j < i; j++)); do
    jid="$("$BIN" tendermint show-node-id --home "$(node_home "$j")")"
    peers="${peers}${peers:+,}${jid}@127.0.0.1:$((26656 + j * 100))"
  done
  rpc=$((26657 + i * 100)); p2p=$((26656 + i * 100)); grpc=$((9090 + i * 100))
  sed -i.bak \
    -e "s#laddr = \"tcp://127.0.0.1:26657\"#laddr = \"tcp://127.0.0.1:${rpc}\"#" \
    -e "s#laddr = \"tcp://0.0.0.0:26656\"#laddr = \"tcp://0.0.0.0:${p2p}\"#" \
    -e "s#persistent_peers = \"\"#persistent_peers = \"${peers}\"#" \
    -e "s#pex = true#pex = false#" \
    -e "s#allow_duplicate_ip = false#allow_duplicate_ip = true#" \
    -e "s#^timeout_commit = .*#timeout_commit = \"${TWILIGHT_LOCALNET_TIMEOUT_COMMIT:-200ms}\"#" \
    "$home/config/config.toml"
  sed -i.bak -e "s#address = \"localhost:9090\"#address = \"localhost:${grpc}\"#" "$home/config/app.toml"
  rm -f "$home/config/"*.bak
}

# wait_synced <index> [seconds] — true once the node reports it is no longer
# catching up AND is within two blocks of node 0. A node must be caught up
# BEFORE it is admitted: a validator that is still syncing produces nothing, and
# quorum stalls waiting for it.
wait_synced() {
  local i="$1" deadline=$((SECONDS + ${2:-90})) h_new h_ref
  while ((SECONDS < deadline)); do
    if [[ "$(rpc_get "$i" /status 2>/dev/null | jq -r '.result.sync_info.catching_up' 2>/dev/null)" == "false" ]]; then
      h_new="$(latest_height "$i")"; h_ref="$(latest_height 0)"
      if (( h_new > 0 && h_ref - h_new <= 2 )); then return 0; fi
    fi
    sleep 1
  done
  return 1
}

# ---- height helpers --------------------------------------------------------

latest_height() {
  local h
  h="$(rpc_get "$1" /status 2>/dev/null | jq -r '.result.sync_info.latest_block_height | tonumber' 2>/dev/null || true)"
  echo "${h:-0}"
}

# wait_height_node <node> <target> [timeout_s]
wait_height_node() {
  local node="$1" target="$2" deadline=$((SECONDS + ${3:-90}))
  while ((SECONDS < deadline)); do
    if (($(latest_height "$node") >= target)); then return 0; fi
    sleep 1
  done
  echo "timed out waiting for node$node to reach height $target" >&2
  return 1
}

# wait_online_height <target> <node...>
wait_online_height() {
  local target="$1"; shift
  local n
  for n in "$@"; do wait_height_node "$n" "$target" || return 1; done
}

# wait_all_height <target>  (all NODE_COUNT nodes)
wait_all_height() {
  local target="$1" n
  for ((n = 0; n < NODE_COUNT; n++)); do wait_height_node "$n" "$target" || return 1; done
}

# advance N blocks past the current min live height across the given nodes
advance_blocks() {
  local by="$1"; shift
  local base=999999999 h n
  for n in "$@"; do h="$(latest_height "$n")"; ((h < base)) && base="$h"; done
  for n in "$@"; do wait_height_node "$n" $((base + by)) || return 1; done
}

# ---- transaction submission (sets LAST_TXHASH / LAST_TXCODE) ----------------

LAST_TXHASH=""
LAST_TXCODE=""

_broadcast() { # <key> <home> <coreslot-subcommand...>
  local key="$1" home="$2"; shift 2
  "$BIN" coreslot "$@" \
    --from "$key" $KEYRING --home "$home" \
    --chain-id "$CHAIN_ID" --node "$(rpc_url 0)" \
    --gas 600000 --fees 0utwlt --broadcast-mode sync --output json -y 2>/dev/null
}

_wait_tx_code() { # <hash> -> prints DeliverTx code (or not_included)
  local hash="$1" i res
  for ((i = 0; i < 40; i++)); do
    res="$(rpc_get 0 "/tx?hash=0x$hash" 2>/dev/null || true)"
    if [[ -n "$res" ]] && jq -e '.result.tx_result' >/dev/null 2>&1 <<<"$res"; then
      jq -r '.result.tx_result.code // 0' <<<"$res"
      return 0
    fi
    sleep 1
  done
  echo "not_included"
}

_submit() { # <key> <home> <coreslot-subcommand...>
  local key="$1" home="$2"; shift 2
  LAST_TXHASH=""; LAST_TXCODE=""
  local out checkcode
  out="$(_broadcast "$key" "$home" "$@")" || true
  LAST_TXHASH="$(jq -r '.txhash // ""' <<<"$out" 2>/dev/null || echo "")"
  checkcode="$(jq -r '.code // empty' <<<"$out" 2>/dev/null || echo "")"
  if [[ -z "$LAST_TXHASH" ]]; then LAST_TXCODE="broadcast_error"; return 0; fi
  if [[ -n "$checkcode" && "$checkcode" != "0" ]]; then LAST_TXCODE="$checkcode"; return 0; fi
  LAST_TXCODE="$(_wait_tx_code "$LAST_TXHASH")"
  return 0
}

submit_authority() { _submit operator0 "$(node_home 0)" "$@"; }
submit_emergency() { _submit operator1 "$(node_home 1)" "$@"; }

# inclusion height of an included tx (empty if not found)
tx_height() { rpc_get 0 "/tx?hash=0x$1" 2>/dev/null | jq -r '.result.height // ""' 2>/dev/null || echo ""; }

# ---- queries ---------------------------------------------------------------

q() { "$BIN" coreslot-query "$@" --node "$(rpc_url 0)" --output json 2>/dev/null; }

active_count() { q active 2>/dev/null | jq -r '(.slots // []) | length' 2>/dev/null || echo "?"; }
last_applied_count() { q last-applied 2>/dev/null | jq -r '(.validators // []) | length' 2>/dev/null || echo "?"; }
slot_status() { q slot "$1" 2>/dev/null | jq -r '.slot.status // "?"' 2>/dev/null || echo "?"; }
slot_power() { q slot "$1" 2>/dev/null | jq -r '.slot.consensus_power // "?"' 2>/dev/null || echo "?"; }
next_slot_id() { q slots 2>/dev/null | jq -r '[(.slots // [])[].slot_id | tonumber] | (max // 0) + 1' 2>/dev/null || echo "?"; }
slot_voting_power() { q params 2>/dev/null | jq -r '.params.slot_voting_power // "?"' 2>/dev/null || echo "?"; }

# ---- provenance: CometBFT num_val_updates from a node log -------------------

timestamp_utc() { date -u +%Y-%m-%dT%H:%M:%SZ; }

# assert_num_val_updates_exact_at <action> <height> <expected> [node...]
# Every relevant node must have a valid finalized-block count equal to expected.
LAST_NUM_VAL_UPDATES=""
assert_num_val_updates_exact_at() {
  local action="$1" height="$2" expected="$3"
  shift 3
  local nodes=("$@") n line value result error failures=0
  if ((${#nodes[@]} == 0)); then
    for ((n = 0; n < NODE_COUNT; n++)); do nodes+=("$n"); done
  fi

  for n in "${nodes[@]}"; do
    line="$(sed $'s/\x1b\\[[0-9;]*m//g' "$NET/logs/node$n.log" 2>/dev/null \
      | grep 'finalized block' | grep -E "height=$height " | head -1 || true)"
    value="$(grep -oE 'num_val_updates=[0-9]+' <<<"$line" 2>/dev/null | head -1 | cut -d= -f2 || true)"
    result="PASS"
    error=""
    if [[ -z "$line" ]]; then
      result="FAIL"; error="missing finalized-block record"; failures=$((failures + 1))
    elif [[ ! "$value" =~ ^[0-9]+$ ]]; then
      result="FAIL"; error="missing or malformed num_val_updates"; failures=$((failures + 1))
    elif [[ "$value" != "$expected" ]]; then
      result="FAIL"; error="expected $expected"; failures=$((failures + 1))
    fi
    jq -cn \
      --arg drill "$DRILL" --arg run_id "$RUN_ID" --arg action "$action" \
      --arg node "$n" --arg height "$height" --arg num_val_updates "${value:-}" \
      --arg expected_num_val_updates "$expected" --arg result "$result" \
      --arg error "$error" --arg timestamp "$(timestamp_utc)" \
      '{drill:$drill,run_id:$run_id,action:$action,node_index:($node|tonumber),height:($height|tonumber),num_val_updates:$num_val_updates,expected_num_val_updates:$expected_num_val_updates,result:$result,error:$error,timestamp:$timestamp}' \
      >>"$PROVENANCE"
    [[ "$result" == "PASS" ]] || echo "  provenance node$n height=$height: FAIL ($error, got ${value:-missing})" >&2
  done

  if ((failures > 0)); then
    LAST_NUM_VAL_UPDATES="FAIL"
    return 1
  fi
  LAST_NUM_VAL_UPDATES="$expected"
  echo "  provenance action=$action height=$height nodes=[${nodes[*]}] num_val_updates=$expected: PASS"
}

# ---- agreement -------------------------------------------------------------

# agree_nodes "<idx...>" "<action>" -> persist evidence and assert hash agreement
agree_nodes() {
  local nodes="${1:-}" action="${2:-checkpoint}"
  if [[ -n "$nodes" ]]; then
    AGREE_NODES="$nodes" AGREE_ACTION="$action" AGREE_EVIDENCE_FILE="${HASHES:-}" "$ROOT/scripts/localnet/agree.sh"
  else
    AGREE_ACTION="$action" AGREE_EVIDENCE_FILE="${HASHES:-}" "$ROOT/scripts/localnet/agree.sh"
  fi
}

# ---- evidence --------------------------------------------------------------

init_evidence() {
  mkdir -p "$EVID_DIR"
  mkdir -p "$ROOT/build/localnet/evidence"
  echo "$RUN_ID" >"$ROOT/build/localnet/evidence/latest-run.txt"
  SUMMARY="$EVID_DIR/summary.csv"
  HASHES="$EVID_DIR/hashes.jsonl"
  PROVENANCE="$EVID_DIR/provenance.jsonl"
  : >"$HASHES"
  : >"$PROVENANCE"
  echo "action,height_before,tx_hash,tx_code,height_after,active_count,num_val_updates,agree,result,checked_slot_id,checked_slot_status,checked_slot_power" >"$SUMMARY"
  echo "run_id=$RUN_ID evidence_dir=$EVID_DIR"
}

# record_row <action> <h_before> <txhash> <txcode> <h_after> <active> <numvu> <agree> <result> [checked_slot_id] [checked_slot_status] [checked_slot_power]
record_row() {
  local checked_slot_id="${10:--}" checked_slot_status="${11:--}" checked_slot_power="${12:--}"
  echo "$1,$2,$3,$4,$5,$6,$7,$8,$9,$checked_slot_id,$checked_slot_status,$checked_slot_power" >>"$SUMMARY"
  printf '  [%s] %s  tx=%s code=%s  h:%s->%s active=%s num_val_updates=%s agree=%s\n' \
    "$9" "$1" "${3:0:10}" "$4" "$2" "$5" "$6" "$7" "$8"
}
